/**
 *  CONSTRUCT
 *  ACT_ID_... = {
 *      ACT_.. : "";
 *  }
 */

/**
 *  START_CM
 *  Common
 */
export const ACT_BACK = "COMMON_BACK_ACT";

/**
 *  Common
 *      Tìm kiếm
 */
export const ACT_ID_SEARCH = {
  ACT_SEARCH_CO_SO_SAN_XUAT: "key-co-so-san-xuat",
  ACT_SEARCH_NGHIEP_VU_THANH_TRA: "key-nghiep-vu-thanh-tra",
  ACT_SEARCH_PHAN_ANH_KIEN_NGHI: "key-phan-anh-kien-nghi",
  ACT_SEARCH_NGO_DOC_THUC_PHAM: "key-ngo-doc-thuc-pham",
  ACT_SEARCH_O_NHIEM_THUC_PHAM: "key-o-nhiem-thuc-pham",
};

export const ACT_ID_HOME = {
  ACT_CSSX: "CO_SO_SAN_XUAT",
  ACT_PTT: "PHONG_THANH_TRA",
  ACT_PNV: "PHONG_NGHIEP_VU",
  ACT_NVVP: "NGHIEP_VU_VAN_PHONG",
  ACT_NVC: "NGHIEP_VU_CHUNG",
  ACT_TBCBSP: "THONG_BAO_CONG_BO_SAN_PHAM",
};
/**
 *  END_CM
 */

/**
 *  START_SYSTEM
 *  Hệ thống
 *      Người dùng
 */
export const ACT_ID_ACCOUNT = {
  ACT_LIST: "ACCOUNT_LIST_ACT",
  ACT_CREATE: "ACCOUNT_CREATE_ACT",
  ACT_UPDATE: "ACCOUNT_UPDATE_ACT",
  ACT_DELETE: "ACCOUNT_DELETE_ACT",
  ACT_SEARCH: "ACCOUNT_SEARCH_ACT",
  ACT_CHANGE_ACTIVE: "ACCOUNT_CHANGE_ACTIVE_ACT",
  ACT_UNLOCK: "ACCOUNT_UNLOCK_ACT",
};

/**
 *  Hệ thống
 *      Nhóm người dùng
 */
export const ACT_ID_ACCOUNT_GROUP = {
  ACT_LIST: "ACCOUNT_GROUP_LIST_ACT",
  ACT_CREATE: "ACCOUNT_GROUP_CREATE_ACT",
  ACT_UPDATE: "ACCOUNT_GROUP_UPDATE_ACT",
  ACT_DELETE: "ACCOUNT_GROUP_DELETE_ACT",
  ACT_SEARCH: "ACCOUNT_GROUP_SEARCH_ACT",
  ACT_CHANGE_ACTIVE: "ACCOUNT_GROUP_CHANGE_ACTIVE_ACT",
  ACT_DECENTRALIZATION: "ACCOUNT_GROUP_DECENTRALIZATION_ACT",
};

/**
 *  Hệ thống
 *      Quyền
 */
export const ACT_ID_PERMISSION = {
  ACT_LIST: "PERMISSION_LIST_ACT",
  ACT_CREATE: "PERMISSION_CREATE_ACT",
  ACT_UPDATE: "PERMISSION_UPDATE_ACT",
  ACT_DELETE: "PERMISSION_DELETE_ACT",
  ACT_MOVE: "PERMISSION_MOVE_ACT",
  ACT_VIEW_MOBILE: "PERMISSION_VIEW_MOBILE_ACT",
};

/**
 *  Hệ thống
 *      Dịch vụ
 */
export const ACT_ID_SERVICE = {
  ACT_LIST: "SERVICE_LIST_ACT",
  ACT_CREATE: "SERVICE_CREATE_ACT",
  ACT_UPDATE: "SERVICE_UPDATE_ACT",
  ACT_DELETE: "SERVICE_DELETE_ACT",
  ACT_SEARCH: "SERVICE_SEARCH_ACT",
};

/**
 *  Hệ thống
 *      Cấu hình
 */
export const ACT_ID_CAU_HINH = {
  ACT_LIST: "CAU_HINH_LIST_ACT",
  ACT_CREATE: "CAU_HINH_CREATE_ACT",
  ACT_UPDATE: "CAU_HINH_UPDATE_ACT",
  ACT_DELETE: "CAU_HINH_DELETE_ACT",
};
/**
 *  END_SYSTEM
 */

/**
 *  START_DM
 *  Danh mục
 *      Địa bàn
 */
export const ACT_ID_DANH_MUC_DIA_BAN = {
  ACT_LIST: "DANH_MUC_DIA_BAN_LIST_ACT",
  ACT_CREATE: "DANH_MUC_DIA_BAN_CREATE_ACT",
  ACT_UPDATE: "DANH_MUC_DIA_BAN_UPDATE_ACT",
  ACT_DELETE: "DANH_MUC_DIA_BAN_DELETE_ACT",
  ACT_SEARCH: "DANH_MUC_DIA_BAN_SEARCH_ACT",
  ACT_SYNC: "DANH_MUC_DIA_BAN_SYNC_ACT",
};
export const ACT_ID_DIA_BAN = {
  ACT_LIST: "DIA_BAN_LIST_ACT",
  ACT_CREATE: "DIA_BAN_CREATE_ACT",
  ACT_UPDATE: "DIA_BAN_UPDATE_ACT",
  ACT_DELETE: "DIA_BAN_DELETE_ACT",
};
/**
 *  END_DM
 */

/**
 *  START_QLCSSXKD
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Danh mục
 *          Linh vực
 */
export const ACT_ID_LINH_VUC = {
  ACT_LIST: "LINH_VUC_LIST_ACT",
  ACT_CREATE: "LINH_VUC_CREATE_ACT",
  ACT_UPDATE: "LINH_VUC_UPDATE_ACT",
  ACT_DELETE: "LINH_VUC_DELETE_ACT",
  ACT_SEARCH: "LINH_VUC_SEARCH_ACT",
};

/**
 *  Danh mục -> Đoàn thẩm định
 */

export const ACT_ID_DOAN_THAM_DINH = {
  ACT_LIST: "DOAN_THAM_DINH_LIST_ACT",
  ACT_CREATE: "DOAN_THAM_DINH_CREATE_ACT",
  ACT_UPDATE: "DOAN_THAM_DINH_UPDATE_ACT",
  ACT_DELETE: "DOAN_THAM_DINH_DELETE_ACT",
  ACT_SEARCH: "DOAN_THAM_DINH_SEARCH_ACT",
};

/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Danh mục
 *          Loại hình cơ sở
 */
export const ACT_ID_LOAI_HINH_CO_SO = {
  ACT_LIST: "LOAI_HINH_CO_SO_LIST_ACT",
  ACT_CREATE: "LOAI_HINH_CO_SO_CREATE_ACT",
  ACT_UPDATE: "LOAI_HINH_CO_SO_UPDATE_ACT",
  ACT_DELETE: "LOAI_HINH_CO_SO_DELETE_ACT",
  ACT_SEARCH: "LOAI_HINH_CO_SO_SEARCH_ACT",
};

/**
 *  Quản lý Phòng ban
 *      Danh mục
 *          Quản lý phòng ban
 */
export const ACT_ID_QUAN_LY_PHONG_BAN = {
  ACT_LIST: "QUAN_LY_PHONG_BAN_LIST_ACT",
  ACT_CREATE: "QUAN_LY_PHONG_BAN_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_PHONG_BAN_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_PHONG_BAN_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_PHONG_BAN_SEARCH_ACT",
};

/**
 *  Quản lý quốc gia
 *      Danh muc
 *        Quốc gia
 */
export const ACT_ID_QUAN_LY_QUOC_GIA = {
  ACT_LIST: "QUAN_LY_QUOC_GIA_LIST_ACT",
  ACT_CREATE: "QUAN_LY_DQUOC_GIA_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_QUOC_GIA_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_QUOC_GIA_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_QUOC_GIA_SEARCH_ACT",
};

/**
 *  Quản lý Tài sản
 *      Tài sản
 */
export const ACT_ID_TAI_SAN = {
  ACT_LIST: "TAI_SAN_LIST_ACT",
  ACT_CREATE: "TAI_SAN_CREATE_ACT",
  ACT_UPDATE: "TAI_SAN_UPDATE_ACT",
  ACT_DELETE: "TAI_SAN_DELETE_ACT",
  ACT_SEARCH: "TAI_SAN_SEARCH_ACT",
  ACT_DOWNLOAD: "TAI_SAN_DOWNLOAD_ACT",
  ACT_LIST_DETAIL: "TAI_SAN_LIST_DETAIL_ACT",
};

export const ACT_ID_TAI_SAN_NHOM_TAI_SAN = {
  ACT_LIST: "TAI_SAN_NHOM_TAI_SAN_LIST_ACT",
  ACT_CREATE: "TAI_SAN_NHOM_TAI_SAN_CREATE_ACT",
  ACT_UPDATE: "TAI_SAN_NHOM_TAI_SAN_UPDATE_ACT",
  ACT_DELETE: "TAI_SAN_NHOM_TAI_SAN_DELETE_ACT",
  ACT_SEARCH: "TAI_SAN_NHOM_TAI_SAN_SEARCH_ACT",
};

//Báo cáo thống kê sự kiện
export const ACT_ID_BAO_CAO_THONG_KE_TAI_SAN_CO_DINH = {
  ACT_LIST: "QUAN_LY_TAI_SAN_TAI_SAN_CO_DINH_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_CONG_CU_DUNG_CU = {
  ACT_LIST: "QUAN_LY_TAI_TAI_CONG_CU_DUNG_CU_THONG_KE_BAO_CAO_ACT",
};

/**
 *  Quản lý Tài sản
 *      Tài sản
 */
export const ACT_ID_THONG_TIN_NGHI_PHEP = {
  ACT_LIST: "THONG_TIN_NGHI_PHEP_LIST_ACT",
  ACT_CREATE: "THONG_TIN_NGHI_PHEP_CREATE_ACT",
  ACT_UPDATE: "THONG_TIN_NGHI_PHEP_UPDATE_ACT",
  ACT_DELETE: "THONG_TIN_NGHI_PHEP_DELETE_ACT",
  ACT_SEARCH: "THONG_TIN_NGHI_PHEP_SEARCH_ACT",
  ACT_DOWNLOAD: "THONG_TIN_NGHI_PHEP_DOWNLOAD_ACT",
};

export const ACT_ID_CAU_HINH_NGHI_PHEP = {
  ACT_LIST: "CAU_HINH_NGHI_PHEP_LIST_ACT",
  ACT_CREATE: "CAU_HINH_NGHI_PHEP_CREATE_ACT",
  ACT_UPDATE: "CAU_HINH_NGHI_PHEP_UPDATE_ACT",
  ACT_DELETE: "CAU_HINH_NGHI_PHEP_DELETE_ACT",
  ACT_SEARCH: "CAU_HINH_NGHI_PHEP_SEARCH_ACT",
};
/**
 *  Quản lý Nghi Phep
 *      nghi phep
 */
export const ACT_ID_QUAN_LY_NGHI_PHEP = {
  ACT_VIEW_CURRENT_DATE: "QUAN_LY_NGHI_PHEP_SAN_VIEW_CURRENT_DATE_ACT",
  ACT_LIST: "QUAN_LY_NGHI_PHEP_LIST_ACT",
  ACT_CREATE: "QUAN_LY_NGHI_PHEP_SAN_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_NGHI_PHEP_SAN_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_NGHI_PHEP_SAN_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_NGHI_PHEP_SAN_SEARCH_ACT",
  ACT_PHE_DUYET: "QUAN_LY_NGHI_PHEP_SAN_PHE_DUYET_ACT",
  ACT_TRINH_PHE_DUYET: "QUAN_LY_NGHI_PHEP_SAN_TRINH_PHE_DUYET_ACT",
  ACT_TU_CHOI_PHE_DUYET: "QUAN_LY_NGHI_PHEP_SAN_TU_CHOI_PHE_DUYET_ACT",
  ACT_CHI_TIET_NGHI_PHEP: "QUAN_LY_NGHI_PHEP_CHI_TIET_ACT",
};

/**
 *  Quản lý Nghi Phep
 *      nghi phep
 */
export const ACT_ID_QUAN_LY_CONG_TAC = {
  ACT_LIST: "QUAN_LY_CONG_TAC_LIST_ACT",
  ACT_PHE_DUYET: "QUAN_LY_CONG_TAC_PHE_DUYET_ACT",
  ACT_TRINH_PHE_DUYET: "QUAN_LY_CONG_TAC_TRINH_PHE_DUYET_ACT",
};

/**
 *  Quản lý đối ngoại
 *      quản lý đoàn vào
 */
export const ACT_ID_QUAN_LY_DOAN_VAO = {
  ACT_LIST: "QUAN_LY_DOAN_VAO_LIST_ACT",
  ACT_CREATE: "QUAN_LY_DOAN_VAO_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_DOAN_VAO_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_DOAN_VAO_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_DOAN_VAO_SEARCH_ACT",
  ACT_ATTACH_FILE: "QUAN_LY_DOAN_VAO_ATTACH_FILE_ACT",
};

/**
 *  Quản lý đối ngoại
 *      quản lý đoàn ra
 */
export const ACT_ID_QUAN_LY_DOAN_RA = {
  ACT_LIST: "QUAN_LY_DOAN_RA_LIST_ACT",
  ACT_CREATE: "QUAN_LY_DOAN_RA_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_DOAN_RA_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_DOAN_RA_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_DOAN_RA_SEARCH_ACT",
  ACT_ATTACH_FILE: "QUAN_LY_DOAN_RA_ATTACH_FILE_ACT",
};

/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Cơ sở sản xuất kinh doanh
 */
export const ACT_ID_CO_SO_SAN_XUAT_KINH_DOANH = {
  ACT_LIST: "CO_SO_SAN_XUAT_KINH_DOANH_LIST_ACT",
  ACT_CREATE: "CO_SO_SAN_XUAT_KINH_DOANH_CREATE_ACT",
  ACT_UPDATE: "CO_SO_SAN_XUAT_KINH_DOANH_UPDATE_ACT",
  ACT_DELETE: "CO_SO_SAN_XUAT_KINH_DOANH_DELETE_ACT",

  ACT_SEARCH: "CO_SO_SAN_XUAT_KINH_DOANH_SEARCH_ACT",
  ACT_BAOCAO: "CO_SO_SAN_XUAT_KINH_DOANH_ACT_BAOCAO",
  ACT_DETAIL: "CO_SO_SAN_XUAT_KINH_DOANH_DETAIL_ACT",
  ACT_EXPORT: "CO_SO_SAN_XUAT_KINH_DOANH_EXPORT_ACT",
  ACT_DOWNLOAD_GCN: "CO_SO_SAN_XUAT_KINH_DOANH_DOWNLOAD_GCN_ACT",
  ACT_REPORT: "CO_SO_SAN_XUAT_KINH_DOANH_REPORT_ACT",
  ACT_IMPORT: "CO_SO_SAN_XUAT_KINH_DOANH_IMPORT_ACT",
  ACT_TCB_LIST: "CO_SO_SAN_XUAT_KINH_DOANH_TCB_LIST_ACT",
  ACT_TCB_CREATE: "CO_SO_SAN_XUAT_KINH_DOANH_TCB_CREATE_ACT",
  ACT_TCB_UPDATE: "CO_SO_SAN_XUAT_KINH_DOANH_TCB_UPDATE_ACT",
  ACT_TCB_EXPORT: "CO_SO_SAN_XUAT_KINH_DOANH_TCB_EXPORT_ACT",

  ACT_LIST_DRAFT: "CO_SO_SAN_XUAT_KINH_DOANH_LIST_DRAFT_ACT",

  ACT_CHUYENXULY: "CO_SO_SAN_XUAT_KINH_DOANH_CHUYENXULY_ACT",
  ACT_TRINHPHEDUYET: "CO_SO_SAN_XUAT_KINH_DOANH_TRINHPHEDUYET_ACT",
  ACT_PHEDUYET: "CO_SO_SAN_XUAT_KINH_DOANH_PHEDUYET_ACT",
  ACT_ALLOW_VIEW_ALL: "CO_SO_SAN_XUAT_KINH_DOANH_ALLOW_VIEW_ALL_ACT",
};

export const ACT_ID_CSSXKD_QUAN_HUYEN = {
  ACT_LIST: "CSSXKD_QUAN_HUYEN_LIST_ACT",
  ACT_CREATE: "CSSXKD_QUAN_HUYEN_CREATE_ACT",
  ACT_UPDATE: "CSSXKD_QUAN_HUYEN_UPDATE_ACT",
  ACT_DELETE: "CSSXKD_QUAN_HUYEN_DELETE_ACT",
  ACT_SEARCH: "CSSXKD_QUAN_HUYEN_SEARCH_ACT",
  ACT_EXPORT: "CSSXKD_QUAN_HUYEN_EXPORT_ACT",
};

/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Hồ sơ tiếp nhận một cửa
 */
export const ACT_ID_HO_SO_TIEP_NHAN_MOT_CUA = {
  ACT_LIST: "HO_SO_TIEP_NHAN_MOT_CUA_LIST_ACT",
  ACT_ADD_TO_CSSXKD: "HO_SO_TIEP_NHAN_MOT_CUA_THEM_CSSXKD",
  ACT_ADD_TO_HSCGCN: "HO_SO_TIEP_NHAN_MOT_CUA_THEM_HSCGCN",
  ACT_REPORT: "HO_SO_TIEP_NHAN_MOT_CUA_REPORT_ACT",
  ACT_DONG_BO_HO_SO: "HO_SO_TIEP_NHAN_MOT_CUA_DONG_BO_HO_SO_ACT",
};

/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Thống ke báo cáo
 */
export const ACT_ID_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO = {
  ACT_LIST: "CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO_LIST_ACT",
  ACT_LIST_CO_SO: "CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO_LIST_CO_SO_ACT",
  ACT_SO_LIEU_TONG_HOP:
    "CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO_SO_LIEU_TONG_HOP_ACT",
};
/**
 *  END_QLCSSXKD
 */

/**
 *  START_QLVBPL
 *  Quản lý văn bản pháp luật
 *      Văn bản pháp luật
 */
export const ACT_ID_VAN_BAN_PHAP_LUAT = {
  ACT_LIST: "VAN_BAN_PHAP_LUAT_LIST_ACT",
  ACT_CREATE: "VAN_BAN_PHAP_LUAT_CREATE_ACT",
  ACT_UPDATE: "VAN_BAN_PHAP_LUAT_UPDATE_ACT",
  ACT_DELETE: "VAN_BAN_PHAP_LUAT_DELETE_ACT",
  ACT_SEARCH: "VAN_BAN_PHAP_LUAT_SEARCH_ACT",
  ACT_DETAIL: "VAN_BAN_PHAP_LUAT_DETAIL_ACT",
  ACT_DETAIL_PDF: "VAN_BAN_PHAP_LUAT_DETAIL_PDF_ACT",
  ACT_DETAIL_LQ: "VAN_BAN_PHAP_LUAT_DETAIL_LQ_ACT",
  ACT_DETAIL_TT: "VAN_BAN_PHAP_LUAT_DETAIL_TT_ACT",
  ACT_DETAIL_LD: "VAN_BAN_PHAP_LUAT_DETAIL_LD_ACT",
  ACT_DETAIL_TV: "VAN_BAN_PHAP_LUAT_DETAIL_TV_ACT",
};

/**
 *  Quản lý văn bản pháp luật
 *      Danh mục
 *          Lĩnh vực
 */
export const ACT_ID_VAN_BAN_PHAP_LUAT_DANH_MUC_LINH_VUC = {
  ACT_LIST: "VBPL_DANH_MUC_LINH_VUC_LIST_ACT",
  ACT_CREATE: "VBPL_DANH_MUC_LINH_VUC_CREATE_ACT",
  ACT_UPDATE: "VBPL_DANH_MUC_LINH_VUC_UPDATE_ACT",
  ACT_DELETE: "VBPL_DANH_MUC_LINH_VUC_DELETE_ACT",
  ACT_SEARCH: "VBPL_DANH_MUC_LINH_VUC_SEARCH_ACT",
};
/**
 *  END_QLVBPL
 */

/**
 *  START_QLNS
 *  Quản lý nhân sự
 *      Danh mục
 *          Phòng ban
 */
export const ACT_ID_PHONG_BAN = {
  ACT_LIST: "PHONG_BAN_LIST_ACT",
  ACT_CREATE: "PHONG_BAN_CREATE_ACT",
  ACT_UPDATE: "PHONG_BAN_UPDATE_ACT",
  ACT_DELETE: "PHONG_BAN_DELETE_ACT",
  ACT_SEARCH: "PHONG_BAN_SEARCH_ACT",
};

/**
 *  Quản lý nhân sự
 *      Danh mục
 *          Danh hiệu thi đua
 */
export const ACT_ID_DANHHIEU_THIDUA = {
  ACT_LIST: "DANHHIEU_THIDUA_LIST_ACT",
  ACT_CREATE: "DANHHIEU_THIDUA_CREATE_ACT",
  ACT_UPDATE: "DANHHIEU_THIDUA_UPDATE_ACT",
  ACT_DELETE: "DANHHIEU_THIDUA_DELETE_ACT",
  ACT_SEARCH: "DANHHIEU_THIDUA_SEARCH_ACT",
};

/**
 *  Quản lý nhân sự
 *      Nhân sự
 */
export const ACT_ID_NHAN_SU = {
  ACT_LIST: "NHAN_SU_LIST_ACT",
  ACT_CREATE: "NHAN_SU_CREATE_ACT",
  ACT_UPDATE: "NHAN_SU_UPDATE_ACT",
  ACT_DELETE: "NHAN_SU_DELETE_ACT",
  ACT_SEARCH: "NHAN_SU_SEARCH_ACT",
  ACT_DETAIL: "NHAN_SU_DETAIL_ACT",
  ACT_DETAIL_NGHIPHEP: "NHAN_SU_DETAIL_NGHIPHEP_ACT",
  ACT_DETAIL_TAISANCONG: "NHAN_SU_DETAIL_TAISANCONG_ACT",
  ACT_DETAIL_KHENTHUONG: "NHAN_SU_DETAIL_KHENTHUONG_ACT",
  ACT_DETAIL_DTTH: "NHAN_SU_DETAIL_DTTH_ACT",
};

/**
 *  Quản lý nhân sự
 *      Thi đua khen thưởng
 */
export const ACT_ID_QUAN_LY_THI_DUA_KHEN_THUONG = {
  ACT_LIST: "QUAN_LY_THI_DUA_KHEN_THUONG_LIST_ACT",
  ACT_DETAIL: "QUAN_LY_THI_DUA_KHEN_THUONG_DETAIL_ACT",
  ACT_CREATE: "QUAN_LY_THI_DUA_KHEN_THUONG_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_THI_DUA_KHEN_THUONG_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_THI_DUA_KHEN_THUONG_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_THI_DUA_KHEN_THUONG_SEARCH_ACT",
};

/**
 *  Quản lý nhân sự
 *      Chương trình đào tạo tập huấn
 */
export const ACT_ID_CHUONGTRINH_DAOTAOTAPHUAN = {
  ACT_LIST: "CHUONGTRINH_DAOTAOTAPHUAN_LIST_ACT",
  ACT_CREATE: "CHUONGTRINH_DAOTAOTAPHUAN_CREATE_ACT",
  ACT_UPDATE: "CHUONGTRINH_DAOTAOTAPHUAN_UPDATE_ACT",
  ACT_DELETE: "CHUONGTRINH_DAOTAOTAPHUAN_DELETE_ACT",
  ACT_SEARCH: "CHUONGTRINH_DAOTAOTAPHUAN_SEARCH_ACT",
};

/**
 *  Quản lý nhân sự
 *      Đào tạo tập huấn
 */
export const ACT_ID_DAOTAO_TAPHUAN = {
  ACT_LIST: "DAOTAO_TAPHUAN_LIST_ACT",
  ACT_CREATE: "DAOTAO_TAPHUAN_CREATE_ACT",
  ACT_UPDATE: "DAOTAO_TAPHUAN_UPDATE_ACT",
  ACT_DELETE: "DAOTAO_TAPHUAN_DELETE_ACT",
  ACT_SEARCH: "DAOTAO_TAPHUAN_SEARCH_ACT",
  ACT_DETAIL: "DAOTAO_TAPHUAN_DETAIL_ACT",
};

/**
 *  Quản lý nhân sự
 *      Nghiệp vụ
 */
export const ACT_ID_NGHIPHEP = {
  ACT_LIST: "NGHIPHEP_LIST_ACT",
  ACT_LIST_CHOPHEDUYET: "NGHIPHEP_LIST_CHOPHEDUYET_ACT",
  ACT_CREATE: "NGHIPHEP_CREATE_ACT",
  ACT_UPDATE: "NGHIPHEP_UPDATE_ACT",
  ACT_DELETE: "NGHIPHEP_DELETE_ACT",
  ACT_SEARCH: "NGHIPHEP_SEARCH_ACT",
  ACT_CONFIRM: "NGHIPHEP_CONFIRM_ACT",
  ACT_NOTCONFIRM: "NGHIPHEP_NOTCONFIRM_ACT",
};

/**
 *  Quản lý nhân sự
 *      Nghỉ phép
 */
export const ACT_ID_NGHIPHEP_USER = {
  ACT_LIST: "NGHIPHEP_USER_LIST_ACT",
  ACT_CREATE: "NGHIPHEP_USER_CREATE_ACT",
  ACT_UPDATE: "NGHIPHEP_USER_UPDATE_ACT",
  ACT_DELETE: "NGHIPHEP_USER_DELETE_ACT",
  ACT_SEARCH: "NGHIPHEP_USER_SEARCH_ACT",
};

/**
 *  Quản lý nhân sự
 *      Tài sản công
 */
export const ACT_ID_TAISANCONG = {
  ACT_LIST: "TAISANCONG_LIST_ACT",
  ACT_CREATE: "TAISANCONG_CREATE_ACT",
  ACT_UPDATE: "TAISANCONG_UPDATE_ACT",
  ACT_DELETE: "TAISANCONG_DELETE_ACT",
  ACT_SEARCH: "TAISANCONG_SEARCH_ACT",
};
/**
 *  END_QLNS
 */

/**
 *  START_QLQTNVTT
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Quy trình nghiệp vụ thanh tra || Phòng ban
 */
export const ACT_ID_QTNVTT = {
  ACT_ALLOW_THANH_TRA: "QTNVTT_ALLOW_THANH_TRA",
  ACT_ALLOW_NGHIEP_VU: "QTNVTT_ALLOW_NGHIEP_VU",
  ACT_ALLOW_DOI1: "QTNVTT_ALLOW_DOI1",
  ACT_ALLOW_DOI2: "QTNVTT_ALLOW_DOI2",
};

export const ACT_ID_QLONATTP = {
  ACT_ALLOW_THANH_TRA: "QLONATTP_ALLOW_THANH_TRA",
  ACT_ALLOW_NGHIEP_VU: "QLONATTP_ALLOW_NGHIEP_VU",
  ACT_ALLOW_DOI1: "QLONATTP_ALLOW_DOI1",
  ACT_ALLOW_DOI2: "QLONATTP_ALLOW_DOI2",
};

/**
 *  Quản lý quy trình nghiệp vụ thanht ra
 *      Kế hoạch thanh tra
 */
export const ACT_ID_QTNVTT_KE_HOACH_THANH_TRA = {
  ACT_LIST: "QTNVTT_KE_HOACH_THANH_TRA_LIST_ACT",
  ACT_CREATE: "QTNVTT_KE_HOACH_THANH_TRA_CREATE_ACT",
  ACT_UPDATE: "QTNVTT_KE_HOACH_THANH_TRA_UPDATE_ACT",
  ACT_DELETE: "QTNVTT_KE_HOACH_THANH_TRA_DELETE_ACT",
  ACT_SEARCH: "QTNVTT_KE_HOACH_THANH_TRA_SEARCH_ACT",
  ACT_ALLOW_THANH_TRA: "QTNVTT_KE_HOACH_THANH_TRA_ALLOW_THANH_TRA_ACT",
  ACT_ALLOW_NGHIEP_VU: "QTNVTT_KE_HOACH_THANH_TRA_ALLOW_NGHIEP_VU_ACT",
  ACT_CREATE_CUOC_THANH_TRA: "QTNVTT_CUOC_THANH_TRA_CREATE_CUOC_THANH_TRA_ACT",
  ACT_LIST_CUOC_THANH_TRA: "QTNVTT_CUOC_THANH_TRA_LIST_CUOC_THANH_TRA_ACT",
  ACT_TRINHPHEDUYET: "QTNVTT_KE_HOACH_THANH_TRA_TRINH_PHE_DUYET",
  ACT_PHE_DUYET: "QTNVTT_KE_HOACH_THANH_TRA_PHE_DUYET",
  ACT_BAN_HANH: "QTNVTT_KE_HOACH_THANH_TRA_BAN_HANH",
  ACT_VIEW_BAN_HANH: "QTNVTT_KE_HOACH_THANH_TRA_VIEW_BAN_HANH",
  ACT_DOWNLOAD: "QTNVTT_KE_HOACH_THANH_TRA_DOWNLOAD",
  ACT_DETAIL: "QTNVTT_KE_HOACH_THANH_TRA_DETAIL",
};

export const ACT_ID_QTNVTT_KE_HOACH_THANH_TRA_DETAIL = {
  ACT_PHE_DUYET: "QTNVTT_KE_HOACH_THANH_TRA_DETAIL_PHE_DUYET_ACT",
};
/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Cuộc thanh tra
 */
export const ACT_ID_QTNVTT_CUOC_THANH_TRA = {
  ACT_LIST: "QTNVTT_CUOC_THANH_TRA_LIST_ACT",
  ACT_CREATE: "QTNVTT_CUOC_THANH_TRA_CREATE_ACT",
  ACT_UPDATE: "QTNVTT_CUOC_THANH_TRA_UPDATE_ACT",
  ACT_DELETE: "QTNVTT_CUOC_THANH_TRA_DELETE_ACT",
  ACT_SEARCH: "QTNVTT_CUOC_THANH_TRA_SEARCH_ACT",
  ACT_TRINH_PHE_DUYET: "QTNVTT_CUOC_THANH_TRA_TRINH_PHE_DUYET_ACT",
  ACT_PHE_DUYET: "QTNVTT_CUOC_THANH_TRA_PHE_DUYET_ACT",
  ACT_BAN_HANH: "QTNVTT_CUOC_THANH_TRA_BAN_HANH_ACT",
  ACT_KET_LUAN: "QTNVTT_CUOC_THANH_TRA_KET_LUAN_ACT",
  ACT_THANH_TRA: "QTNVTT_CUOC_THANH_TRA_THANH_TRA_ACT",
  ACT_ATTACH_FILE: "QTNVTT_CUOC_THANH_TRA_ATTACH_FILE_ACT",
  ACT_BAN_HANH_QDTLDTKT: "QTNVTT_CUOC_THANH_TRA_BAN_HANH_QDTLDTKT_ACT",

  ACT_THANH_TRA_LQD: "QTNVTT_CUOC_THANH_TRA_THANH_TRA_LQD_ACT",
  ACT_THANH_TRA_QDXPVPHC: "QTNVTT_CUOC_THANH_TRA_THANH_TRA_QDXPVPHC_ACT",
  ACT_THANH_TRA_KQTT: "QTNVTT_CUOC_THANH_TRA_THANH_TRA_KQTT_ACT",
  ACT_THANH_TRA_KLTT: "QTNVTT_CUOC_THANH_TRA_THANH_TRA_KLTT_ACT",
  ACT_THANH_TRA_FILES: "QTNVTT_CUOC_THANH_TRA_THANH_TRA_FILES_ACT",
  ACT_THANH_TRA_KT: "QTNVTT_CUOC_THANH_TRA_THANH_TRA_KT_ACT",
  ACT_THANH_TRA_ALLOW_UPDATE:
    "QTNVTT_CUOC_THANH_TRA_THANH_TRA_ALLOW_UPDATE_ACT",
  ACT_THANH_TRA_CHANGE_DURATION_UPDATE:
    "QTNVTT_CUOC_THANH_TRA_THANH_TRA_CHANGE_DURATION_UPDATE_ACT",
  ACT_LAP_BIEN_BAN: "QTNVTT_CUOC_THANH_TRA_LAP_BIEN_BAN_ACT",
  ACT_CHI_TIET_XU_PHAT: "QTNVTT_CUOC_THANH_TRA_CHI_TIET_XU_PHAT_ACT",
  ACT_DOWNLOAD: "QTNVTT_CUOC_THANH_TRA_DOWNLOAD",
  ACT_NHIEM_VU: "QTNVTT_CUOC_THANH_TRA_NHIEM_VU_ACT",
  ACT_XU_PHAT_HANH_CHINH: "QTNVTT_CUOC_THANH_TRA_XU_PHAT_HANH_CHINH_ACT",

  ACT_THANH_TRA_TIENHANHTHANHTRA:
    "QTNVTT_CUOC_THANH_TRA_THANH_TRA_TIENHANHTHANHTRA_ACT",

  ACT_TRINHPHEDUYETHOSOBOSUNG:
    "QTNVTT_CUOC_THANH_TRA_TRINHPHEDUYETHOSOBOSUNG_ACT",
  ACT_PHEDUYETHOSOBOSUNG: "QTNVTT_CUOC_THANH_TRA_PHEDUYETHOSOBOSUNG_ACT",
};

export const ACT_ID_QTNVTT_CUOC_THANH_TRA_DETAIL = {
  ACT_PHE_DUYET: "QTNVTT_CUOC_THANH_TRA_DETAIL_PHE_DUYET_ACT",
  ACT_VIEW_RATING: "QTNVTT_CUOC_THANH_TRA_VIEW_RATING_ACT",
};

/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Đợt thanh tra
 */
export const ACT_ID_QTNVTT_DOT_THANH_TRA = {
  ACT_LIST: "QTNVTT_DOT_THANH_TRA_LIST_ACT",
  ACT_CREATE: "QTNVTT_DOT_THANH_TRA_CREATE_ACT",
  ACT_UPDATE: "QTNVTT_DOT_THANH_TRA_UPDATE_ACT",
  ACT_DELETE: "QTNVTT_DOT_THANH_TRA_DELETE_ACT",
  ACT_SEARCH: "QTNVTT_DOT_THANH_TRA_SEARCH_ACT",
  ACT_TRINH_PHE_DUYET: "QTNVTT_DOT_THANH_TRA_TRINH_PHE_DUYET_ACT",
  ACT_PHE_DUYET: "QTNVTT_DOT_THANH_TRA_PHE_DUYET_ACT",
  ACT_BAN_HANH: "QTNVTT_DOT_THANH_TRA_BAN_HANH_ACT",
  ACT_KET_LUAN: "QTNVTT_DOT_THANH_TRA_KET_LUAN_ACT",
  ACT_THANH_TRA: "QTNVTT_DOT_THANH_TRA_THANH_TRA_ACT",
  ACT_ATTACH_FILE: "QTNVTT_DOT_THANH_TRA_ATTACH_FILE_ACT",

  ACT_THANH_TRA_TIENHANHTHANHTRA:
    "QTNVTT_DOT_THANH_TRA_THANH_TRA_TIENHANHTHANHTRA_ACT",
  ACT_THANH_TRA_KT: "QTNVTT_DOT_THANH_TRA_THANH_TRA_KT_ACT",
  ACT_THANH_TRA_ALLOW_UPDATE: "QTNVTT_DOT_THANH_TRA_THANH_TRA_ALLOW_UPDATE_ACT",
  ACT_THANH_TRA_CHANGE_DURATION_UPDATE:
    "QTNVTT_DOT_THANH_TRA_THANH_TRA_CHANGE_DURATION_UPDATE_ACT",
  ACT_LAP_BIEN_BAN: "QTNVTT_DOT_THANH_TRA_LAP_BIEN_BAN_ACT",
  ACT_CHI_TIET_XU_PHAT: "QTNVTT_DOT_THANH_TRA_CHI_TIET_XU_PHAT_ACT",
  ACT_DOWNLOAD: "QTNVTT_DOT_THANH_TRA_DOWNLOAD",
  ACT_NHIEM_VU: "QTNVTT_DOT_THANH_TRA_NHIEM_VU_ACT",

  ACT_PHE_DUYET_BO_SUNG_CO_SO:
    "QTNVTT_DOT_THANH_TRA_PHE_DUYET_BO_SUNG_CO_SO_ACT",
};
export const ACT_ID_QTNVTT_PHE_DUYET_BO_SUNG_CO_SO = {
  ACT_PHE_DUYET: "QTNVTT_PHE_DUYET_BO_SUNG_CO_SO_PHE_DUYET_ACT",
};

export const ACT_ID_QTNVTT_DOT_THANH_TRA_DETAIL = {
  ACT_PHE_DUYET: "QTNVTT_DOT_THANH_TRA_DETAIL_PHE_DUYET_ACT",
  ACT_VIEW_RATING: "QTNVTT_DOT_THANH_TRA_VIEW_RATING_ACT",
};

/**
 *  Quản lý quy trình nghiệp vụ thanht ra
 *      Đoàn thanh tra
 */
export const ACT_ID_QTNVTT_DOAN_THANH_TRA = {
  ACT_LIST: "QTNVTT_DOAN_THANH_TRA_LIST_ACT",
  ACT_CREATE: "QTNVTT_DOAN_THANH_TRA_CREATE_ACT",
  ACT_UPDATE: "QTNVTT_DOAN_THANH_TRA_UPDATE_ACT",
  ACT_DELETE: "QTNVTT_DOAN_THANH_TRA_DELETE_ACT",
  ACT_SEARCH: "QTNVTT_DOAN_THANH_TRA_SEARCH_ACT",
  ACT_THANH_VIEN_SELECT_FROM_APP: "QTNVTT_DTT_THANH_VIEN_SELECT_FROM_APP_ACT",
  ACT_THANH_VIEN_CREATE: "QTNVTT_DTT_THANH_VIEN_CREATE_ACT",
  ACT_THANH_VIEN_UPDATE: "QTNVTT_DTT_THANH_VIEN_UPDATE_ACT",
  ACT_THANH_VIEN_DELETE: "QTNVTT_DTT_THANH_VIEN_DELETE_ACT",
  ACT_THANH_VIEN_HISTORY: "QTNVTT_DTT_THANH_VIEN_HISTORY_ACT",
};

/**
 *  Quản lý quy trình nghiệp vụ thanht ra
 *      Báo cáo thống kê
 */
export const ACT_ID_QTNVTT_BAO_CAO_THONG_KE = {
  ACT_NGHIEP_VU_ALLOW_ACCESS:
    "QTNVTT_THONG_KE_BAO_CAO_NGHIEP_VU_ALLOW_ACCESS_ACT",
  ACT_THANH_TRA_ALLOW_ACCESS:
    "QTNVTT_THONG_KE_BAO_CAO_THANH_TRA_ALLOW_ACCESS_ACT",
  ACT_ALL_ALLOW_ACCESS: "QTNVTT_THONG_KE_BAO_CAO_ALL_ALLOW_ACCESS_ACT",
  ACT_CHI_TIET_VI_PHAM: "QTNVTT_THONG_KE_BAO_CAO_CHI_TIET_VI_PHAM_ACT",
  ACT_DS_CO_SO: "QTNVTT_THONG_KE_BAO_CAO_DS_CO_SO_ACT",
};
/**
 *  END_QLQTNVTT
 */

/**
 *  START_QLQTDTXLNDTP
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Hồ sơ ngộ độc thực phẩm
 */
export const ACT_ID_HO_SO_NGO_DOC_THUC_PHAM = {
  ACT_LIST: "HO_SO_NGO_DOC_THUC_PHAM_LIST_ACT",
  ACT_CREATE: "HO_SO_NGO_DOC_THUC_PHAM_CREATE_ACT",
  ACT_UPDATE: "HO_SO_NGO_DOC_THUC_PHAM_UPDATE_ACT",
  ACT_DELETE: "HO_SO_NGO_DOC_THUC_PHAM_DELETE_ACT",
  ACT_SEARCH: "HO_SO_NGO_DOC_THUC_PHAM_SEARCH_ACT",
  ACT_DETAIL: "HO_SO_NGO_DOC_THUC_PHAM_DETAIL_ACT",
  ACT_DIEU_TRA: "HO_SO_NGO_DOC_THUC_PHAM_DIEU_TRA_ACT",
  ACT_DIEU_TRA_CHI_TIET: "HO_SO_NGO_DOC_THUC_PHAM_DIEU_TRA_CHI_TIET_ACT",
  ACT_KET_LUAN: "HO_SO_NGO_DOC_THUC_PHAM_KET_LUAN_ACT",
  ACT_CO_SO_LIEN_QUAN_SELECT_FROM_APP: "ACT_CO_SO_LIEN_QUAN_SELECT_FROM_APP",
  ACT_CO_SO_LIEN_QUAN_CREATE: "QTDT_XL_DT_CO_SO_LIEN_QUAN_CREATE",
  ACT_CO_SO_LIEN_QUAN_UPDATE: "QTDT_XL_DT_CO_SO_LIEN_QUAN_UPDATE",
  ACT_CO_SO_LIEN_QUAN_DELETE: "QTDT_XL_DT_CO_SO_LIEN_QUAN_DELETE",
  ACT_CSLQ_XU_LY_LIST: "QTDT_XL_DT_CSLQ_XU_LY_LIST_ACT",
  ACT_CSLQ_XU_LY_CREATE: "QTDT_XL_DT_CSLQ_XU_LY_CREATE_ACT",
  ACT_CSLQ_XU_LY_UPDATE: "QTDT_XL_DT_CSLQ_XU_LY_UPDATE_ACT",
  ACT_CSLQ_XU_LY_DELETE: "QTDT_XL_DT_CSLQ_XU_LY_DELETE_ACT",
};

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Điều tra ngộ độc thực phẩm
 */
export const ACT_ID_DIEU_TRA_NGO_DOC_THUC_PHAM = {
  ACT_LIST: "DIEU_TRA_NGO_DOC_THUC_PHAM_LIST_ACT",
  ACT_CREATE: "DIEU_TRA_NGO_DOC_THUC_PHAM_CREATE_ACT",
  ACT_UPDATE: "DIEU_TRA_NGO_DOC_THUC_PHAM_UPDATE_ACT",
  ACT_DELETE: "DIEU_TRA_NGO_DOC_THUC_PHAM_DELETE_ACT",
  ACT_SEARCH: "DIEU_TRA_NGO_DOC_THUC_PHAM_SEARCH_ACT",
};

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Xử lý ngộ độc thực phẩm
 */
export const ACT_ID_XU_LY_NGO_DOC_THUC_PHAM = {
  ACT_LIST: "XU_LY_NGO_DOC_THUC_PHAM_LIST_ACT",
  ACT_CREATE: "XU_LY_NGO_DOC_THUC_PHAM_CREATE_ACT",
  ACT_UPDATE: "XU_LY_NGO_DOC_THUC_PHAM_UPDATE_ACT",
  ACT_DELETE: "XU_LY_NGO_DOC_THUC_PHAM_DELETE_ACT",
  ACT_SEARCH: "XU_LY_NGO_DOC_THUC_PHAM_SEARCH_ACT",
};
/**
 *  END_QLQTDTXLNDTP
 */

/**
 *  START_QLTTTCB
 *  Quản lý thủ tục tự công bố
 *      Hồ sơ tự công bố
 */
export const ACT_ID_HO_SO_TU_CONG_BO = {
  ACT_LIST: "HO_SO_TU_CONG_BO_LIST_ACT",
  ACT_CREATE: "HO_SO_TU_CONG_BO_CREATE_ACT",
  ACT_UPDATE: "HO_SO_TU_CONG_BO_UPDATE_ACT",
  ACT_DELETE: "HO_SO_TU_CONG_BO_DELETE_ACT",
  ACT_SEARCH: "HO_SO_TU_CONG_BO_SEARCH_ACT",
  ACT_KE_HOACH_UPDATE_LIST: "HO_SO_TU_CONG_BO_KE_HOACH_UPDATE_LIST_ACT",
  ACT_EXPORT: "HO_SO_TU_CONG_BO_EXPORT_ACT",
  ACT_EXPORT_GIAY_BIEN_NHAN: "HO_SO_TU_CONG_BO_EXPORT_GIAY_BIEN_NHAN_ACT",
  ACT_DETAIL: "HO_SO_TU_CONG_BO_DETAIL_ACT",
  ACT_TRINH_PHE_DUYET: "HO_SO_TU_CONG_BO_TRINH_PHE_DUYET_ACT",
  ACT_CHUYEN_XU_LY: "HO_SO_TU_CONG_BO_CHUYEN_XU_LY_ACT",
  ACT_PHE_DUYET: "HO_SO_TU_CONG_BO_PHE_DUYET_ACT",
  ACT_YEU_CAU_BO_SUNG: "HO_SO_TU_CONG_BO_YEU_CAU_BO_SUNG_ACT",
  ACT_THONGBAOCONGBO: "HO_SO_TU_CONG_BO_THONGBAOCONGBO_ACT",
  ACT_HIDE_WEBSITE: "HO_SO_TU_CONG_BO_HIDE_WEBSITE_ACT",
  ACT_IMPORT: "HO_SO_TU_CONG_BO_IMPORT_ACT",
};

export const ACT_ID_DANH_SAN_PHAM_OCOP = {
  ACT_SEARCH: "HO_SO_TU_CONG_BO_SP_OCOP_SEARCH_ACT",
  ACT_IMPORT: "HO_SO_TU_CONG_BO_SP_OCOP_IMPORT_ACT",
  ACT_LIST: "DANH_SACH_SAN_PHAM_OCOP_LIST_ACT",
  ACT_DELETE: "DANH_SACH_SAN_PHAM_OCOP_DELETE_ACT",
};

/**
 *  Quản lý thủ tục tự công bố
 *      Danh mục
 *          Nhóm
 */
export const ACT_ID_TCB_NHOM = {
  ACT_LIST: "TCB_NHOM_LIST_ACT",
  ACT_CREATE: "TCB_NHOM_CREATE_ACT",
  ACT_UPDATE: "TCB_NHOM_UPDATE_ACT",
  ACT_DELETE: "TCB_NHOM_DELETE_ACT",
  ACT_SEARCH: "TCB_NHOM_SEARCH_ACT",
};
/**
 *  Quản lý thủ tục tự công bố
 *      Danh mục
 *          Nhóm - Phân nhóm
 */
export const ACT_ID_TCB_PHAN_NHOM = {
  ACT_LIST: "TCB_PHAN_NHOM_LIST_ACT",
  ACT_CREATE: "TCB_PHAN_NHOM_CREATE_ACT",
  ACT_UPDATE: "TCB_PHAN_NHOM_UPDATE_ACT",
  ACT_DELETE: "TCB_PHAN_NHOM_DELETE_ACT",
  ACT_SEARCH: "TCB_PHAN_NHOM_SEARCH_ACT",
};
/**
 *  Quản lý thủ tục tự công bố
 *      Thông báo công bố sản phẩm
 */
export const ACT_ID_THONG_BAO_HO_SO_TU_CONG_BO = {
  ACT_LIST: "THONG_BAO_HO_SO_TU_CONG_BO_LIST_ACT",
  ACT_CREATE: "THONG_BAO_HO_SO_TU_CONG_BO_CREATE_ACT",
  ACT_UPDATE: "THONG_BAO_HO_SO_TU_CONG_BO_UPDATE_ACT",
  ACT_DELETE: "THONG_BAO_HO_SO_TU_CONG_BO_DELETE_ACT",
  ACT_SEARCH: "THONG_BAO_HO_SO_TU_CONG_BO_SEARCH_ACT",
  ACT_EXPORT: "THONG_BAO_HO_SO_TU_CONG_BO_EXPORT_ACT",
  ACT_DETAIL: "THONG_BAO_HO_SO_TU_CONG_BO_DETAIL_ACT",
  ACT_TRINHPHEDUYET: "THONG_BAO_HO_SO_TU_CONG_BO_TRINHPHEDUYET_ACT",
  ACT_HUYTHONGBAO: "THONG_BAO_HO_SO_TU_CONG_BO_HUYTHONGBAO_ACT",
  ACT_PHEDUYET: "THONG_BAO_HO_SO_TU_CONG_BO_PHEDUYET_ACT",
  ACT_BAN_HANH: "THONG_BAO_HO_SO_TU_CONG_BO_BAN_HANH_ACT",
};

export const ACT_ID_THONG_BAO_HO_SO_TU_CONG_BO_DETAIL = {
  ACT_UPDATE_HS: "THONG_BAO_HO_SO_TU_CONG_BO_DETAIL_UPDATE_HS_ACT",
  ACT_PHEDUYET: "THONG_BAO_HO_SO_TU_CONG_BO_DETAIL_PHEDUYET_ACT",
  ACT_TRINHPHEDUYET: "THONG_BAO_HO_SO_TU_CONG_BO_DETAIL_TRINHPHEDUYET_ACT",
  ACT_HUYTHONGBAO: "THONG_BAO_HO_SO_TU_CONG_BO_DETAIL_HUYTHONGBAO_ACT",
  ACT_PHEDUYET_HS: "THONG_BAO_HO_SO_TU_CONG_BO_DETAIL_PHEDUYET_HS_ACT",
};
/**
 *  Quản lý thủ tục tự công bố
 *      Công tác hậu kiểm
 */
export const ACT_ID_CONG_TAC_HAU_KIEM = {
  ACT_LIST: "CONG_TAC_HAU_KIEM_LIST_ACT",
  ACT_CREATE: "CONG_TAC_HAU_KIEM_CREATE_ACT",
  ACT_UPDATE: "CONG_TAC_HAU_KIEM_UPDATE_ACT",
  ACT_DELETE: "CONG_TAC_HAU_KIEM_DELETE_ACT",
  ACT_SEARCH: "CONG_TAC_HAU_KIEM_SEARCH_ACT",
  ACT_HOSO_CREATE: "CONG_TAC_HAU_KIEM_HOSO_CREATE_ACT",
  ACT_HOSO_DELETE: "CONG_TAC_HAU_KIEM_HOSO_DELETE_ACT",
  ACT_HOSO_LIST: "CONG_TAC_HAU_KIEM_HOSO_LIST_ACT",
  ACT_NOTCONFIRM: "CONG_TAC_HAU_KIEM_NOTCONFIRM_ACT",
  ACT_CONFIRM: "CONG_TAC_HAU_KIEM_CONFIRM_ACT",
  ACT_PRINT: "CONG_TAC_HAU_KIEM_PRINT_ACT",
};
/**
 *  END_QLTTTCB
 */

/**
 *  START_QLCTGSONTP
 *  Quản lý công tác giám sát ô nhiễm thực phẩm
 *      Danh mục
 *          Chỉ tiêu
 */
export const ACT_ID_QLDM_CHI_TIEU = {
  ACT_LIST: "QLCTGSON_DM_CHI_TIEU_LIST_ACT",
  ACT_CREATE: "QLCTGSON_DM_CHI_TIEU_CREATE_ACT",
  ACT_UPDATE: "QLCTGSON_DM_CHI_TIEU_UPDATE_ACT",
  ACT_DELETE: "QLCTGSON_DM_CHI_TIEU_DELETE_ACT",
  ACT_SEARCH: "QLCTGSON_DM_CHI_TIEU_SEARCH_ACT",
};

/**
 *  Quản lý công tác giám sát ô nhiễm thực phẩm
 *      Danh mục
 *          Loại thực phẩm
 */
export const ACT_ID_QLDM_LOAI_THUC_PHAM = {
  ACT_LIST: "QLCTGSON_DM_LOAI_THUC_PHAM_LIST_ACT",
  ACT_CREATE: "QLCTGSON_DM_LOAI_THUC_PHAM_CREATE_ACT",
  ACT_UPDATE: "QLCTGSON_DM_LOAI_THUC_PHAM_UPDATE_ACT",
  ACT_DELETE: "QLCTGSON_DM_LOAI_THUC_PHAM_DELETE_ACT",
  ACT_SEARCH: "QLCTGSON_DM_LOAI_THUC_PHAM_SEARCH_ACT",
};

/**
 *  Quản lý công tác giám sát ô nhiễm thực phẩm
 *      Đợt kiểm tra
 */
export const ACT_ID_DOT_KIEM_TRA = {
  ACT_LIST: "QLCTGSON_DOT_KIEM_TRA_LIST_ACT",
  ACT_CREATE: "QLCTGSON_DOT_KIEM_TRA_CREATE_ACT",
  ACT_UPDATE: "QLCTGSON_DOT_KIEM_TRA_UPDATE_ACT",
  ACT_DELETE: "QLCTGSON_DOT_KIEM_TRA_DELETE_ACT",
  ACT_SEARCH: "QLCTGSON_DOT_KIEM_TRA_SEARCH_ACT",
  ACT_CHI_TIET_MAU: "QLCTGSON_DOT_KIEM_TRA_CHI_TIET_MAU_ACT",
  ACT_CHI_TIEU_GIAM_SAT_CREATE: "QLCTGSON_DKT_CHI_TIEU_GIAM_SAT_CREATE_ACT",
  ACT_CHI_TIEU_GIAM_SAT_UPDATE: "QLCTGSON_DKT_CHI_TIEU_GIAM_SAT_UPDATE_ACT",
  ACT_CHI_TIEU_GIAM_SAT_DELETE: "QLCTGSON_DKT_CHI_TIEU_GIAM_SAT_DELETE_ACT",
};

/**
 *  Quản lý công tác giám sát ô nhiễm thực phẩm
 *      Thành lập đoàn kiểm tra - giám sát
 */
export const ACT_ID_THANH_LAP_DOAN_KIEM_TRA = {
  ACT_LIST: "THANH_LAP_DOAN_KIEM_TRA_LIST_ACT",
  ACT_CREATE: "THANH_LAP_DOAN_KIEM_TRA_CREATE_ACT",
  ACT_UPDATE: "THANH_LAP_DOAN_KIEM_TRA_UPDATE_ACT",
  ACT_DELETE: "THANH_LAP_DOAN_KIEM_TRA_DELETE_ACT",
  ACT_SEARCH: "THANH_LAP_DOAN_KIEM_TRA_SEARCH_ACT",
  ACT_TRINH_PHE_DUYET: "THANH_LAP_DOAN_KIEM_TRA_TRINH_PHE_DUYET_ACT",
  ACT_PHE_DUYET: "THANH_LAP_DOAN_KIEM_TRA_PHE_DUYET_ACT",
  ACT_TRINHPHEDUYETHOSOBOSUNG:
    "THANH_LAP_DOAN_KIEM_TRA_ACT_TRINHPHEDUYETHOSOBOSUNG",
  ACT_PHEDUYETHOSOBOSUNG: "THANH_LAP_DOAN_KIEM_TRA_ACT_PHEDUYETHOSOBOSUNG",
  ACT_BAN_HANH_QDTLDGS: "THANH_LAP_DOAN_KIEM_TRA_BAN_HANH",
};

export const ACT_ID_THANH_LAP_DOAN_KIEM_TRA_DETAIL = {
  ACT_PHE_DUYET: "THANH_LAP_DOAN_KIEM_TRA_DETAIL_DETAIL_PHE_DUYET_ACT",
  ACT_VIEW_RATING: "THANH_LAP_DOAN_KIEM_TRA_DETAIL_VIEW_RATING_ACT",
};
/**
 *  END_QLCTGSONTP
 */

/**
 *  START_QLTNVXLPAKN
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Hồ sơ phản ánh kiến nghị
 */
export const ACT_ID_PAKN_HO_SO = {
  ACT_LIST: "PAKN_HO_SO_LIST_ACT",
  ACT_CREATE: "PAKN_HO_SO_CREATE_ACT",
  ACT_UPDATE: "PAKN_HO_SO_UPDATE_ACT",
  ACT_DELETE: "PAKN_HO_SO_DELETE_ACT",
  ACT_SEARCH: "PAKN_HO_SO_SEARCH_ACT",
  ACT_BIEN_BAN_THANH_TRA: "PAKN_HO_SO_BIEN_BAN_THANH_TRA_ACT",
  ACT_BIEN_BAN_XU_PHAT: "PAKN_HO_SO_BIEN_BAN_XU_PHAT_ACT",
  PHAN_ANH_UPDATE_ACT: "PHAN_ANH_UPDATE_ACT",
  ACT_XU_LY: "PAKN_HO_SO_XU_LY_ACT",
};

export const ACT_ID_PAKN_HO_SO_TIEP_NHAN = {
    ACT_LIST: "PAKN_HO_SO_TIEP_NHAN_LIST_ACT",
    ACT_CREATE: "PAKN_HO_SO_TIEP_NHAN_CREATE_ACT",
    ACT_UPDATE: "PAKN_HO_SO_TIEP_NHAN_UPDATE_ACT",
    ACT_DELETE: "PAKN_HO_SO_TIEP_NHAN_DELETE_ACT",
    ACT_SEARCH: "PAKN_HO_SO_TIEP_NHAN_SEARCH_ACT",
    ACT_BIEN_BAN_THANH_TRA: "PAKN_HO_SO_BIEN_BAN_THANH_TRA_ACT",
    ACT_BIEN_BAN_XU_PHAT: "PAKN_HO_SO_BIEN_BAN_XU_PHAT_ACT",
    PHAN_ANH_UPDATE_ACT: "PHAN_ANH_UPDATE_ACT",
    ACT_XU_LY: "PAKN_HO_SO_XU_LY_ACT",
    ACT_TRINH_PHE_DUYET: "PAKN_HO_SO_TRINH_PHE_DUYET_ACT"
}

export const ACT_ID_PAKN_HO_SO_DANG_XU_LY = {
    ACT_LIST: "PAKN_HO_SO_DANG_XU_LY_LIST_ACT",
    ACT_CREATE: "PAKN_HO_SO_CREATE_ACT",
    ACT_UPDATE: "PAKN_HO_SO_UPDATE_ACT",
    ACT_DELETE: "PAKN_HO_SO_DELETE_ACT",
    ACT_SEARCH: "PAKN_HO_SO_DANG_XU_LY_SEARCH_ACT",
    ACT_BIEN_BAN_THANH_TRA: "PAKN_HO_SO_DANG_XU_LY_BIEN_BAN_THANH_TRA_ACT",
    ACT_BIEN_BAN_XU_PHAT: "PAKN_HO_SO_BIEN_BAN_XU_PHAT_ACT",
    PHAN_ANH_UPDATE_ACT: "PHAN_ANH_UPDATE_ACT",
    ACT_XU_LY: "PAKN_HO_SO_DANG_XU_LY_ACT",
    ACT_PHE_DUYET: "PAKN_HO_SO_PHE_DUYET_ACT",
    ACT_CHUYEN_XU_LY: "PAKN_HO_SO_CHUYEN_XU_LY_ACT"
}

/**
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Biên bản thanh tra
 */
export const ACT_ID_PAKN_BIEN_BAN_THANH_TRA = {
  ACT_LIST: "PAKN_BIEN_BAN_THANH_TRA_LIST_ACT",
  ACT_CREATE: "PAKN_BIEN_BAN_THANH_TRA_CREATE_ACT",
  ACT_UPDATE: "PAKN_BIEN_BAN_THANH_TRA_UPDATE_ACT",
  ACT_DELETE: "PAKN_BIEN_BAN_THANH_TRA_DELETE_ACT",
  ACT_SEARCH: "PAKN_BIEN_BAN_THANH_TRA_SEARCH_ACT",
};

/**
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Biên bản xử phạt
 */
export const ACT_ID_PAKN_BIEN_BAN_XU_PHAT = {
  ACT_LIST: "PAKN_BIEN_BAN_XU_PHAT_LIST_ACT",
  ACT_CREATE: "PAKN_BIEN_BAN_XU_PHAT_CREATE_ACT",
  ACT_UPDATE: "PAKN_BIEN_BAN_XU_PHAT_UPDATE_ACT",
  ACT_DELETE: "PAKN_BIEN_BAN_XU_PHAT_DELETE_ACT",
  ACT_SEARCH: "PAKN_BIEN_BAN_XU_PHAT_SEARCH_ACT",
};
/**
 *  END_QLTNVXLPAKN
 */

/**
 *  START_QLTDHSCGCNATTP
 *  Quản lý thẩm định hồ sơ cấp giấy chứng nhận an toàn thực phẩm
 *      Hồ sơ cấp giấy chứng nhận
 */
export const ACT_ID_HO_SO_CAP_GIAY_CHUNG_NHAN = {
  ACT_LIST: "HO_SO_CAP_GIAY_CHUNG_NHAN_LIST_ACT",
  ACT_CREATE: "HO_SO_CAP_GIAY_CHUNG_NHAN_CREATE_ACT",
  ACT_UPDATE: "HO_SO_CAP_GIAY_CHUNG_NHAN_UPDATE_ACT",
  ACT_DELETE: "HO_SO_CAP_GIAY_CHUNG_NHAN_DELETE_ACT",
  ACT_SEARCH: "HO_SO_CAP_GIAY_CHUNG_NHAN_SEARCH_ACT",
  ACT_EXPORT: "HO_SO_CAP_GIAY_CHUNG_NHAN_EXPORT_ACT",
  ACT_REPORT: "HO_SO_CAP_GIAY_CHUNG_NHAN_REPORT_ACT",
  ACT_KE_HOACH_UPDATE_LIST:
    "HO_SO_CAP_GIAY_CHUNG_NHAN_KE_HOACH_UPDATE_LIST_ACT",
  ACT_DONG_BO_HO_SO: "HO_SO_CAP_GIAY_CHUNG_NHAN_KE_HOACH_DONG_BO_HO_SO_ACT",
  ACT_DETAIL: "HO_SO_CAP_GIAY_CHUNG_NHAN_DETAIL_ACT",
};

export const ACT_ID_HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY = {
  ACT_LIST: "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_LIST_ACT",
  ACT_CREATE: "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_CREATE_ACT",
  ACT_UPDATE: "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_UPDATE_ACT",
  ACT_SEARCH: "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_SEARCH_ACT",
  ACT_EXPORT: "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_EXPORT_ACT",
  ACT_REPORT: "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_REPORT_ACT",
  ACT_DONG_BO_HO_SO:
    "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_KE_HOACH_DONG_BO_HO_SO_ACT",
  ACT_DETAIL: "HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_KE_HOACH_DETAIL_ACT",
};

/**
 *  START_QLTDHSCGCNATTP
 *  Quản lý thẩm định hồ sơ cấp giấy chứng nhận an toàn thực phẩm
 *      Kế hoạch thẩm định
 */
export const ACT_ID_KE_HOACH_THAM_DINH = {
  ACT_LIST: "KE_HOACH_THAM_DINH_LIST_ACT",
  ACT_CREATE: "KE_HOACH_THAM_DINH_CREATE_ACT",
  ACT_HOSO_CREATE: "HO_SO_THAM_DINH_CREATE_ACT",
  ACT_HOSO_DELETE: "HO_SO_THAM_DINH_DELETE_ACT",
  ACT_UPDATE: "KE_HOACH_THAM_DINH_UPDATE_ACT",
  ACT_DELETE: "KE_HOACH_THAM_DINH_DELETE_ACT",
  ACT_SEARCH: "KE_HOACH_THAM_DINH_SEARCH_ACT",
  ACT_EXPORT: "KE_HOACH_THAM_DINH_EXPORT_ACT",
  ACT_REPORT: "KE_HOACH_THAM_DINH_REPORT_ACT",
  ACT_HOSO_LIST: "KE_HOACH_THAM_DINH_HOSO_LIST_ACT",

  ACT_THAM_DINH: "KE_HOACH_THAM_DINH_THAM_DINH_ACT",
  ACT_TRINH_PHE_DUYET: "KE_HOACH_THAM_DINH_HOSO_TRINHPHEDUYET_ACT",
  ACT_PHE_DUYET: "KE_HOACH_THAM_DINH_HOSO_PHE_DUYET_ACT",
  ACT_BAN_HANH: "KE_HOACH_THAM_DINH_HOSO_BAN_HANH_ACT",
  ACT_VIEW_BAN_HANH: "KE_HOACH_THAM_DINH_HOSO_VIEW_BAN_HANH_ACT",

  ACT_DETAIL: "KE_HOACH_THAM_DINH_DETAIL_ACT",

  ACT_HSTD_TD: "KE_HOACH_THAM_DINH_HSTD_TD_ACT",
  ACT_HSTD_DEL: "KE_HOACH_THAM_DINH_HSTD_DEL_ACT",
  ACT_HSTD_UPDATE: "KE_HOACH_THAM_DINH_HSTD_UPDATE_ACT",

  ACT_LAP_DTD: "KE_HOACH_THAM_DINH_LAP_DTD_ACT",
  ACT_KET_THUC: "KE_HOACH_THAM_DINH_KET_THUC_THAM_DINH_ACT",

  ACT_EXPORT_LIST_HO_SO: "KE_HOACH_THAM_DINH_EXPORT_LIST_HO_SO_ACT",
};

export const ACT_ID_HO_SO_CAP_GIAY_CHUNG_NHAN_CHI_TIET_KE_HOACH = {
  ACT_UPDATE_HO_SO: "KE_HOACH_THAM_DINH_HOSO_DETAIL_UPDATE_HOSO_ACT",
  ACT_TRINH_PHE_DUYET: "KE_HOACH_THAM_DINH_HOSO_DETAIL_TRINHPHEDUYET_ACT",
  ACT_PHE_DUYET: "KE_HOACH_THAM_DINH_HOSO_DETAIL_PHE_DUYET_ACT",
  ACT_YEU_CAU_BO_SUNG: "KE_HOACH_THAM_DINH_HOSO_DETAIL_YEUCAUBOSUNG_ACT",
};
/**
 *  END_QLTDHSCGCNATTP
 */

/**
 *  START_QLXNQC
 *  Quản lý xác nhận quảng cáo
 *      Hồ sơ xác nhận quảng cáo
 */
export const ACT_ID_XAC_NHAN_QUANG_CAO = {
  ACT_LIST: "XAC_NHAN_QUANG_CAO_LIST_ACT",
  ACT_CREATE: "XAC_NHAN_QUANG_CAO_CREATE_ACT",
  ACT_UPDATE: "XAC_NHAN_QUANG_CAO_UPDATE_ACT",
  ACT_DELETE: "XAC_NHAN_QUANG_CAO_DELETE_ACT",
  ACT_SEARCH: "XAC_NHAN_QUANG_CAO_SEARCH_ACT",
  ACT_SAN_PHAM_QUANG_CAO_CREATE: "XNQC_SAN_PHAM_QUANG_CAO_CREATE_ACT",
  ACT_SAN_PHAM_QUANG_CAO_UPDATE: "XNQC_SAN_PHAM_QUANG_CAO_UPDATE_ACT",
  ACT_SAN_PHAM_QUANG_CAO_DELETE: "XNQC_SAN_PHAM_QUANG_CAO_DELETE_ACT",
};
/**
 *  END_QLXNQC
 */

/**
 * START_QLCTPAT
 * Quản lý chuỗi thực phẩm an toàn
 *      Nhóm chuỗi thực phẩm
 */
export const ACT_ID_NHOM_CHUOI_THUC_PHAM = {
  ACT_LIST: "NHOM_CHUOI_THUC_PHAM_LIST_ACT",
  ACT_CREATE: "NHOM_CHUOI_THUC_PHAM_CREATE_ACT",
  ACT_UPDATE: "NHOM_CHUOI_THUC_PHAM_UPDATE_ACT",
  ACT_DELETE: "NHOM_CHUOI_THUC_PHAM_DELETE_ACT",
  ACT_SEARCH: "NHOM_CHUOI_THUC_PHAM_SEARCH_ACT",
};

/**
 *  Quản lý chuỗi thực phẩm an toàn
 *      Hồ sơ chuỗi thực phẩm
 */
export const ACT_ID_HO_SO_CHUOI_THUC_PHAM = {
  ACT_LIST: "HO_SO_CHUOI_THUC_PHAM_LIST_ACT",
  ACT_CREATE: "HO_SO_CHUOI_THUC_PHAM_CREATE_ACT",
  ACT_UPDATE: "HO_SO_CHUOI_THUC_PHAM_UPDATE_ACT",
  ACT_DELETE: "HO_SO_CHUOI_THUC_PHAM_DELETE_ACT",
  ACT_LIST_CO_SO: "HO_SO_CHUOI_THUC_PHAM_LIST_CO_SO_ACT",
  ACT_SEARCH: "HO_SO_CHUOI_THUC_PHAM_SEARCH_ACT",
  ACT_EXPORT: "HO_SO_CHUOI_THUC_PHAM_EXPORT_ACT",
  ACT_REPORT: "HO_SO_CHUOI_THUC_PHAM_REPORT_ACT",
  ACT_CAP_SO_GXN: "HO_SO_CHUOI_THUC_PHAM_ACT_CAP_SO_GXN_ACT",
  ACT_KE_HOACH_UPDATE_LIST: "HO_SO_CHUOI_THUC_PHAM_KE_HOACH_UPDATE_LIST_ACT",
  ACT_THANH_VIEN_CTP_SELECT_FROM_APP:
    "HO_SO_CTP_THANH_VIEN_SELECT_FROM_APP_ACT",
  ACT_THANH_VIEN_CTP_CREATE: "HO_SO_CTP_THANH_VIEN_CREATE_ACT",
  ACT_THANH_VIEN_CTP_UPDATE: "HO_SO_CTP_THANH_VIEN_UPDATE_ACT",
  ACT_THANH_VIEN_CTP_DELETE: "HO_SO_CTP_THANH_VIEN_DELETE_ACT",
};

/**
 *  Quản lý chuỗi thực phẩm an toàn
 *      Kế hoạch thẩm định
 */
export const ACT_ID_KE_HOACH_THAM_DINH_CTP = {
  ACT_LIST: "KE_HOACH_THAM_DINH_CTP_LIST_ACT",
  ACT_CREATE: "KE_HOACH_THAM_DINH_CTP_CREATE_ACT",
  ACT_UPDATE: "KE_HOACH_THAM_DINH_CTP_UPDATE_ACT",
  ACT_DELETE: "KE_HOACH_THAM_DINH_CTP_DELETE_ACT",
  ACT_SEARCH: "KE_HOACH_THAM_DINH_CTP_SEARCH_ACT",

  ACT_EXPORT: "KE_HOACH_THAM_DINH_CTP_EXPORT_ACT",
  ACT_REPORT: "KE_HOACH_THAM_DINH_CTP_REPORT_ACT",

  ACT_CAP_GCN: "KE_HOACH_THAM_DINH_CTP_CAP_GCN_ACT",
  ACT_HOSO_LIST: "KE_HOACH_THAM_DINH_CTP_HOSO_LIST_ACT",
  ACT_HOSO_CREATE: "KE_HOACH_THAM_DINH_CTP_HOSO_CREATE_ACT",
  ACT_HOSO_DELETE: "KE_HOACH_THAM_DINH_CTP_HOSO_DELETE_ACT",

  ACT_THAM_DINH: "KE_HOACH_THAM_DINH_CTP_THAM_DINH_ACT",

  ACT_TRINH_PHE_DUYET: "KE_HOACH_THAM_DINH_CTP_TRINH_PHE_DUYET_ACT",
  ACT_PHE_DUYET: "KE_HOACH_THAM_DINH_CTP_PHE_DUYET_ACT",
  ACT_BAN_HANH: "KE_HOACH_THAM_DINH_CTP_BAN_HANH_ACT",

  ACT_DETAIL: "KE_HOACH_THAM_DINH_CTP_DETAIL_ACT",
};
/**
 *  END_QLCTPAT
 */

/**
 * START_QLCTXNKTATTP
 * Quản lý xác nhận kiến thức an toàn thực phẩm
 *      Hồ sơ xác nhận kiến thức attp
 */
export const ACT_ID_HO_SO_XAC_NHAN_KTATTP = {
  ACT_LIST: "HO_SO_XAC_NHAN_KTATTP_LIST_ACT",
  ACT_CREATE: "HO_SO_XAC_NHAN_KTATTP_CREATE_ACT",
  ACT_UPDATE: "HO_SO_XAC_NHAN_KTATTP_UPDATE_ACT",
  ACT_DELETE: "HO_SO_XAC_NHAN_KTATTP_DELETE_ACT",
  ACT_SEARCH: "HO_SO_XAC_NHAN_KTATTP_SEARCH_ACT",
  ACT_CREATE_HO_SO: "HO_SO_XAC_NHAN_KTATTP_CREATE_HO_SO_ACT",
};
/**
 * Quản lý xác nhận kiến thức an toàn thực phẩm
 *      Đợt xác nhận kiến thức attp
 */
export const ACT_ID_DOT_XAC_NHAN_KTATTP = {
  ACT_LIST: "DOT_XAC_NHAN_KTATTP_LIST_ACT",
  ACT_CREATE: "DOT_XAC_NHAN_KTATTP_CREATE_ACT",
  ACT_UPDATE: "DOT_XAC_NHAN_KTATTP_UPDATE_ACT",
  ACT_DELETE: "DOT_XAC_NHAN_KTATTP_DELETE_ACT",
  ACT_PHEDUYET: "DOT_XAC_NHAN_KTATTP_PHEDUYET_ACT",
  ACT_KHONGPHEDUYET: "DOT_XAC_NHAN_KTATTP_KHONGPHEDUYET_ACT",
  ACT_SEARCH: "DOT_XAC_NHAN_KTATTP_SEARCH_ACT",
  ACT_DS_HO_SO: "DOT_XAC_NHAN_KTATTP_DS_HO_SO_ACT",
  ACT_CAP_SO: "DOT_XAC_NHAN_KTATTP_CAP_SO_ACT",
  ACT_UPDATE_LIST_HO_SO: "DOT_XAC_NHAN_KTATTP_UPDATE_LIST_HO_SO_ACT",
  ACT_UPDATE_HO_SO: "DOT_XAC_NHAN_KTATTP_UPDATE_HO_SO_ACT",
  ACT_DELETE_HO_SO: "DOT_XAC_NHAN_KTATTP_DELETE_HO_SO_ACT",
  ACT_DANH_GIA_HO_SO: "DOT_XAC_NHAN_KTATTP_DANH_GIA_HO_SO_ACT",
};
/**
 *  END_QLCTXNKTATTP
 */
/**
 *  START_BCTH
 *  Báo cáo tổng hợp
 */
export const ACT_ID_BAO_CAO_TONG_HOP = {
  ACT_LIST: "BAO_CAO_TONG_HOP_LIST_ACT",
  ACT_CREATE: "BAO_CAO_TONG_HOP_CREATE_ACT",
  ACT_UPDATE: "BAO_CAO_TONG_HOP_UPDATE_ACT",
  ACT_DELETE: "BAO_CAO_TONG_HOP_DELETE_ACT",
  ACT_SEARCH: "BAO_CAO_TONG_HOP_SEARCH_ACT",
  ACT_EXPORT: "BAO_CAO_TONG_HOP_EXPORT_ACT",
};
/**
 *  END_BCTH
 */

/**
 *  START QLBM
 *  Quản lý biểu mẫu
 */
export const ACT_ID_QUAN_LY_BIEU_MAU = {
  ACT_LIST: "QUAN_LY_BIEU_MAU_LIST_ACT",
  ACT_CREATE: "QUAN_LY_BIEU_MAU_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_BIEU_MAU_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_BIEU_MAU_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_BIEU_MAU_SEARCH_ACT",
  ACT_EXPORT: "QUAN_LY_BIEU_MAU_EXPORT_ACT",
};
/**
 *  END QLBM
 */

/**
 *  START QLKHTC
 *  Quản lý kế hoạch tài chính
 */
export const ACT_ID_QUAN_LY_KE_HOACH_TAI_CHINH = {
  ACT_LIST: "QUAN_LY_KE_HOACH_TAI_CHINH_LIST_ACT",
  ACT_CREATE: "QUAN_LY_KE_HOACH_TAI_CHINH_CREATE_ACT",
  ACT_RECREATE: "QUAN_LY_KE_HOACH_TAI_CHINH_RECREATE_ACT",
  ACT_UPDATE: "QUAN_LY_KE_HOACH_TAI_CHINH_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_KE_HOACH_TAI_CHINH_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_KE_HOACH_TAI_CHINH_SEARCH_ACT",
  ACT_EXPORT: "QUAN_LY_KE_HOACH_TAI_CHINH_EXPORT_ACT",
  ACT_CHUYEN_XU_LY: "QUAN_LY_KE_HOACH_TAI_CHINH_CHUYEN_XU_LY_ACT",
  ACT_YEU_CAU_BO_SUNG: "QUAN_LY_KE_HOACH_TAI_CHINH_YEU_CAU_BO_SUNG_ACT",
  ACT_TRINH_PHE_DUYET: "QUAN_LY_KE_HOACH_TAI_CHINH_TRINH_PHE_DUYET_ACT",
  ACT_PHE_DUYET: "QUAN_LY_KE_HOACH_TAI_CHINH_PHE_DUYET_ACT",
  ACT_BAN_HANH: "QUAN_LY_KE_HOACH_TAI_CHINH_BAN_HANH_ACT",
  ACT_VIEW_BAN_HANH: "QUAN_LY_KE_HOACH_TAI_CHINH_VIEW_BAN_HANH_ACT",
};
/**
 *  END QLKHTC
 */

/**
 *  Quản lý Kết quả thanh kiểm tra attp
 *
 */
export const ACT_ID_KET_QUA_THANH_KIEM_TRA_ATTP = {
  ACT_LIST: "KET_QUA_THANH_KIEM_TRA_ATTP_LIST_ACT",
  ACT_CREATE: "KET_QUA_THANH_KIEM_TRA_ATTP_CREATE_ACT",
  ACT_UPDATE: "KET_QUA_THANH_KIEM_TRA_ATTP_UPDATE_ACT",
  ACT_DELETE: "KET_QUA_THANH_KIEM_TRA_ATTP_DELETE_ACT",
  ACT_SEARCH: "KET_QUA_THANH_KIEM_TRA_ATTP_SEARCH_ACT",
};
/**
 *  END QLCSPL
 */

/**
 *  Quản lý đầu tư ATTP_DIA_PHUONG
 *
 */
export const ACT_ID_QUAN_LY_DAU_TU_ATTP_DIA_PHUONG = {
  ACT_LIST: "QUAN_LY_DAU_TU_ATTP_DIA_PHUONG_LIST_ACT",
  ACT_CREATE: "QUAN_LY_DAU_TU_ATTP_DIA_PHUONG_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_DAU_TU_ATTP_DIA_PHUONG_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_DAU_TU_ATTP_DIA_PHUONG_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_DAU_TU_ATTP_DIA_PHUONG_SEARCH_ACT",
  ACT_ATTACH_FILE: "QUAN_LY_DAU_TU_ATTP_DIA_PHUONG_ATTACH_FILE_ACT",
};
/**
 *  END Quản lý đầu tư ATTP_DIA_PHUONG
 */

/**
 *  Kết quả kiểm nghiệm tp
 *
 */
export const ACT_ID_KET_QUA_KIEM_NGHIEM_TP = {
  ACT_LIST: "KET_QUA_KIEM_NGHIEM_LIST_ACT",
  ACT_CREATE: "KET_QUA_KIEM_NGHIEM_CREATE_ACT",
  ACT_UPDATE: "KET_QUA_KIEM_NGHIEM_UPDATE_ACT",
  ACT_DELETE: "KET_QUA_KIEM_NGHIEM_DELETE_ACT",
  ACT_SEARCH: "KET_QUA_KIEM_NGHIEM_SEARCH_ACT",
};
/**
 *  END Kết quả kiểm nghiệm tp
 */

/**
 *  GOS nhiễm thực phẩm nông nghiệp
 *
 */
export const ACT_ID_GOS_NHIEM_TPNN = {
  ACT_LIST: "GOS_NHIEM_TPNN_LIST_ACT",
  ACT_CREATE: "GOS_NHIEM_TPNN_CREATE_ACT",
  ACT_UPDATE: "GOS_NHIEM_TPNN_UPDATE_ACT",
  ACT_DELETE: "GOS_NHIEM_TPNN_DELETE_ACT",
  ACT_SEARCH: "GOS_NHIEM_TPNN_SEARCH_ACT",
};
/**
 *  END GOS nhiễm thực phẩm nông nghiệp
 */

/**
 *  GOS nhiễm thực phẩm Y TẾ
 *
 */
export const ACT_ID_GOS_NHIEM_TPYT = {
  ACT_LIST: "GOS_NHIEM_TPYT_LIST_ACT",
  ACT_CREATE: "GOS_NHIEM_TPYT_CREATE_ACT",
  ACT_UPDATE: "GOS_NHIEM_TPYT_UPDATE_ACT",
  ACT_DELETE: "GOS_NHIEM_TPYT_DELETE_ACT",
  ACT_SEARCH: "GOS_NHIEM_TPYT_SEARCH_ACT",
};
/**
 *  END GOS nhiễm thực phẩm Y TẾ
 */

/**
 *  Kết quả thực hiện TTHC
 *
 */
export const ACT_ID_KET_QUA_THUC_HIEN_TTHC = {
  ACT_LIST: "KET_QUA_THUC_HIEN_TTHC_LIST_ACT",
  ACT_CREATE: "KET_QUA_THUC_HIEN_TTHC_CREATE_ACT",
  ACT_UPDATE: "KET_QUA_THUC_HIEN_TTHC_UPDATE_ACT",
  ACT_DELETE: "KET_QUA_THUC_HIEN_TTHC_DELETE_ACT",
  ACT_SEARCH: "KET_QUA_THUC_HIEN_TTHC_SEARCH_ACT",
};
/**
 *  END Kết quả thực hiện TTHC
 */

/**
 *  Quản lý chợ siêu thị
 *
 */
export const ACT_ID_QUAN_LY_CHO_SIEU_THI = {
  ACT_LIST: "QUAN_LY_CHO_SIEU_THI_LIST_ACT",
  ACT_CREATE: "QUAN_LY_CHO_SIEU_THI_CREATE_ACT",
  ACT_UPDATE: "QUAN_LY_CHO_SIEU_THI_UPDATE_ACT",
  ACT_DELETE: "QUAN_LY_CHO_SIEU_THI_DELETE_ACT",
  ACT_SEARCH: "QUAN_LY_CHO_SIEU_THI_SEARCH_ACT",
};
/**
 *  END Quản lý chợ siêu thị
 */

/**
 *  Sử dụng kinh phí địa phương
 *
 */
export const ACT_ID_SU_DUNG_KINH_PHI_DIA_PHUONG = {
  ACT_LIST: "SU_DUNG_KINH_PHI_DIA_PHUONG_LIST_ACT",
  ACT_CREATE: "SU_DUNG_KINH_PHI_DIA_PHUONG_CREATE_ACT",
  ACT_UPDATE: "SU_DUNG_KINH_PHI_DIA_PHUONG_UPDATE_ACT",
  ACT_DELETE: "SU_DUNG_KINH_PHI_DIA_PHUONG_DELETE_ACT",
  ACT_SEARCH: "SU_DUNG_KINH_PHI_DIA_PHUONG_SEARCH_ACT",
};
/**
 *  END Sử dụng kinh phí địa phương
 */

/**
 *  Sử dụng kinh phí trung ương
 *
 */
export const ACT_ID_SU_DUNG_KINH_PHI_TW = {
  ACT_LIST: "SU_DUNG_KINH_PHI_TW_LIST_ACT",
  ACT_CREATE: "SU_DUNG_KINH_PHI_TW_CREATE_ACT",
  ACT_UPDATE: "SU_DUNG_KINH_PHI_TW_UPDATE_ACT",
  ACT_DELETE: "SU_DUNG_KINH_PHI_TW_DELETE_ACT",
  ACT_SEARCH: "SU_DUNG_KINH_PHI_TW_SEARCH_ACT",
};
/**
 *  END Sử dụng kinh phí trung ương
 */

/**
 *  Tổng hợp tình hình vi phạm attp
 *
 */
export const ACT_ID_TONG_HOP_TINH_HINH_VTATTP = {
  ACT_LIST: "TONG_HOP_TINH_HINH_VTATTP_LIST_ACT",
  ACT_CREATE: "TONG_HOP_TINH_HINH_VTATTP_CREATE_ACT",
  ACT_UPDATE: "TONG_HOP_TINH_HINH_VTATTP_UPDATE_ACT",
  ACT_DELETE: "TONG_HOP_TINH_HINH_VTATTP_DELETE_ACT",
  ACT_SEARCH: "TONG_HOP_TINH_HINH_VTATTP_SEARCH_ACT",
};
/**
 *  END Tổng hợp tình hình vi phạm attp
 */

/**
 *  Xây dựng cơ sở vật chất địa phương
 *
 */
export const ACT_ID_XAY_DUNG_CO_SO_VAT_CHAT_DIA_PHUONG = {
  ACT_LIST: "XAY_DUNG_CO_SO_VAT_CHAT_DIA_PHUONG_LIST_ACT",
  ACT_CREATE: "XAY_DUNG_CO_SO_VAT_CHAT_DIA_PHUONG_CREATE_ACT",
  ACT_UPDATE: "XAY_DUNG_CO_SO_VAT_CHAT_DIA_PHUONG_UPDATE_ACT",
  ACT_DELETE: "XAY_DUNG_CO_SO_VAT_CHAT_DIA_PHUONG_DELETE_ACT",
  ACT_SEARCH: "XAY_DUNG_CO_SO_VAT_CHAT_DIA_PHUONG_SEARCH_ACT",
};
/**
 *  END Xây dựng cơ sở vật chất địa phương
 */

/**
 *  Mẫu kiểm nghiêm
 *
 */
export const ACT_ID_MAU_KIEM_NGHIEM = {
  ACT_LIST: "MAU_KIEM_NGHIEM_LIST_ACT",
  ACT_CREATE: "MAU_KIEM_NGHIEM_CREATE_ACT",
  ACT_UPDATE: "MAU_KIEM_NGHIEM_UPDATE_ACT",
  ACT_DELETE: "MAU_KIEM_NGHIEM_DELETE_ACT",
  ACT_SEARCH: "MAU_KIEM_NGHIEM_SEARCH_ACT",
};
/**
 *  END Mẫu kiểm nghiêm
 */

/**
 *  Mẫu thực phẩm nông nghiệp
 *
 */
export const ACT_ID_MAU_THUC_PHAM_NONG_NGHIEP = {
  ACT_LIST: "MAU_THUC_PHAM_NONG_NGHIEP_LIST_ACT",
  ACT_CREATE: "MAU_THUC_PHAM_NONG_NGHIEP_CREATE_ACT",
  ACT_UPDATE: "MAU_THUC_PHAM_NONG_NGHIEP_UPDATE_ACT",
  ACT_DELETE: "MAU_THUC_PHAM_NONG_NGHIEP_DELETE_ACT",
  ACT_SEARCH: "MAU_THUC_PHAM_NONG_NGHIEP_SEARCH_ACT",
};
/**
 *  END Mẫu thực phẩm nông nghiệp
 */

/**
 *  Truyền thông
 *
 */
export const ACT_ID_TRUYEN_THONG = {
  ACT_LIST: "TRUYEN_THONG_LIST_ACT",
  ACT_CREATE: "TRUYEN_THONG_CREATE_ACT",
  ACT_UPDATE: "TRUYEN_THONG_UPDATE_ACT",
  ACT_DELETE: "TRUYEN_THONG_DELETE_ACT",
  ACT_SEARCH: "TRUYEN_THONG_SEARCH_ACT",
};
/**
 *  END Truyền thông
 *
 */

/**
 *  START_QLKHTC
 *  Quản lý kế hoạch tài chính
 *      Phòng ban
 */
export const ACT_ID_QTKHTC = {
  ACT_ALLOW_THANH_TRA: "QLKHTC_ALLOW_THANH_TRA",
  ACT_ALLOW_NGHIEP_VU: "QLKHTC_ALLOW_NGHIEP_VU",
  ACT_ALLOW_VAN_PHONG: "QLKHTC_ALLOW_VAN_PHONG",
  ACT_ALLOW_DOI1: "QLKHTC_ALLOW_DOI1",
  ACT_ALLOW_DOI2: "QLKHTC_ALLOW_DOI2",
  ACT_ALLOW_ADMIN: "QLKHTC_ALLOW_ADMIN",
};

/**
 *  Quản lý giám sát attp
 *
 */

// sự kiện
export const ACT_ID_SU_KIEN = {
  ACT_LIST: "SU_KIEN_LIST_ACT",
  ACT_CREATE: "SU_KIEN_CREATE_ACT",
  ACT_UPDATE: "SU_KIEN_UPDATE_ACT",
  ACT_DELETE: "SU_KIEN_DELETE_ACT",
  ACT_SEARCH: "SU_KIEN_SEARCH_ACT",
};

// giám sát attp
export const ACT_ID_GIAM_SAT_ATTP = {
  ACT_LIST: "GIAM_SAT_ATTP_LIST_ACT",
  ACT_CREATE: "GIAM_SAT_ATTP_CREATE_ACT",
  ACT_UPDATE: "GIAM_SAT_ATTP_UPDATE_ACT",
  ACT_DELETE: "GIAM_SAT_ATTP_DELETE_ACT",
  ACT_SEARCH: "GIAM_SAT_ATTP_SEARCH_ACT",
  ACT_BAN_HANH: "GIAM_SAT_ATTP_BAN_HANH_ACT",
};

// loại sự kiện
export const ACT_ID_LOAI_SU_KIEN = {
  ACT_LIST: "LOAI_SU_KIEN_LIST_ACT",
  ACT_CREATE: "LOAI_SU_KIEN_CREATE_ACT",
  ACT_UPDATE: "LOAI_SU_KIEN_UPDATE_ACT",
  ACT_DELETE: "LOAI_SU_KIEN_DELETE_ACT",
  ACT_SEARCH: "LOAI_SU_KIEN_SEARCH_ACT",
};

// kế hoach giám sát
export const ACT_ID_KE_HOACH_GIAM_SAT = {
  ACT_LIST: "KE_HOACH_GIAM_SAT_LIST_ACT",
  ACT_CREATE: "KE_HOACH_GIAM_SAT_CREATE_ACT",
  ACT_UPDATE: "KE_HOACH_GIAM_SAT_UPDATE_ACT",
  ACT_DELETE: "KE_HOACH_GIAM_SAT_DELETE_ACT",
  ACT_SEARCH: "KE_HOACH_GIAM_SAT_SEARCH_ACT",
  ACT_TRINH_PHE_DUYET: "QUAN_LY_GIAM_SAT_ATTP_TRINH_PHE_DUYET",
  ACT_PHE_DUYET: "QUAN_LY_GIAM_SAT_ATTP_PHE_DUYET",
  ACT_VIEW_BAN_HANH: "QUAN_LY_GIAM_SAT_ATTP_VIEW_BAN_HANH",
};

// Quyết định giám sát
export const ACT_ID_QUYET_DINH_GIAM_SAT = {
  ACT_LIST: "QUYET_DINH_GIAM_SAT_LIST_ACT",
  ACT_CREATE: "QUYET_DINH_GIAM_SAT_CREATE_ACT",
  ACT_UPDATE: "QUYET_DINH_GIAM_SAT_UPDATE_ACT",
  ACT_DELETE: "QUYET_DINH_GIAM_SAT_DELETE_ACT",
  ACT_SEARCH: "QUYET_DINH_GIAM_SAT_SEARCH_ACT",
  ACT_TRINH_PHE_DUYET: "QUYET_DINH_GIAM_SAT_TRINH_PHE_DUYET",
  ACT_PHE_DUYET: "QUYET_DINH_GIAM_SAT_PHE_DUYET",
  ACT_BAN_HANH: "QUYET_DINH_GIAM_SAT_BAN_HANH",
  ACT_VIEW_BAN_HANH: "QUYET_DINH_GIAM_SAT_VIEW_BAN_HANH",
};

// chi tiết sự kiện
export const ACT_ID_CHI_TIET_SU_KIEN = {
  ACT_LIST: "CHI_TIET_SU_KIEN_LIST_ACT",
  ACT_CREATE: "CHI_TIET_SU_KIEN_CREATE_ACT",
  ACT_UPDATE: "CHI_TIET_SU_KIEN_UPDATE_ACT",
  ACT_DELETE: "CHI_TIET_SU_KIEN_DELETE_ACT",
  ACT_SEARCH: "CHI_TIET_SU_KIEN_SEARCH_ACT",
};

//Thống kê báo cáo
export const ACT_ID_QUAN_LY_GIAM_SAT_ATTP_THONG_KE_BAO_CAO = {
  ACT_LIST: "QUAN_LY_GIAM_SAT_ATTP_THONG_KE_BAO_CAO_ACT",
};
/**
 *  END Quản lý giám sát attp
 */

//Quản lý tài sản thanh lý
export const ACT_ID_QUAN_LY_TAI_SAN_THANH_LY = {
  ACT_LIST: "THANH_LY_LIST_ACT",
  ACT_CREATE: "THANH_LY_CREATE_ACT",
  ACT_UPDATE: "THANH_LY_UPDATE_ACT",
  ACT_DELETE: "THANH_LY_DELETE_ACT",
  ACT_SEARCH: "THANH_LY_SEARCH_ACT",
  ACT_TRINH_PHE_DUYET: "THANH_LY_TAI_SAN_TRINH_PHE_DUYET",
  ACT_PHE_DUYET: "THANH_LY_TAI_SAN_PHE_DUYET",
};

//Báo cáo thống kê sự kiện
export const ACT_ID_BAO_CAO_THONG_KE_SU_KIEN = {
  ACT_LIST: "QUAN_LY_GIAM_SAT_ATTP_SU_KIEN_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_CHI_TIET_SU_KIEN = {
  ACT_LIST: "QUAN_LY_GIAM_SAT_ATTP_CHI_TIET_SU_KIEN_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_GIAM_SAT_ATTP = {
  ACT_LIST: "QUAN_LY_GIAM_SAT_ATTP_GIAM_SAT_ATTP_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_KE_HOACH_GIAM_SAT = {
  ACT_LIST: "QUAN_LY_GIAM_SAT_ATTP_KE_HOACH_GIAM_SAT_THONG_KE_BAO_CAO_ACT",
};

//Quản lý tài  chính
export const ACT_ID_QUAN_LY_TAI_CHINH = {
  ACT_LIST: "TAI_CHINH_LIST_ACT",
  ACT_CREATE: "TAI_CHINH_CREATE_ACT",
  ACT_UPDATE: "TAI_CHINH_UPDATE_ACT",
  ACT_UPDATE_PBCM: "TAI_CHINH_UPDATE_PBCM_ACT",
  ACT_DELETE: "TAI_CHINH_DELETE_ACT",
  ACT_SEARCH: "TAI_CHINH_SEARCH_ACT",
  ACT_TRINH_PHE_DUYET: "QLKHTC_TAI_CHINH_TRINH_PHE_DUYET",
  ACT_PHE_DUYET: "QLKHTC_TAI_CHINH_PHE_DUYET",
  ACT_THUC_HIEN: "TAI_CHINH_THUC_HIEN_ACT",
  ACT_YEU_CAU_BO_XUNG: "QLKHTC_TAI_CHINH_YEU_CAU_BO_XUNG",

  ACT_XAC_NHAN_THANH_TOAN: "TAI_CHINH_XAC_NHAN_THANH_TOAN_ACT",
  ACT_VIEW_DETAIL: "TAI_CHINH_VIEW_DETAIL_ACT",

  ACT_LOAI_KE_TOAN: "QLKHTC_TAI_CHINH_LOAI_KE_TOAN_ACT",
  ACT_LOAI_PBCM: "QLKHTC_TAI_CHINH_LOAI_PBCM_ACT",
  ACT_LOAI_TRUONG_BAN: "QLKHTC_TAI_CHINH_LOAI_TRUONG_BAN_ACT",
  ACT_XOA_KE_HOACH: "QLKHTC_TAI_CHINH_XOA_KE_HOACH_ACT",
};

// loại tài chính
export const ACT_ID_LOAI_TAI_CHINH = {
  ACT_LIST: "LOAI_TAI_CHINH_LIST_ACT",
  ACT_CREATE: "LOAI_TAI_CHINH_CREATE_ACT",
  ACT_UPDATE: "LOAI_TAI_CHINH_UPDATE_ACT",
  ACT_DELETE: "LOAI_TAI_CHINH_DELETE_ACT",
  ACT_SEARCH: "LOAI_TAI_CHINH_SEARCH_ACT",
};

// Nguồn kinh phí
export const ACT_ID_NGUON_KINH_PHI = {
  ACT_LIST: "NGUON_KINH_PHI_LIST_ACT",
  ACT_CREATE: "NGUON_KINH_PHI_CREATE_ACT",
  ACT_UPDATE: "NGUON_KINH_PHI_UPDATE_ACT",
  ACT_DELETE: "NGUON_KINH_PHI_DELETE_ACT",
  ACT_SEARCH: "NGUON_KINH_PHI_SEARCH_ACT",
};

// Danh mục chợ
export const ACT_ID_DANH_MUC_CHO = {
  ACT_LIST: "DANH_MUC_CHO_LIST_ACT",
  ACT_CREATE: "DANH_MUC_CHO_CREATE_ACT",
  ACT_UPDATE: "DANH_MUC_CHO_UPDATE_ACT",
  ACT_DELETE: "DANH_MUC_CHO_DELETE_ACT",
  ACT_SEARCH: "DANH_MUC_CHO_SEARCH_ACT",
  ACT_DETAIL: "DANH_MUC_CHO_DETAIL_ACT",
};

// Nhóm ngành hàng
export const ACT_ID_NHOM_NGANH_HANG = {
  ACT_LIST: "NHOM_NGANH_HANG_LIST_ACT",
  ACT_CREATE: "NHOM_NGANH_HANG_CREATE_ACT",
  ACT_UPDATE: "NHOM_NGANH_HANG_UPDATE_ACT",
  ACT_DELETE: "NHOM_NGANH_HANG_DELETE_ACT",
  ACT_SEARCH: "NHOM_NGANH_HANG_SEARCH_ACT",
};

//Hộ tiểu thương
export const ACT_ID_HO_TIEU_THUONG = {
  ACT_LIST: "HO_TIEU_THUONG_LIST_ACT",
  ACT_CREATE: "HO_TIEU_THUONG_CREATE_ACT",
  ACT_UPDATE: "HO_TIEU_THUONG_UPDATE_ACT",
  ACT_DELETE: "HO_TIEU_THUONG_DELETE_ACT",
  ACT_SEARCH: "HO_TIEU_THUONG_SEARCH_ACT",
  ACT_SYNC: "HO_TIEU_THUONG_SYNC_ACT",
  ACT_IMPORT: "HO_TIEU_THUONG_IMPORT",
};

export const ACT_ID_LO_KINH_DOANH = {
  ACT_LIST: "LO_KINH_DOANH_LIST_ACT",
  ACT_CREATE: "LO_KINH_DOANH_CREATE_ACT",
  ACT_UPDATE: "LO_KINH_DOANH_UPDATE_ACT",
  ACT_DELETE: "LO_KINH_DOANH_DELETE_ACT",
  ACT_SEARCH: "LO_KINH_DOANH_SEARCH_ACT",
};

//Báo cáo thống kê chính sách pháp luật
export const ACT_ID_BAO_CAO_THONG_DAU_TU_QUAN_LY_DIA_PHUONG = {
  ACT_LIST: "DAU_TU_QUAN_LY_ATTP_DIA_PHUONG_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_MAU_KIEM_NGHIEM = {
  ACT_LIST: "MAU_KIEM_NGHIEM_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_MAU_THUC_PHAM_NN = {
  ACT_LIST: "MAU_THUC_PHAM_NN_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_DANH_MUC_TRUYEN_THONG = {
  ACT_LIST: "DANH_MUC_TRUYEN_THONG_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_KET_QUA_KIEM_NGHIEM_TP = {
  ACT_LIST: "KET_QUA_KIEM_NGHIEM_THUC_PHAM_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_KET_QUA_THANH_KIEM_TRA_ATTP = {
  ACT_LIST: "KET_QUA_THANH_KIEM_TRA_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_KET_QUA_THUC_HIEN_TTHC = {
  ACT_LIST: "KET_QUA_THUC_HIEN_TTHC_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_QUAN_LY_CHO_SIEU_THI = {
  ACT_LIST: "QUAN_LY_CHO_SIEU_THI_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_SU_DUNG_KINH_PHI_DIA_PHUONG = {
  ACT_LIST: "SU_DUNG_KINH_PHI_DIA_PHUONG_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_SU_DUNG_KINH_PHI_TRUNG_UONG = {
  ACT_LIST: "SU_DUNG_KINH_PHI_TRUNG_UONG_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_GOS_NHIEM_TPNN = {
  ACT_LIST: "GIAM_SAT_O_NHIEM_TPNN_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_GOS_NHIEM_TPYTE = {
  ACT_LIST: "GIAM_SAT_O_NHIEM_TPYTE_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_TONG_HOP_TINH_HINH_VSATTP = {
  ACT_LIST: "TONG_HOP_TINH_HINH_VSATTP_THONG_KE_BAO_CAO_ACT",
};
export const ACT_ID_BAO_CAO_THONG_KE_XAY_DUNG_CSVC_DIA_PHUONG = {
  ACT_LIST: "XAY_DUNG_CO_SO_VAT_CHAT_DIA_PHUONG_THONG_KE_BAO_CAO_ACT",
};
//quản lý danh mục hạng sao
export const ACT_DANH_MUC_HANG_SAO = {
  ACT_LIST: "DANH_MUC_HANG_SAO_LIST_ACT",
  ACT_CREATE: "DANH_MUC_HANG_SAO_CREATE_ACT",
  ACT_UPDATE: "DANH_MUC_HANG_SAO_UPDATE_ACT",
  ACT_DELETE: "DANH_MUC_HANG_SAO_DELETE_ACT",
  ACT_MOVE: "DANH_MUC_HANG_SAO_MOVE_ACT",
  ACT_VIEW_MOBILE: "DANH_MUC_HANG_SAO_VIEW_MOBILE_ACT",
};
export const ACT_ID_DANH_GIA_HANG_SAO = {
  ACT_LIST: "DANH_GIA_HANG_SAO_LIST_ACT",
  ACT_CREATE: "DANH_GIA_HANG_SAO_CREATE_ACT",
  ACT_UPDATE: "DANH_GIA_HANG_SAO_UPDATE_ACT",
  ACT_DELETE: "DANH_GIA_HANG_SAO_DELETE_ACT",
  ACT_SEARCH: "DANH_GIA_HANG_SAO_SEARCH_ACT",
  ACT_DETAIL: "DANH_GIA_HANG_SAO_DETAIL_ACT",
};
export const ACT_ID_O_NHIEM_KIEM_TRA_GIAM_SAT = {
  ACT_LIST: "KE_HOACH_GIAM_SAT_O_NHIEM_LIST_ACT",
  ACT_CREATE: "KE_HOACH_GIAM_SAT_O_NHIEM_CREATE_ACT",
  ACT_UPDATE: "KE_HOACH_GIAM_SAT_O_NHIEM_UPDATE_ACT",
  ACT_DELETE: "KE_HOACH_GIAM_SAT_O_NHIEM_DELETE_ACT",
  ACT_SEARCH: "KE_HOACH_GIAM_SAT_O_NHIEM_SEARCH_ACT",
  ACT_ALLOW_THANH_TRA: "KE_HOACH_GIAM_SAT_O_NHIEM_ALLOW_THANH_TRA_ACT",
  ACT_ALLOW_NGHIEP_VU: "KE_HOACH_GIAM_SAT_O_NHIEM_ALLOW_NGHIEP_VU_ACT",
  ACT_CREATE_CUOC_THANH_TRA: "QTNVTT_CUOC_THANH_TRA_CREATE_CUOC_THANH_TRA_ACT",
  ACT_LIST_CUOC_THANH_TRA: "QTNVTT_CUOC_THANH_TRA_LIST_CUOC_THANH_TRA_ACT",
  ACT_TRINHPHEDUYET: "KE_HOACH_GIAM_SAT_O_NHIEM_TRINH_PHE_DUYET",
  ACT_PHE_DUYET: "KE_HOACH_GIAM_SAT_O_NHIEM_PHE_DUYET",
  ACT_BAN_HANH: "KE_HOACH_GIAM_SAT_O_NHIEM_BAN_HANH",
  ACT_VIEW_BAN_HANH: "KE_HOACH_GIAM_SAT_O_NHIEM_VIEW_BAN_HANH",
  ACT_DOWNLOAD: "KE_HOACH_GIAM_SAT_O_NHIEM_DOWNLOAD",
  ACT_DETAIL: "KE_HOACH_GIAM_SAT_O_NHIEM_DETAIL",
};
