/**
 *  DEFAULT
 */
export const FORM_NAME_DEFAULT = "FORM_NAME_DEFAULT";

/**
 *  START_ACCOUNT_CURRENT
 */
export const FORM_NAME_PROFILE = "FORM_NAME_PROFILE";
export const FORM_NAME_CHANGE_PASSWORD = "FORM_NAME_CHANGE_PASSWORD";
/**
 *  END_ACCOUNT_CURRENT
 */

/**
 *  START_SYSTEM
 *  Hệ thống
 *      Quyền
 */
export const FORM_NAME_PERMISSION = "FORM_NAME_PERMISSION";

/**
 *  Hệ thống
 *      Người dùng
 */
export const FORM_NAME_ACCOUNT = "FORM_NAME_ACCOUNT";
export const FORM_NAME_ACCOUNT_SEARCH = "FORM_NAME_ACCOUNT_SEARCH";

/**
 *  Hệ thống
 *      Nhóm người dùng
 */
export const FORM_NAME_ACCOUNT_GROUP = "FORM_NAME_ACCOUNT_GROUP";
export const FORM_NAME_ACCOUNT_GROUP_SEARCH = "FORM_NAME_ACCOUNT_GROUP_SEARCH";

/**
 *  Hệ thống
 *      Cấu hình
 */
export const FORM_NAME_CAU_HINH = "FORM_NAME_CAU_HINH";

/**
 *  Hệ thống
 *      Cấu hình
 *         Một cửa
 */
export const FORM_NAME_DONG_BO_MOT_CUA = "FORM_NAME_DONG_BO_MOT_CUA";
/**
 *  Hệ thống
 *      Dịch vụ
 */
export const FORM_NAME_SERVICE = "FORM_NAME_SERVICE";
/**
 *  END_SYSTEM
 */

/**
 *  START_DM
 *  Danh mục
 *      Địa bàn
 */

/**
 *  END_DM
 */

/**
 *  START_QLCSSXKD
 *  Quản lý cơ sở sản xuât kinh doanh
 *      Danh mục
 */
export const FORM_NAME_DOAN_THAM_DINH = "FORM_NAME_DOAN_THAM_DINH";
export const FORM_NAME_LINH_VUC = "FORM_NAME_LINH_VUC";
export const FORM_NAME_LINH_VUC_SEARCH = "FORM_NAME_LINH_VUC_SEARCH";
export const FORM_NAME_LOAI_HINH_CO_SO = "FORM_NAME_LOAI_HINH_CO_SO";
export const FORM_NAME_LOAI_HINH_CO_SO_SEARCH = "FORM_NAME_LOAI_HINH_CO_SO_SEARCH";
export const FORM_NAME_DANH_MUC_CHO = "FORM_NAME_DANH_MUC_CHO";
export const FORM_NAME_NHOM_NGANH_HANG = "FORM_NAME_NHOM_NGANH_HANG";
export const FORM_NAME_HO_TIEU_THUONG = "FORM_NAME_HO_TIEU_THUONG";
export const FORM_NAME_LO_KINH_DOANH = "FORM_NAME_LO_KINH_DOANH";
export const FORM_NAME_BAO_CAO_HO_TIEU_THUONG = "FORM_NAME_BAO_CAO_HO_TIEU_THUONG";
// phòng ban
export const FORM_NAME_QUAN_LY_PHONG_BAN = "FORM_NAME_QUAN_LY_PHONG_BAN";
export const FORM_NAME_QUAN_LY_PHONG_BAN_SEARCH = "FORM_NAME_QUAN_LY_PHONG_BAN_SEARCH";

// quốc gia
export const FORM_NAME_QUAN_LY_QUOC_GIA = "FORM_NAME_QUAN_LY_QUOC_GIA";
export const FORM_NAME_QUAN_LY_QUOC_GIA_SEARCH = "FORM_NAME_QUAN_LY_QUOC_GIA_SEARCH";

/**
 *  Quản lý cơ sở sản xuât kinh doanh
 *      Cơ sở sản xuất kinh doanh
 */
export const FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH = "FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH";
export const FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH_SEARCH = "FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH_SEARCH";
export const FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH_REPORT = "FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH_REPORT";

/**
 *  Quản lý cơ sở sản xuât kinh doanh
 *      Hồ sơ tiếp nhận một cửa
 */
export const FORM_NAME_HO_SO_TIEP_NHAN_MOT_CUA_REPORT = "FORM_NAME_HO_SO_TIEP_NHAN_MOT_CUA_REPORT";

/**
 *  Quản lý cơ sở sản xuât kinh doanh
 *      Cơ sở sản xuất kinh doanh
 */
export const FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO = "FORM_NAME_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO";

/**
 *  END_QLCSSXKD
 */

/**
 *  START_QLVBPL
 *  Quản lý văn bản pháp luật
 *      Danh mục
 */
export const FORM_NAME_VBPL_LINH_VUC = "FORM_NAME_VBPL_LINH_VUC";
export const FORM_NAME_VBPL_LINH_VUC_SEARCH = "FORM_NAME_VBPL_LINH_VUC_SEARCH";

/**
 *  Quản lý văn bản pháp luật
 *      Văn bản pháp luật
 */
export const FORM_NAME_VAN_BAN_PHAP_LUAT = "FORM_NAME_VAN_BAN_PHAP_LUAT";
export const FORM_NAME_VAN_BAN_PHAP_LUAT_SEARCH = "FORM_NAME_VAN_BAN_PHAP_LUAT_SEARCH";
/**
 *  END_QLVBPL
 */


/**
 *  Quản lý tài sản
 *      tài sản
 */
export const FORM_NAME_QUAN_LY_TAI_SAN = "FORM_NAME_QUAN_LY_TAI_SAN";
export const FORM_NAME_QUAN_LY_TAI_SAN_SEARCH = "FORM_NAME_QUAN_LY_TAI_SAN_SEARCH";
export const FORM_NAME_QUAN_LY_CAP_PHAT_TAI_SAN = "FORM_NAME_QUAN_LY_CAP_PHAT_TAI_SAN";
export const FORM_NAME_QUAN_LY_SUA_CHUA_TAI_SAN = "FORM_NAME_QUAN_LY_SUA_CHUA_TAI_SAN";
export const FORM_NAME_QUAN_LY_CAP_PHAT_TAI_SAN_SEARCH = "FORM_NAME_QUAN_LY_CAP_PHAT_TAI_SAN_SEARCH";
export const FORM_NAME_QUAN_LY_DANH_MUC_LOAI_TAI_SAN = "FORM_NAME_QUAN_LY_DANH_MUC_LOAI_TAI_SAN";
export const FORM_NAME_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_SEARCH = "FORM_NAME_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_SEARCH";

export const FORM_NAME_QUAN_LY_DANH_MUC_NHOM_TAI_SAN = "FORM_NAME_QUAN_LY_DANH_MUC_NHOM_TAI_SAN";
export const FORM_NAME_QUAN_LY_DANH_MUC_NHOM_TAI_SAN_SEARCH = "FORM_NAME_QUAN_LY_DANH_MUC_NHOM_TAI_SAN_SEARCH";

/**
 *  END_QLVBPL
 */



/**
 *  Quản lý đối ngoại
 *      quản lý đoàn vào
 */
export const FORM_NAME_QUAN_LY_DOAN_VAO = "FORM_NAME_QUAN_LY_DOAN_VAO";
export const FORM_NAME_QUAN_LY_DOAN_VAO_SEARCH = "FORM_NAME_QUAN_LY_DOAN_VAO_SEARCH";

//  quản lý đoàn ra
export const FORM_NAME_QUAN_LY_DOAN_RA = "FORM_NAME_QUAN_LY_DOAN_RA";
export const FORM_NAME_QUAN_LY_DOAN_RA_SEARCH = "FORM_NAME_QUAN_LY_DOAN_RA_SEARCH";

/**
 *  END_QLVBPL
 */


/**
 *  Ca Nhan Nghi Phep
 *      tài sản
 */
export const FORM_NAME_THONG_TIN_NGHI_PHEP = "FORM_NAME_THONG_TIN_NGHI_PHEP";
export const FORM_NAME_THONG_TIN_CONG_TAC = "FORM_NAME_THONG_TIN_CONG_TAC";
export const FORM_NAME_CAU_HINH_NGHI_PHEP = "FORM_NAME_CAU_HINH_NGHI_PHEP";
export const FORM_NAME_CAU_HINH_NGHI_PHEP_ABC = "FORM_NAME_CAU_HINH_NGHI_PHEP_ABC";

/**
 *  START_QLNS
 *  Quản lý nhân sự
 *      Danh mục
 */
export const FORM_NAME_PHONG_BAN = "FORM_NAME_PHONG_BAN";
export const FORM_NAME_PHONG_BAN_SEARCH = "FORM_NAME_PHONG_BAN_SEARCH";

/**
 *  Quản lý nhân sự
 *      Nhân sự
 */
export const FORM_NAME_NHAN_SU = "FORM_NAME_NHAN_SU";
export const FORM_NAME_NHAN_SU_SEARCH = "FORM_NAME_NHAN_SU_SEARCH";

/**
 *  Quản lý nhân sự
 *      Chương trình đào tạo tập huấn
 */
export const FORM_NAME_CHUONGTRINH_DAOTAOTAPHUAN = "FORM_NAME_CHUONGTRINH_DAOTAOTAPHUAN";
export const FORM_NAME_CHUONGTRINH_DAOTAOTAPHUAN_SEARCH = "FORM_NAME_CHUONGTRINH_DAOTAOTAPHUAN_SEARCH";

/**
 *  Quản lý nhân sự
 *      Đào tạo tập huấn
 */
export const FORM_NAME_THONGTIN_DAOTAOTAPHUAN = "FORM_NAME_THONGTIN_DAOTAOTAPHUAN";
export const FORM_NAME_THONGTIN_DAOTAOTAPHUAN_SEARCH = "FORM_NAME_THONGTIN_DAOTAOTAPHUAN_SEARCH";

/**
 *  Quản lý nhân sự
 *      Thông tin khen thưởng
 */
export const FORM_NAME_THONGTIN_KHENTHUONG = "FORM_NAME_THONGTIN_KHENTHUONG";
export const FORM_NAME_THONGTIN_KHENTHUONG_SEARCH = "FORM_NAME_THONGTIN_KHENTHUONG_SEARCH";

/**
 *  Quản lý nhân sự
 *      Danh hiệu thi đua
 */
export const FORM_NAME_DANHHIEU_THIDUA = "FORM_NAME_DANHHIEU_THIDUA";
export const FORM_NAME_DANHHIEU_THIDUA_SEARCH = "FORM_NAME_DANHHIEU_THIDUA_SEARCH";

/**
 *  Quản lý nhân sự
 *      Thông tin nghỉ phép
 */
export const FORM_NAME_THONGTIN_NGHIPHEP = "FORM_NAME_THONGTIN_NGHIPHEP";
export const FORM_NAME_THONGTIN_NGHIPHEP_SEARCH = "FORM_NAME_THONGTIN_NGHIPHEP_SEARCH";

/**
 *  Quản lý nhân sự
 *      Thông tin nghỉ phép user
 */
export const FORM_NAME_THONGTIN_NGHIPHEP_USER = "FORM_NAME_THONGTIN_NGHIPHEP_USER";
export const FORM_NAME_THONGTIN_NGHIPHEP_USER_SEARCH = "FORM_NAME_THONGTIN_NGHIPHEP_USER_SEARCH";

/**
 *  Quản lý nhân sự
 *      Tài sản công
 */
export const FORM_NAME_THONGTIN_TAISANCONG = "FORM_NAME_THONGTIN_TAISANCONG";
export const FORM_NAME_THONGTIN_TAISANCONG_SEARCH = "FORM_NAME_THONGTIN_TAISANCONG_SEARCH";
/**
 *  END_QLNS
 */

/**
*  Quản lý nghi phep
*      nghỉ phép
*/
export const FORM_NAME_QUAN_LY_NGHI_PHEP = "FORM_NAME_QUAN_LY_NGHI_PHEP";
export const FORM_NAME_THONG_KE_BAO_CAO_NGHI_PHEP = "FORM_NAME_THONG_KE_BAO_CAO_NGHI_PHEP";

/**
 *  END_QLNS
 */

/**
 *  START_QLQTNVTT
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Kế hoạch thanh tra
 */
export const FORM_NAME_QTNVTT_KE_HOACH_THANH_TRA = "FORM_NAME_QTNVTT_KE_HOACH_THANH_TRA";
export const FORM_NAME_QTNVTT_KE_HOACH_THANH_TRA_SEARCH = "FORM_NAME_QTNVTT_KE_HOACH_THANH_TRA_SEARCH";

/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Cuộc thanh tra
 */
export const FORM_NAME_QTNVTT_CUOC_THANH_TRA = "FORM_NAME_QTNVTT_CUOC_THANH_TRA";
export const FORM_NAME_QTNVTT_CUOC_THANH_TRA_SEARCH = "FORM_NAME_QTNVTT_CUOC_THANH_TRA_SEARCH";
export const FORM_NAME_QTNVTT_CUOC_THANH_TRA_BIEN_BAN = "FORM_NAME_QTNVTT_CUOC_THANH_TRA_BIEN_BAN";

/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Đợt thanh tra
 */
export const FORM_NAME_QTNVTT_DOT_THANH_TRA = "FORM_NAME_QTNVTT_DOT_THANH_TRA";
export const FORM_NAME_QTNVTT_DOT_THANH_TRA_SEARCH = "FORM_NAME_QTNVTT_DOT_THANH_TRA_SEARCH";
export const FORM_NAME_QTNVTT_DOT_THANH_TRA_BIEN_BAN = "FORM_NAME_QTNVTT_DOT_THANH_TRA_BIEN_BAN";

/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Đoàn thanh tra
 */
export const FORM_NAME_QTNVTT_DOAN_THANH_TRA = "FORM_NAME_QTNVTT_DOAN_THANH_TRA";
export const FORM_NAME_QTNVTT_DOAN_THANH_TRA_SEARCH = "FORM_NAME_QTNVTT_DOAN_THANH_TRA_SEARCH";
/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Thống kê báo cáo
 */
export const FORM_NAME_QTNVTT_TKBC_DSCS = "FORM_NAME_QTNVTT_TKBC_DSCS";
export const FORM_NAME_QTNVTT_TKBC_TTPC = "FORM_NAME_QTNVTT_TKBC_TTPC";
export const FORM_NAME_QTNVTT_TKBC_CTVP = "FORM_NAME_QTNVTT_TKBC_CTVP";
/**
 *  END_QLQTNVTT
 */

/**
 *  START_QLQTDTXLNDTP
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Hồ sơ ngộ độc thực phẩm
 */
export const FORM_NAME_HO_SO_NGO_DOC_THUC_PHAM = "FORM_NAME_HO_SO_NGO_DOC_THUC_PHAM";
export const FORM_NAME_HO_SO_NGO_DOC_THUC_PHAM_SEARCH = "FORM_NAME_HO_SO_NGO_DOC_THUC_PHAM_SEARCH";

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Điều tra ngộ độc thực phẩm
 */
export const FORM_NAME_DIEU_TRA_NGO_DOC_THUC_PHAM = "FORM_NAME_DIEU_TRA_NGO_DOC_THUC_PHAM";
export const FORM_NAME_DIEU_TRA_NGO_DOC_THUC_PHAM_SEARCH = "FORM_NAME_DIEU_TRA_NGO_DOC_THUC_PHAM_SEARCH";

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Xử lý ngộ độc thực phẩm
 */
export const FORM_NAME_QTDTXL_NDTP_XU_LY = "FORM_NAME_QTDTXL_NDTP_XU_LY";
export const FORM_NAME_XU_LY_NGO_DOC_THUC_PHAM = "FORM_NAME_XU_LY_NGO_DOC_THUC_PHAM";
export const FORM_NAME_XU_LY_NGO_DOC_THUC_PHAM_SEARCH = "FORM_NAME_XU_LY_NGO_DOC_THUC_PHAM_SEARCH";

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Thống kê báo cáo
 */
export const FORM_NAME_QTDTXL_NDTP_THONG_KE_BAO_CAO_SEARCH = "FORM_NAME_QTDTXL_NDTP_THONG_KE_BAO_CAO_SEARCH";
export const FORM_NAME_QTDTXL_NDTP_THONG_KE_BAO_CAO_CHI_TIET_SEARCH = "FORM_NAME_QTDTXL_NDTP_THONG_KE_BAO_CAO_CHI_TIET_SEARCH";
/**
 *  END_QLQTDTXLNDTP
 */

/**
 *  START_QLTTTCB
 *  Quản lý thủ tục tự công bố
 *      Hồ sơ thủ tục tự công bố
 */
export const FORM_NAME_HO_SO_TU_CONG_BO = "FORM_NAME_HO_SO_TU_CONG_BO";
export const FORM_NAME_HO_SO_TU_CONG_BO_SEARCH = "FORM_NAME_HO_SO_TU_CONG_BO_SEARCH"
export const FORM_NAME_THONG_BAO_HO_SO_TU_CONG_BO = "FORM_NAME_THONG_BAO_HO_SO_TU_CONG_BO";
export const FORM_NAME_THONG_BAO_HO_SO_TU_CONG_BO_SEARCH = "FORM_NAME_THONG_BAO_HO_SO_TU_CONG_BO_SEARCH"
export const FORM_NAME_TCBSP_BAO_CAO_THONG_KE_SEARCH = "FORM_NAME_TCBSP_BAO_CAO_THONG_KE_SEARCH";

export const FORM_NAME_TCB_NHOM = "FORM_NAME_TCB_NHOM";
export const FORM_NAME_TCB_NHOM_SEARCH = "FORM_NAME_TCB_NHOM_SEARCH";
export const FORM_NAME_TCB_PHAN_NHOM = "FORM_NAME_TCB_PHAN_NHOM";
export const FORM_NAME_TCB_PHAN_NHOM_SEARCH = "FORM_NAME_TCB_PHAN_NHOM_SEARCH";
/**
 *  END_QLTTTCB
 */

/**
 *  START_QLCTGSON
 *  Quản lý công tác giám sát ô nhiễm
 *      Danh mục
 *          Chỉ tiêu
 */
export const FORM_NAME_QLCTGSON_DM_CHI_TIEU = "FORM_NAME_QLCTGSON_DM_CHI_TIEU";
export const FORM_NAME_QLCTGSON_DM_CHI_TIEU_SEARCH = "FORM_NAME_QLCTGSON_DM_CHI_TIEU_SEARCH";

/**
 *  Quản lý công tác giám sát ô nhiễm
 *      Danh mục
 *          Nhóm thực phẩm
 */
export const FORM_NAME_QLCTGSON_DM_NHOM_THUC_PHAM = "FORM_NAME_QLCTGSON_DM_NHOM_THUC_PHAM";
export const FORM_NAME_QLCTGSON_DM_NHOM_THUC_PHAM_SEARCH = "FORM_NAME_QLCTGSON_DM_NHOM_THUC_PHAM_SEARCH";

/**
 *  Quản lý công tác giám sát ô nhiễm
 *      Đợt kiểm tra
 */
export const FORM_NAME_QLCTGSON_DOT_KIEM_TRA = "FORM_NAME_QLCTGSON_DOT_KIEM_TRA";
export const FORM_NAME_QLCTGSON_DOT_KIEM_TRA_SEARCH = "FORM_NAME_QLCTGSON_DOT_KIEM_TRA_SEARCH";
export const FORM_NAME_CHI_TIEU_GIAM_SAT = "FORM_NAME_CHI_TIEU_GIAM_SAT";

/**
 *  Quản lý công tác giám sát ô nhiễm
 *      Thống kê báo cáo
 */
export const FROM_NAME_QLCTGSON_THONG_KE_BAO_CAO_SEARCH = "FROM_NAME_QLCTGSON_THONG_KE_BAO_CAO_SEARCH";

/**
 *  Quản lý công tác giám sát ô nhiễm
 *      Thanh lập đoàn kiểm tra - giám sát
 */
export const FROM_NAME_QLCTGSON_CUOC_GIAM_SAT = "FROM_NAME_QLCTGSON_CUOC_GIAM_SAT";
export const FROM_NAME_QLCTGSON_CUOC_GIAM_SAT_SEARCH = "FROM_NAME_QLCTGSON_CUOC_GIAM_SAT_SEARCH";

/**
 *  START_QLTDCGCNATTP
 *  Quản lý thẩm định cấp giấy chứng nhận an toàn thực phẩm
 *      Hồ sơ cấp giấy chứng nhận
 */
export const FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN = "FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN";
export const FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN_SEARCH = "FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN_SEARCH";

/**
 *  Quản lý thẩm định cấp giấy chứng nhận an toàn thực phẩm
 *      Hồ sơ đã xử lý
 */
export const FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY = "FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY";
export const FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_SEARCH = "FORM_NAME_HO_SO_CAP_GIAY_CHUNG_NHAN_DA_XU_LY_SEARCH";

/**
 *  Quản lý thẩm định cấp giấy chứng nhận an toàn thực phẩm
 *      Kế hoạch thẩm định
 */
export const FORM_NAME_KE_HOACH_THAM_DINH = "FORM_NAME_KE_HOACH_THAM_DINH";
export const FORM_NAME_KE_HOACH_THAM_DINH_THAM_DINH = "FORM_NAME_KE_HOACH_THAM_DINH_THAM_DINH";
export const FORM_NAME_KE_HOACH_THAM_DINH_SEARCH = "FORM_NAME_KE_HOACH_THAM_DINH_SEARCH";
/**
 *  END_QLTDCGCNATTP
 */

/**
 *  START_QLTTTCB
 *  Quản lý thủ tục tự công bố
 *      Công tác hậu kiểm
 */
export const FORM_NAME_CONG_TAC_HAU_KIEM = "FORM_NAME_CONG_TAC_HAU_KIEM";
export const FORM_NAME_CONG_TAC_HAU_KIEM_SEARCH = "FORM_NAME_CONG_TAC_HAU_KIEM_SEARCH";
export const FORM_NAME_KE_HOACH_HAU_KIEM_HAU_KIEM = "FORM_NAME_KE_HOACH_HAU_KIEM_HAU_KIEM";
/**
 *  END_QLTTTCB
 */

/**
 *  START_QLTNVXLPAKN
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Hồ sơ phản ánh kiến nghị
 */
export const FORM_NAME_HO_SO_PHAN_ANH_KIEN_NGHI = "FORM_NAME_HO_SO_PHAN_ANH_KIEN_NGHI";
export const FORM_NAME_HO_SO_PHAN_ANH_KIEN_NGHI_SEARCH = "FORM_NAME_HO_SO_PHAN_ANH_KIEN_NGHI_SEARCH";

/**
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Biên bản thanh tra
 */
export const FORM_NAME_PAKN_BIEN_BAN_THANH_TRA = "FORM_NAME_PAKN_BIEN_BAN_THANH_TRA";
export const FORM_NAME_PAKN_BIEN_BAN_THANH_TRA_SEARCH = "FORM_NAME_PAKN_BIEN_BAN_THANH_TRA_SEARCH";

/**
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Biên bản xử phạt
 */
export const FORM_NAME_PAKN_BIEN_BAN_XU_PHAT = "FORM_NAME_PAKN_BIEN_BAN_XU_PHAT";
export const FORM_NAME_PAKN_BIEN_BAN_XU_PHAT_SEARCH = "FORM_NAME_PAKN_BIEN_BAN_XU_PHAT_SEARCH";
/**
 *  END_QLTNVXLPAKN
 */

/**
 *  START_QLXNQC
 *  Quản lý xác nhận quảng cáo
 *      Xác nhận quảng cáo
 */
export const FORM_NAME_XAC_NHAN_QUANG_CAO = "FORM_XAC_NHAN_QUANG_CAO";
export const FORM_NAME_XAC_NHAN_QUANG_CAO_SEARCH = "FORM_NAME_XAC_NHAN_QUANG_CAO_SEARCH";

/**
 *  Quản lý xác nhận quảng cáo
 *      Thống kê báo cáo
 */
export const FORM_NAME_XNQC_BAO_CAO_THONG_KE_SEARCH = "FORM_NAME_XNQC_BAO_CAO_THONG_KE_SEARCH";
/**
 *  END_QLXNQC
 */

/**
 *  START_QLCTPAT
 *  Quản lý chuỗi thực phẩm an toàn
 *      Nhóm chuỗi thực phẩm
 */
export const FORM_NAME_NHOM_CHUOI_THUC_PHAM = "FORM_NAME_NHOM_CHUOI_THUC_PHAM";
export const FORM_NAME_NHOM_CHUOI_THUC_PHAM_SEARCH = "FORM_NAME_NHOM_CHUOI_THUC_PHAM_SEARCH";
export const FORM_NAME_THONGKE_BAOCAO_CHUOI_THUCPHAM_SEARCH = "FORM_NAME_THONGKE_BAOCAO_CHUOI_THUCPHAM_SEARCH";
/**
 *  Quản lý chuỗi thực phẩm an toàn
 *      Kế hoạch thẩm định
 */
export const FORM_NAME_KE_HOACH_THAM_DINH_CTPAT = "FORM_NAME_KE_HOACH_THAM_DINH_CTPAT";
export const FORM_NAME_KE_HOACH_THAM_DINH_CTPAT_SEARCH = "FORM_NAME_KE_HOACH_THAM_DINH_CTPAT_SEARCH";
/**
 *  END_QLCTPAT
 */

/**
 *	START_QLCTXNKTATTP
 *  Quản lý xác nhận kiến thức attp
 *      Hồ sơ xác nhận kiến thức attp
 */
export const FORM_NAME_HO_SO_XAC_NHAN_KIEN_THUC_ATTP = "FORM_NAME_HO_SO_XAC_NHAN_KIEN_THUC_ATTP";
export const FORM_NAME_HO_SO_XAC_NHAN_KIEN_THUC_ATTP_SEARCH = "FORM_NAME_HO_SO_XAC_NHAN_KIEN_THUC_ATTP_SEARCH";
/**
 *  Quản lý xác nhận kiến thức attp
 *      Đợt xác nhận kiến thức attp
 */
export const FORM_NAME_DOT_XAC_NHAN_KIEN_THUC_ATTP = "FORM_NAME_DOT_XAC_NHAN_KIEN_THUC_ATTP";
export const FORM_NAME_DOT_XAC_NHAN_KIEN_THUC_ATTP_SEARCH = "FORM_NAME_DOT_XAC_NHAN_KIEN_THUC_ATTP_SEARCH";
export const FORM_NAME_XNKTATTP_BAO_CAO_THONG_KE_SEARCH = "FORM_NAME_XNKTATTP_BAO_CAO_THONG_KE_SEARCH";
/**
 *  END_QLCTXNKTATTP
 */
/**
 *  START_BCTH
 *  Báo cáo tổng hợp
 */
export const FORM_NAME_BAO_CAO_TONG_HOP = "FORM_NAME_BAO_CAO_TONG_HOP";
export const FORM_NAME_BAO_CAO_TONG_HOP_SEARCH = "FORM_NAME_BAO_CAO_TONG_HOP_SEARCH";
/**
 *  END_BCTH
 */

/**
 *  START QLBM
 */
export const FORM_NAME_QUAN_LY_BIEU_MAU = "FORM_NAME_QUAN_LY_BIEU_MAU";
export const FORM_NAME_QUAN_LY_BIEU_MAU_SEARCH = "FORM_NAME_QUAN_LY_BIEU_MAU_SEARCH";


/**
 *  START QLKHTC
 *  Quản lý kế hoạch tài chính
 */

export const FORM_NAME_QUAN_LY_KE_HOACH_TAI_CHINH = "FORM_NAME_QUAN_LY_KE_HOACH_TAI_CHINH";
export const FORM_NAME_QUAN_LY_KE_HOACH_TAI_CHINH_SEARCH = "FORM_NAME_QUAN_LY_KE_HOACH_TAI_CHINH_SEARCH";
/**
 *  END QLKHTC
 *  Quản lý kế hoạch tài chính
 */



/**
*  Quản lý chính sách pháp luât
*      dau tư qlattp dia phuong
*/
export const FORM_NAME_QUAN_LY_ATTP_DIA_PHUONG = "FORM_NAME_QUAN_LY_ATTP_DIA_PHUONG";
export const FORM_NAME_QUAN_LY_ATTP_DIA_PHUONG_SEARCH = "FORM_NAME_QUAN_LY_ATTP_DIA_PHUONG_SEARCH";

// kết quả thanh kiểm tra
export const FORM_NAME_KET_QUA_THANH_KIEM_TRA = "FORM_NAME_KET_QUA_THANH_KIEM_TRA";
export const FORM_NAME_KET_QUA_THANH_KIEM_TRA_SEARCH = "FORM_NAME_KET_QUA_THANH_KIEM_TRA_SEARCH";

// kết quả kiểm nghiêm tp
export const FORM_NAME_KET_QUA_KIEM_NGHIEM_TP = "FORM_NAME_KET_QUA_KIEM_NGHIEM_TP";
export const FORM_NAME_KET_QUA_KIEM_NGHIEM_TP_SEARCH = "FORM_NAME_KET_QUA_KIEM_NGHIEM_TP_SEARCH";


// gos_nhiem_Tpnn
export const FORM_NAME_GOS_NHIEM_TPNN = "FORM_NAME_GOS_NHIEM_TPNN";
export const FORM_NAME_GOS_NHIEM_TPNN_SEARCH = "FORM_NAME_GOS_NHIEM_TPNN_SEARCH";


// gos nhiễm tpyt
export const FORM_NAME_GOS_NHIEM_TPYT = "FORM_NAME_GOS_NHIEM_TPYT";
export const FORM_NAME_GOS_NHIEM_TPYT_SEARCH = "FORM_NAME_GOS_NHIEM_TPYT_SEARCH";


// kết quả kiểm nghiêm tthc
export const FORM_NAME_KET_QUA_THUC_HIEN_TTHC = "FORM_NAME_KET_QUA_THUC_HIEN_TTHC";
export const FORM_NAME_KET_QUA_THUC_HIEN_TTHC_SEARCH = "FORM_NAME_KET_QUA_THUC_HIEN_TTHC_SEARCH";

// quản lý chợ siêu thị
export const FORM_NAME_QUAN_LY_CHO_SIEU_THI = "FORM_NAME_QUAN_LY_CHO_SIEU_THI";
export const FORM_NAME_QUAN_LY_CHO_SIEU_THI_SEARCH = "FORM_NAME_QUAN_LY_CHO_SIEU_THI_SEARCH";

// sử dụng kinh phi dia phuong
export const FORM_NAME_SU_DUNG_KINH_PHI_DIA_PHUONG = "FORM_NAME_SU_DUNG_KINH_PHI_DIA_PHUONG";
export const FORM_NAME_SU_DUNG_KINH_PHI_DIA_PHUONG_SEARCH = "FORM_NAME_SU_DUNG_KINH_PHI_DIA_PHUONG_SEARCH";

// sử dụng kinh phi TW
export const FORM_NAME_SU_DUNG_KINH_PHI_TW = "FORM_NAME_SU_DUNG_KINH_PHI_TW";
export const FORM_NAME_SU_DUNG_KINH_PHI_TW_SEARCH = "FORM_NAME_SU_DUNG_KINH_PHI_TW_SEARCH";

// tổng hợp tình hình vsattp
export const FORM_NAME_TONG_HOP_TINH_HINH_VSATTP = "FORM_NAME_TONG_HOP_TINH_HINH_VSATTP";
export const FORM_NAME_TONG_HOP_TINH_HINH_VSATTP_SEARCH = "FORM_NAME_TONG_HOP_TINH_HINH_VSATTP_SEARCH";

// Xây dựng csvc địa phương
export const FORM_NAME_XAY_DUNG_CSVC_DIA_PHUONG = "FORM_NAME_XAY_DUNG_CSVC_DIA_PHUONG";
export const FORM_NAME_XAY_DUNG_CSVC_DIA_PHUONG_SEARCH = "FORM_NAME_XAY_DUNG_CSVC_DIA_PHUONG_SEARCH";


// Mẫu kiểm nghiệm
export const FORM_NAME_MAU_KIEM_NGHIEM = "FORM_NAME_MAU_KIEM_NGHIEM";
export const FORM_NAME_MAU_KIEM_NGHIEM_SEARCH = "FORM_NAME_MAU_KIEM_NGHIEM_SEARCH";


// Mẫu thực phẩm nn
export const FORM_NAME_MAU_THUC_PHAM_NN = "FORM_NAME_MAU_THUC_PHAM_NN";
export const FORM_NAME_MAU_THUC_PHAM_NN_SEARCH = "FORM_NAME_MAU_THUC_PHAM_NN_SEARCH";



// Truyền thông
export const FORM_NAME_TRUYEN_THONG = "FORM_NAME_TRUYEN_THONG";
export const FORM_NAME_TRUYEN_THONG_SEARCH = "FORM_NAME_TRUYEN_THONG_SEARCH";


/**
 *  END_QLVBPL
 */


// su_kien
export const FORM_NAME_SU_KIEN = "FORM_NAME_SU_KIEN";
export const FORM_NAME_SU_KIEN_SEARCH = "FORM_NAME_SU_KIEN_SEARCH";

// loai su_kien
export const FORM_NAME_LOAI_SU_KIEN = "FORM_NAME_LOAI_SU_KIEN";
export const FORM_NAME_LOAI_SU_KIEN_SEARCH = "FORM_NAME_LOAI_SU_KIEN_SEARCH";

//kế hoạch giám sát
export const FORM_NAME_KE_HOACH_GIAM_SAT = "FORM_NAME_KE_HOACH_GIAM_SAT";
export const FORM_NAME_KE_HOACH_GIAM_SAT_QUYET_DINH_GIAM_SAT = "FORM_NAME_KE_HOACH_GIAM_SAT_QUYET_DINH_GIAM_SAT";
export const FORM_NAME_KE_HOACH_GIAM_SAT_PHIEU_GIAM_SAT = "FORM_NAME_KE_HOACH_GIAM_SAT_PHIEU_GIAM_SAT";
export const FORM_NAME_KE_HOACH_GIAM_SAT_BIEN_BAN_LAM_VIEC = "FORM_NAME_KE_HOACH_GIAM_SAT_BIEN_BAN_LAM_VIEC";
export const FORM_NAME_KE_HOACH_GIAM_SAT_SEARCH = "FORM_NAME_KE_HOACH_GIAM_SAT_SEARCH";

// chi tiet su_kien
export const FORM_NAME_CHI_TIET_SU_KIEN = "FORM_NAME_CHI_TIET_SU_KIEN";
export const FORM_NAME_CHI_TIET_SU_KIEN_SEARCH = "FORM_NAME_CHI_TIET_SU_KIEN_SEARCH";

// giam_sat
export const FORM_NAME_GIAM_SAT = "FORM_NAME_GIAM_SAT";
export const FORM_NAME_GIAM_SAT_SEARCH = "FORM_NAME_GIAM_SAT_SEARCH";


// Thanh lý tài sản
export const FORM_NAME_THANH_LY_TAI_SAN = "FORM_NAME_THANH_LY_TAI_SAN";
export const FORM_NAME_THANH_LY_TAI_SAN_SEARCH = "FORM_NAME_THANH_LY_TAI_SAN_SEARCH";

export const FORM_NAME_THONG_KE_BAO_CAO_SU_KIEN = "FORM_NAME_THONG_KE_BAO_CAO_SU_KIEN";

export const FORM_NAME_THONG_KE_BAO_CAO_CONG_CU_DUNG_CU = "FORM_NAME_THONG_KE_BAO_CAO_CONG_CU_DUNG_CU";
export const FORM_NAME_THONG_KE_BAO_CAO_TAI_SAN_CO_DINH = "FORM_NAME_THONG_KE_BAO_CAO_TAI_SAN_CO_DINH";




// tài chính
export const FORM_NAME_TAI_CHINH = "FORM_NAME_TAI_CHINH";
export const FORM_NAME_TAI_CHINH_SEARCH = "FORM_NAME_TAI_CHINH_SEARCH";

// LOẠI TÀI CHÍNH
export const FORM_NAME_LOAI_TAI_CHINH = "FORM_NAME_LOAI_TAI_CHINH";
export const FORM_NAME_LOAI_TAI_CHINH_SEARCH = "FORM_NAME_LOAI_TAI_CHINH_SEARCH";

// NGUỒN KINH PHÍ
export const FORM_NAME_NGUON_KINH_PHI = "FORM_NAME_NGUON_KINH_PHI";
export const FORM_NAME_NGUON_KINH_PHI_SEARCH = "FORM_NAME_NGUON_KINH_PHI_SEARCH";


// QUẢN LÝ CHÍNH SÁCH PHÁP LUÂTK 

export const FORM_NAME_THONG_KE_DAU_TU_QUAN_LY_DIA_PHUONG = "FORM_NAME_THONG_KE_DAU_TU_QUAN_LY_DIA_PHUONG";
export const FORM_NAME_THONG_KE_MAU_KIEM_NGHIEM = "FORM_NAME_THONG_KE_MAU_KIEM_NGHIEM";
export const FORM_NAME_THONG_KE_MAU_THUC_PHAM_NN = "FORM_NAME_THONG_KE_MAU_THUC_PHAM_NN";
export const FORM_NAME_THONG_KE_DANH_MUC_TRUYEN_THONG = "FORM_NAME_THONG_KE_DANH_MUC_TRUYEN_THONG";
export const FORM_NAME_THONG_KE_KET_QUA_KIEM_NGHIEM_TP = "FORM_NAME_THONG_KE_KET_QUA_KIEM_NGHIEM_TP";
export const FORM_NAME_THONG_KE_KET_QUA_THANH_KIEM_TRA_ATTP = "FORM_NAME_THONG_KE_KET_QUA_THANH_KIEM_TRA_ATTP";
export const FORM_NAME_THONG_KE_KET_QUA_THUC_HIEN_TTHC = "FORM_NAME_THONG_KE_KET_QUA_THUC_HIEN_TTHC";
export const FORM_NAME_THONG_KE_QUAN_LY_CHO_SIEU_THI = "FORM_NAME_THONG_KE_QUAN_LY_CHO_SIEU_THI";
export const FORM_NAME_THONG_KE_SU_DUNG_KINH_PHI_DIA_PHUONG = "FORM_NAME_THONG_KE_SU_DUNG_KINH_PHI_DIA_PHUONG";
export const FORM_NAME_THONG_KE_SU_DUNG_KINH_PHI_TRUNG_UONG = "FORM_NAME_THONG_KE_SU_DUNG_KINH_PHI_TRUNG_UONG";
export const FORM_NAME_THONG_KE_GOS_NHIEM_TPNN = "FORM_NAME_THONG_KE_GOS_NHIEM_TPNN";
export const FORM_NAME_THONG_KE_GOS_NHIEM_TPYTE = "FORM_NAME_THONG_KE_GOS_NHIEM_TPYTE";
export const FORM_NAME_THONG_KE_TONG_HOP_TINH_HINH_VSATTP = "FORM_NAME_THONG_KE_TONG_HOP_TINH_HINH_VSATTP";
export const FORM_NAME_THONG_KE_XAY_DUNG_CSVC_DIA_PHUONG = "FORM_NAME_THONG_KE_XAY_DUNG_CSVC_DIA_PHUONG";
export const FORM_NAME_DANH_GIA_HANG_SAO = "FORM_NAME_DANH_GIA_HANG_SAO";

