export const PORT = "http://192.168.5.169:6969/"

export const SOCKET_ACTION_LOGIN = "SOCKET_ACTION_LOGIN";
export const SOCKET_ACTION_LOGOUT = "SOCKET_ACTION_LOGOUT";

export const SOCKET_ACTION_UPDATE_PERMISSION = "SOCKET_ACTION_UPDATE_PERMISSION";