/**
 *  START_DEFAULT
 */
export const PAGE_KEY_DEFAULT = "PAGE_KEY_DEFAULT";
/**
 *  END_DEFAULT
 */

/**
 *  START_SYSTEM
 *  Hệ thống
 */
export const PAGE_KEY_PERMISSION = "PAGE_KEY_PERMISSION";
export const PAGE_KEY_ACCOUNT = "PAGE_KEY_ACCOUNT";
export const PAGE_KEY_ACCOUNT_GROUP = "PAGE_KEY_ACCOUNT_GROUP";
export const PAGE_KEY_SERVICE = "PAGE_KEY_SERVICE";
export const PAGE_KEY_CAU_HINH = "PAGE_KEY_CAU_HINH";
/**
 *  END_SYSTEM
 */

/**
 *  START_DM
 */
export const PAGE_KEY_DIA_BAN = "PAGE_KEY_DIA_BAN";
/**
 *  END_DM
 */

/**
 *  START_QLCSSXKD
 *  Quản lý cơ sở sản xuất kinh doanh
 */
export const PAGE_KEY_LINH_VUC = "PAGE_KEY_LINH_VUC";
export const PAGE_KEY_LOAI_HINH_CO_SO = "PAGE_KEY_LOAI_HINH_CO_SO";
export const PAGE_KEY_CO_SO_SAN_XUAT_KINH_DOANH = "PAGE_KEY_CO_SO_SAN_XUAT_KINH_DOANH";
export const PAGE_KEY_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO = "PAGE_KEY_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO";
export const PAGE_KEY_HO_SO_TIEP_NHAN_MOT_CUA = "PAGE_KEY_HO_SO_TIEP_NHAN_MOT_CUA";
export const PAGE_KEY_QUAN_LY_PHONG_BAN = "PAGE_KEY_QUAN_LY_PHONG_BAN";
export const PAGE_KEY_DOAN_THAM_DINH = "PAGE_KEY_DOAN_THAM_DINH";
/**
 *  END_QLCSSXKD
 */

/**
 *  START_QLVBPL
 *  Quản lý văn bản pháp luật
 */
export const PAGE_KEY_VAN_BAN_PHAP_LUAT = "PAGE_KEY_VAN_BAN_PHAP_LUAT";
export const PAGE_KEY_VBPL_LINH_VUC = "PAGE_KEY_VBPL_LINH_VUC";
/**
 *  END_QLVBPL
 */


/**
*  START_QLQG
*  Quản lý quốc gia
*/
export const PAGE_KEY_QUAN_LY_QUOC_GIA = "PAGE_KEY_QUAN_LY_QUOC_GIA";
/**
 *  END_QLVBPL
 */


/**
*  START_QLTS
*  Quản lý tài sản
*     tài sản
*/
export const PAGE_KEY_QUAN_LY_TAI_SAN = "PAGE_KEY_QUAN_LY_TAI_SAN";
export const PAGE_KEY_QUAN_LY_TAI_SAN_LIST_DETAIL = "PAGE_KEY_QUAN_LY_TAI_SAN_LIST_DETAIL";
export const PAGE_KEY_QUAN_LY_CAP_PHAT_TAI_SAN = "PAGE_KEY_QUAN_LY_CAP_PHAT_TAI_SAN";
export const PAGE_KEY_QUAN_LY_DANH_MUC_LOAI_TAI_SAN = "PAGE_KEY_QUAN_LY_DANH_MUC_LOAI_TAI_SAN";

export const PAGE_KEY_THONG_KE_BAO_CAO_TAI_SAN_CO_DINH = "PAGE_KEY_THONG_KE_BAO_CAO_TAI_SAN_CO_DINH";
export const PAGE_KEY_THONG_KE_BAO_CAO_CONG_CU_DUNG_CU = "PAGE_KEY_THONG_KE_BAO_CAO_CONG_CU_DUNG_CU";
/**
 *  END_QLCSSXKD
 */

/**
*  START_QLDN
*  Quản lý đoàn vào
*/
export const PAGE_KEY_QUAN_LY_DOAN_VAO = "PAGE_KEY_QUAN_LY_DOAN_VAO";

// Quản lý đoàn ra
export const PAGE_KEY_QUAN_LY_DOAN_RA = "PAGE_KEY_QUAN_LY_DOAN_RA";

/**
 *  END_QLCSSXKD
 */





/**
*  START_QLTS
*  Quản lý nghi phep
*     nghi phep
*/
export const PAGE_KEY_THONG_TIN_NGHI_PHEP = "PAGE_KEY_THONG_TIN_NGHI_PHEP";
export const PAGE_KEY_QUAN_LY_NGHI_PHEP = "PAGE_KEY_QUAN_LY_NGHI_PHEP";
export const PAGE_KEY_QUAN_LY_CONG_TAC = "PAGE_KEY_QUAN_LY_CONG_TAC";
export const PAGE_KEY_CAU_HINH_NGHI_PHEP = "PAGE_KEY_CAU_HINH_NGHI_PHEP";
export const PAGE_KEY_THONG_KE_BAO_CAO_NGHI_PHEP = "PAGE_KEY_THONG_KE_BAO_CAO_NGHI_PHEP";
/**
 *  END_QLCSSXKD
 */




/**
 *  START_QLNS
 *  Quản lý nhân sự
 */
export const PAGE_KEY_NHAN_SU = "PAGE_KEY_NHAN_SU";
export const PAGE_KEY_NHAN_SU_PHONG_BAN = "PAGE_KEY_NHAN_SU_PHONG_BAN";
export const PAGE_KEY_NHAN_SU_DANHHIEU_THIDUA = "PAGE_KEY_NHAN_SU_DANHHIEU_THIDUA";
export const PAGE_KEY_NHAN_SU_CHUONGTRINH_DAOTAOTAPHUAN = "PAGE_KEY_NHAN_SU_CHUONGTRINH_DAOTAOTAPHUAN";
export const PAGE_KEY_NHAN_SU_THONGTIN_KHENTHUONG = "PAGE_KEY_NHAN_SU_THONGTIN_KHENTHUONG";
export const PAGE_KEY_NHAN_SU_THONGTIN_NGHIPHEP = "PAGE_KEY_NHAN_SU_THONGTIN_NGHIPHEP";
export const PAGE_KEY_NHAN_SU_THONGTIN_NGHIPHEP_USER = "PAGE_KEY_NHAN_SU_THONGTIN_NGHIPHEP_USER";
export const PAGE_KEY_NHAN_SU_THONGTIN_TAISANCONG = "PAGE_KEY_NHAN_SU_THONGTIN_TAISANCONG";
export const PAGE_KEY_NHAN_SU_THONGTIN_DAOTAOTAPHUAN = "PAGE_KEY_NHAN_SU_THONGTIN_DAOTAOTAPHUAN";
/**
 *  END_QLNS
 */

/**
 *  START_QLQTDTXLNDTP
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 */
export const PAGE_KEY_QTDT_XL_HO_SO_NGO_DOC_THUC_PHAM = "PAGE_KEY_QTDT_XL_HO_SO_NGO_DOC_THUC_PHAM";
export const PAGE_KEY_QTDT_XL_DIEU_TRA_NGO_DOC_THUC_PHAM = "PAGE_KEY_QTDT_XL_DIEU_TRA_NGO_DOC_THUC_PHAM";
export const PAGE_KEY_QTDT_XL_DIEU_TRA_NGO_DOC_THUC_PHAM_CSLQ = "PAGE_KEY_QTDT_XL_DIEU_TRA_NGO_DOC_THUC_PHAM_CSLQ";
export const PAGE_KEY_QTDT_XL_XU_LY_NGO_DOC_THUC_PHAM = "PAGE_KEY_QTDT_XL_XU_LY_NGO_DOC_THUC_PHAM";
export const PAGE_KEY_QTDT_XL_THONG_KE_BAO_CAO = "PAGE_KEY_QTDT_XL_THONG_KE_BAO_CAO";
export const PAGE_KEY_QTDT_XL_THONG_KE_BAO_CAO_CHI_TIET = "PAGE_KEY_QTDT_XL_THONG_KE_BAO_CAO_CHI_TIET";
/**
 *  END_QLQTDTXLNDTP
 */

/**
 *  START_QLTTTCB
 *  Quản lý thủ tục tự công bố
 */
export const PAGE_KEY_HO_SO_TU_CONG_BO = "PAGE_KEY_HO_SO_TU_CONG_BO";
export const PAGE_KEY_THONG_BAO_HO_SO_TU_CONG_BO = "PAGE_KEY_THONG_BAO_HO_SO_TU_CONG_BO";
export const PAGE_KEY_CONG_TAC_HAU_KIEM = "PAGE_KEY_CONG_TAC_HAU_KIEM";
export const PAGE_KEY_CONG_TAC_THONGKE_BAOCAO = "PAGE_KEY_CONG_TAC_THONGKE_BAOCAO";

export const PAGE_KEY_TCB_NHOM = "PAGE_KEY_TCB_NHOM";
export const PAGE_KEY_TCB_PHAN_NHOM = "PAGE_KEY_TCB_PHAN_NHOM";
/**
 *  END_QLTTTCB
 */

/**
 *  START_QLQTDTNV
 *  Quản lý quy trình điều tra nghiệp vụ
 */
export const PAGE_KEY_QTNVTT_KE_HOACH_THANH_TRA = "PAGE_KEY_QTNVTT_KE_HOACH_THANH_TRA";
export const PAGE_KEY_QTNVTT_CUOC_THANH_TRA = "PAGE_KEY_QTNVTT_CUOC_THANH_TRA";
export const PAGE_KEY_QTNVTT_DOAN_THANH_TRA = "PAGE_KEY_QTNVTT_DOAN_THANH_TRA";
export const PAGE_KEY_QTNVTT_TKBC_DSCS = "PAGE_KEY_QTNVTT_TKBC_DSCS";
export const PAGE_KEY_QTNVTT_TKBC_CTVP = "PAGE_KEY_QTNVTT_TKBC_CTVP";
/**
 *  END_QLQTDTNV
 */

/**
 *  START_QLCTGSONTP
 *  Quản lý công tác giám sát ô nhiễm thực phẩm
 */
export const PAGE_KEY_CHI_TIEU = "PAGE_KEY_CHI_TIEU";
export const PAGE_KEY_NHOM_THUC_PHAM = "PAGE_KEY_NHOM_THUC_PHAM";
export const PAGE_KEY_DOT_KIEM_TRA = "PAGE_KEY_DOT_KIEM_TRA";
export const PAGE_KEY_QLCTGSON_THONG_KE_BAO_CAO = "PAGE_KEY_QLCTGSON_THONG_KE_BAO_CAO";
export const PAGE_KEY_QLCTGSON_THANH_LAP_DOAN_KIEM_TRA = "PAGE_KEY_QLCTGSON_THANH_LAP_DOAN_KIEM_TRA";
/**
 *  END_QLCTGSONTP
 */

/**
 *  START_QLTNVXLPAKN
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 */
export const PAGE_KEY_PAKN_HO_SO = "PAGE_KEY_PAKN_HO_SO";
export const PAGE_KEY_PAKN_BIEN_BAN_THANH_TRA = "PAGE_KEY_PAKN_BIEN_BAN_THANH_TRA";
export const PAGE_KEY_PAKN_BIEN_BAN_XU_PHAT = "PAGE_KEY_PAKN_BIEN_BAN_XU_PHAT";
/**
 *  END_QLTNVXLPAKN
 */

/**
 *  START_QLTDHSCGCNATTP
 *  Quản lý thẩm định hồ sơ cấp giấy chứng nhận an toàn thực phẩm
 */
export const PAGE_KEY_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_REPORT = "PAGE_KEY_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_REPORT";
export const PAGE_KEY_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP = "PAGE_KEY_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP";
export const PAGE_KEY_KE_HOACH_THAM_DINH_HO_SO_CAP_GCN_ATTP = "PAGE_KEY_KE_HOACH_THAM_DINH_HO_SO_CAP_GCN_ATTP";
/**
 *  END_QLTDHSCGCNATTP
 */

/**
 *  START_QLXNQC
 *  Quản lý xác nhận quảng cáo
 */
export const PAGE_KEY_XAC_NHAN_QUANG_CAO = "PAGE_KEY_XAC_NHAN_QUANG_CAO";
export const PAGE_KEY_XNQC_THONG_KE_BAO_CAO = "PAGE_KEY_XNQC_THONG_KE_BAO_CAO";
/**
 *  END_QLXNQC
 */

/**
 *  START_QLCTPAT
 *  Quản lý chuỗi thực phẩm an toàn
 */
export const PAGE_KEY_NHOM_CHUOI_THUC_PHAM = "PAGE_KEY_NHOM_CHUOI_THUC_PHAM";
export const PAGE_KEY_HO_SO_CHUOI_THUC_PHAM = "PAGE_KEY_HO_SO_CHUOI_THUC_PHAM";
export const PAGE_KEY_HO_SO_CHUOI_THUC_PHAM_THANH_VIEN = "PAGE_KEY_HO_SO_CHUOI_THUC_PHAM_THANH_VIEN";
export const PAGE_KEY_KE_HOACH_THAM_DINH_HO_SO_CTP = "PAGE_KEY_KE_HOACH_THAM_DINH_HO_SO_CTP";
export const PAGE_KEY_CHUOI_THUCPHAM_ANTOAN_REPORT = "PAGE_KEY_CHUOI_THUCPHAM_ANTOAN_REPORT";
/**
 *  END_QLCTPAT
 */

/**
 *  START_QLCTXNKTATTP
 *  Quản lý công tác xác nhận kiến thức attp
 *      Hồ sơ xác nhận kiến thức attp
 */
export const PAGE_KEY_HO_SO_XAC_NHAN_KTATTP = "PAGE_KEY_HO_SO_XAC_NHAN_KTATTP";
/**
 *  Quản lý công tác xác nhận kiến thức attp
 *      Đợt xác nhận kiến thức attp
 */
export const PAGE_KEY_DOT_XAC_NHAN_KTATTP = "PAGE_KEY_DOT_XAC_NHAN_KTATTP";
/**
 *  Quản lý công tác xác nhận kiến thức attp
 *      thống kê báo cáo
 */
export const PAGE_KEY_XAC_NHAN_KTATTP_THONG_KE_BAO_CAO = "PAGE_KEY_XAC_NHAN_KTATTP_THONG_KE_BAO_CAO";
/**
 *  END_QLCTXNKTATTP
 */

/**
 *  START_BCTH
 *  Báo cáo tổng hợp
 */
export const PAGE_KEY_BAO_CAO_TONG_HOP = "PAGE_KEY_BAO_CAO_TONG_HOP";
/**
 *  END_BCTH
 */

/**
 *  START QLBM
 *  Quản lý biểu mẫu
 */
export const PAGE_KEY_QUAN_LY_BIEU_MAU = "PAGE_KEY_QUAN_LY_BIEU_MAU";
/**
 *  END QLBM
 */

/**
 *  START QLKHTC
 *  Quản lý kế hoạch tài chính
 */
export const PAGE_KEY_QUAN_LY_KE_HOACH_TAI_CHINH = "PAGE_KEY_QUAN_LY_KE_HOACH_TAI_CHINH";
/**
 *  END QLKHTC
 *  Quản lý kế hoạch tài chính
 */



/**
*  START_QLCSPL
*  Quản lý chính sách pháp luật
*     đầu tư quản lý attp địa phương
*/
export const PAGE_KEY_QUAN_LY_ATTP_DIA_PHUONG = "PAGE_KEY_QUAN_LY_ATTP_DIA_PHUONG";

// kết quả thanh kiểm tra attp
export const PAGE_KEY_KET_QUA_THANH_KIEM_TRA_ATTP = "PAGE_KEY_KET_QUA_THANH_KIEM_TRA_ATTP";

// kết quả kiểm nghiệm tp
export const PAGE_KEY_KET_QUA_KIEM_NGHIEM_TP = "PAGE_KEY_KET_QUA_KIEM_NGHIEM_TP";

// gos nhiem tpnn
export const PAGE_KEY_GOS_NHIEM_TPNN = "PAGE_KEY_GOS_NHIEM_TPNN";

// gos nhiem tpyt
export const PAGE_KEY_GOS_NHIEM_TPYT = "PAGE_KEY_GOS_NHIEM_TPYT";

// Ket quả thực hiện tthc
export const PAGE_KEY_KET_QUA_THUC_HIEN_TTHC = "PAGE_KEY_KET_QUA_THUC_HIEN_TTHC";

// Quản lý chợ siêu thị
export const PAGE_KEY_QUAN_LY_CHO_SIEU_THI = "PAGE_KEY_QUAN_LY_CHO_SIEU_THI";

// Su dung kinh phi dia phuong
export const PAGE_KEY_SU_DUNG_KINH_PHI_DIA_PHUONG = "PAGE_KEY_SU_DUNG_KINH_PHI_DIA_PHUONG";

// Su dung kinh phi trung uong
export const PAGE_KEY_SU_DUNG_KINH_PHI_TRUNG_UONG = "PAGE_KEY_SU_DUNG_KINH_PHI_TRUNG_UONG";

// tổng tình hình vệ sinh attp
export const PAGE_KEY_TONG_TINH_HINH_VSATTP = "PAGE_KEY_TONG_TINH_HINH_VSATTP";

// xây dựng cơ sở vật chất địa phương
export const PAGE_KEY_XAY_DUNG_CSVC_DIA_PHUONG = "PAGE_KEY_XAY_DUNG_CSVC_DIA_PHUONG";

// mẫu kiểm nghiêm
export const PAGE_KEY_MAU_KIEM_NGHIEM = "PAGE_KEY_MAU_KIEM_NGHIEM";


// mẫu thực phẩm nn
export const PAGE_KEY_MAU_THUC_PHAM_NN = "PAGE_KEY_MAU_THUC_PHAM_NN";


// truyền thông
export const PAGE_KEY_TRUYEN_THONG = "PAGE_KEY_TRUYEN_THONG";
/**
 *  END_QLCSPL
 */


/**
*  START quản lý giám sát attp
*/
export const PAGE_KEY_SU_KIEN = "PAGE_KEY_SU_KIEN";
export const PAGE_KEY_LOAI_SU_KIEN = "PAGE_KEY_LOAI_SU_KIEN";
export const PAGE_KEY_KE_HOACH_GIAM_SAT_ATTP = "PAGE_KEY_KE_HOACH_GIAM_SAT_ATTP";
export const PAGE_KEY_KE_HOACH_GIAM_SAT_ATTP_QUYETDINH = "PAGE_KEY_KE_HOACH_GIAM_SAT_ATTP_QUYETDINH";
export const PAGE_KEY_CHI_TIET_SU_KIEN = "PAGE_KEY_CHI_TIET_SU_KIEN";
export const PAGE_KEY_GIAM_SAT_ATTP = "PAGE_KEY_GIAM_SAT_ATTP";
export const PAGE_KEY_DANH_SACH_CHI_TIET_THONG_KE_BAO_CAO = "PAGE_KEY_DANH_SACH_CHI_TIET_THONG_KE_BAO_CAO";
export const PAGE_KEY_DANH_SACH_GIAM_SAT_ATTP_THONG_KE_BAO_CAO = "PAGE_KEY_DANH_SACH_GIAM_SAT_ATTP_THONG_KE_BAO_CAO";
export const PAGE_KEY_DANH_SACH_KE_HOACH_GIAM_SAT_THONG_KE_BAO_CAO = "PAGE_KEY_DANH_SACH_KE_HOACH_GIAM_SAT_THONG_KE_BAO_CAO";
export const PAGE_KEY_DANH_SACH_DANH_SACH_SU_KIEN_THONG_KE_BAO_CAO = "PAGE_KEY_DANH_SACH_DANH_SACH_SU_KIEN_THONG_KE_BAO_CAO";
/**
 *  START quản lý giám sát attp
 */

/**
*  START quản lý thanh lý tài sản
*/
export const PAGE_KEY_QUAN_LY_THANH_LY_TAI_SAN = "PAGE_KEY_QUAN_LY_THANH_LY_TAI_SAN";
export const PAGE_KEY_QUAN_LY_TAI_CHINH = "PAGE_KEY_QUAN_LY_TAI_CHINH";
export const PAGE_KEY_LOAI_TAI_CHINH = "PAGE_KEY_LOAI_TAI_CHINH";
export const PAGE_KEY_NGUON_KINH_PHI = "PAGE_KEY_NGUON_KINH_PHI";

export const PAGE_KEY_DANH_MUC_CHO = "PAGE_KEY_DANH_MUC_CHO";
export const PAGE_KEY_NHOM_NGANH_HANG = "PAGE_KEY_NHOM_NGANH_HANG";
export const PAGE_KEY_HO_TIEU_THUONG = "PAGE_KEY_HO_TIEU_THUONG";
export const PAGE_KEY_LO_KINH_DOANH = "PAGE_KEY_LO_KINH_DOANH";
export const PAGE_KEY_BAO_CAO_HO_TIEU_THUONG = "PAGE_KEY_BAO_CAO_HO_TIEU_THUONG";

/**
 *  START quản lý thanh lý tài sản
 */


export const PAGE_KEY_DAU_TU_QUAN_LY_DIA_PHUONG_THONG_KE_BAO_CAO = "PAGE_KEY_DAU_TU_QUAN_LY_DIA_PHUONG_THONG_KE_BAO_CAO";
export const PAGE_KEY_MAU_KIEM_NGHIEM_THONG_KE_BAO_CAO = "PAGE_KEY_MAU_KIEM_NGHIEM_THONG_KE_BAO_CAO";
export const PAGE_KEY_MAU_THUC_PHAM_NN_THONG_KE_BAO_CAO = "PAGE_KEY_MAU_THUC_PHAM_NN_THONG_KE_BAO_CAO";
export const PAGE_KEY_DANH_MUC_TRUYEN_THONG_THONG_KE_BAO_CAO = "PAGE_KEY_DANH_MUC_TRUYEN_THONG_THONG_KE_BAO_CAO";
export const PAGE_KEY_KET_QUA_KIEM_NGHIEM_TP_THONG_KE_BAO_CAO = "PAGE_KEY_KET_QUA_KIEM_NGHIEM_TP_THONG_KE_BAO_CAO";
export const PAGE_KEY_KET_QUA_THANH_KIEM_TRA_ATTP_THONG_KE_BAO_CAO = "PAGE_KEY_KET_QUA_THANH_KIEM_TRA_ATTP_THONG_KE_BAO_CAO";
export const PAGE_KEY_KET_QUA_THUC_HIEN_TTHC_THONG_KE_BAO_CAO = "PAGE_KEY_KET_QUA_THUC_HIEN_TTHC_THONG_KE_BAO_CAO";
export const PAGE_KEY_QUAN_LY_CHO_SIEU_THI_THONG_KE_BAO_CAO = "PAGE_KEY_QUAN_LY_CHO_SIEU_THI_THONG_KE_BAO_CAO";
export const PAGE_KEY_SU_DUNG_KINH_PHI_DIA_PHUONG_THONG_KE_BAO_CAO = "PAGE_KEY_SU_DUNG_KINH_PHI_DIA_PHUONG_THONG_KE_BAO_CAO";
export const PAGE_KEY_SU_DUNG_KINH_PHI_TRUNG_UONG_THONG_KE_BAO_CAO = "PAGE_KEY_SU_DUNG_KINH_PHI_TRUNG_UONG_THONG_KE_BAO_CAO";
export const PAGE_KEY_GOS_NHIEM_TPNN_THONG_KE_BAO_CAO = "PAGE_KEY_GOS_NHIEM_TPNN_THONG_KE_BAO_CAO";
export const PAGE_KEY_GOS_NHIEM_TPYT_THONG_KE_BAO_CAO = "PAGE_KEY_GOS_NHIEM_TPYT_THONG_KE_BAO_CAO";
export const PAGE_KEY_TONG_HOP_TINH_HINH_VSATTP_THONG_KE_BAO_CAO = "PAGE_KEY_TONG_HOP_TINH_HINH_VSATTP_THONG_KE_BAO_CAO";
export const PAGE_KEY_XAY_DUNG_CSVC_DIA_PHUONG_THONG_KE_BAO_CAO = "PAGE_KEY_XAY_DUNG_CSVC_DIA_PHUONG_THONG_KE_BAO_CAO";
export const PAGE_KEY_DANH_GIA_HANG_SAO = "PAGE_KEY_DANH_GIA_HANG_SAO";

