/**
 *  CONSTRUCT
 *  export const TYPE_....
 */

export const TYPE_AUTHENTICATED_CHECKED = "TYPE_AUTHENTICATED_CHECKED";
export const TYPE_AUTHENTICATED = "TYPE_AUTHENTICATED";
export const TYPE_UNAUTHENTICATED = "TYPE_UNAUTHENTICATED";
export const TYPE_AUTHENTICATION_ERROR = "TYPE_AUTHENTICATION_ERROR";
export const TYPE_PAGINATION = "TYPE_PAGINATION";
export const TYPE_SELECT_ROW = "TYPE_SELECT_ROW";
export const TYPE_ACTIONS = "TYPE_ACTIONS";
export const TYPE_CONTROLLERS = "TYPE_CONTROLLERS";

export const TYPE_NOTIFICATION_PAGE_LIST = "TYPE_NOTIFICATION_PAGE_LIST";
export const TYPE_NOTIFICATION_LOAD_MORE_PAGE = "TYPE_NOTIFICATION_LOAD_MORE_PAGE";

export const TYPE_NOTIFICATION_LIST = "TYPE_NOTIFICATION_LIST";
export const TYPE_NOTIFICATION_NEW = "TYPE_NOTIFICATION_NEW";

export const TYPE_NOTIFICATION_LOAD_NEW = "TYPE_NOTIFICATION_LOAD_NEW";
export const TYPE_NOTIFICATION_LOAD_MORE = "TYPE_NOTIFICATION_LOAD_MORE";

export const TYPE_NOTIFICATION_TICK_RECEIVED = "TYPE_NOTIFICATION_TICK_RECEIVED";
export const TYPE_NOTIFICATION_TICK_NOT_RECEIVED = "TYPE_NOTIFICATION_TICK_NOT_RECEIVED";
export const TYPE_NOTIFICATION_TICK_RECEIVED_ALL = "TYPE_NOTIFICATION_TICK_RECEIVED_ALL";

export const TYPE_NOTIFICATION_TICK_NOT_SEEN = "TYPE_NOTIFICATION_TICK_NOT_SEEN";
export const TYPE_NOTIFICATION_TICK_SEEN = "TYPE_NOTIFICATION_TICK_SEEN";
export const TYPE_NOTIFICATION_TICK_SEEN_ALL = "TYPE_NOTIFICATION_TICK_SEEN_ALL";

export const TYPE_NOTIFICATION_DELETE = "TYPE_NOTIFICATION_DELETE";
export const TYPE_NOTIFICATION_COUNT = "TYPE_NOTIFICATION_COUNT";
export const TYPE_NOTIFICATION_COUNT_INCREASE = "TYPE_NOTIFICATION_COUNT_INCREASE";
export const TYPE_NOTIFICATION_COUNT_DECREASE = "TYPE_NOTIFICATION_COUNT_DECREASE";

export const TYPE_CONFIG_NOTIFICATION = "TYPE_CONFIG_NOTIFICATION";

export const TYPE_CONFIG_HISTORY_DOWNLOAD = "TYPE_CONFIG_HISTORY_DOWNLOAD";
export const TYPE_CONFIG_HISTORY_SEARCH = "TYPE_CONFIG_HISTORY_SEARCH";
export const TYPE_CONFIG_HISTORY_SEARCH_REOMVE = "TYPE_CONFIG_HISTORY_SEARCH_REOMVE";
export const TYPE_CONFIG_HISTORY_SEARCH_REOMVE_ALL = "TYPE_CONFIG_HISTORY_SEARCH_REOMVE_ALL";

export const TYPE_SYNC_PROCESS_CREATE = "TYPE_SYNC_PROCESS_CREATE";
export const TYPE_SYNC_PROCESS_UPDATE = "TYPE_SYNC_PROCESS_UPDATE";
export const TYPE_SYNC_PROCESS_DELETE = "TYPE_SYNC_PROCESS_DELETE";

export const TYPE_ERROR_400 = "TYPE_ERROR_400";
export const TYPE_ERROR_401 = "TYPE_ERROR_401";
export const TYPE_ERROR_403 = "TYPE_ERROR_403";
export const TYPE_ERROR_404 = "TYPE_ERROR_404";
export const TYPE_ERROR_500 = "TYPE_ERROR_500";

export const TYPE_COMMON_SEARCH = "TYPE_COMMON_SEARCH";
export const TYPE_COMMON_SEARCH_REFRESH = "TYPE_COMMON_SEARCH_REFRESH";

export const TYPE_LAYOUT_MENU_LEFT = "TYPE_LAYOUT_MENU_LEFT";
export const TYPE_LAYOUT_MENU_RIGHT = "TYPE_LAYOUT_MENU_RIGHT";
export const TYPE_LAYOUT_TABLE = "TYPE_LAYOUT_TABLE";
export const TYPE_LAYOUT_FORM = "TYPE_LAYOUT_FORM";

export const TYPE_START_LOADING = "TYPE_START_LOADING";
export const TYPE_END_LOADING = "TYPE_END_LOADING";

export const TYPE_PARAMETER = "TYPE_PARAMETER";
export const TYPE_RESET_STORE = "TYPE_RESET_STORE";

export const TYPE_MENU_DISPLAY = "TYPE_MENU_DISPLAY";
export const TYPE_MENU_HIDDEN = "TYPE_MENU_HIDDEN";
export const TYPE_MENU_LIST = "TYPE_MENU_LIST";
export const TYPE_NAVIGATION_LIST = "TYPE_NAVIGATION_LIST";
export const TYPE_CUSTOM_ACTION_LIST = "TYPE_CUSTOM_ACTION_LIST";

export const TYPE_PERMISSION_MENU = "TYPE_PERMISSION_MENU";
export const TYPE_PERMISSION_LIST = "TYPE_PERMISSION_LIST";
export const TYPE_PERMISSION_EDIT = "TYPE_PERMISSION_EDIT";
export const TYPE_PERMISSION_CREATE = "TYPE_PERMISSION_CREATE";
export const TYPE_PERMISSION_UPDATE = "TYPE_PERMISSION_UPDATE";
export const TYPE_PERMISSION_UPDATES = "TYPE_PERMISSION_UPDATES";
export const TYPE_PERMISSION_DELETE = "TYPE_PERMISSION_DELETE";
export const TYPE_PERMISSION_GET_PRIVILIGED = "TYPE_PERMISSION_GET_PRIVILIGED";

export const TYPE_GET_MENU_LEFT = "TYPE_GET_MENU_LEFT";
export const TYPE_DIA_BAN_TREE = "TYPE_DIA_BAN_TREE";

// TYPE HISTORY_DOWNLOAD================================================
export const TYPE_HISTORY_DOWNLOAD_LIST = "TYPE_HISTORY_DOWNLOAD_LIST";
export const TYPE_HISTORY_DOWNLOAD_EDIT = "TYPE_HISTORY_DOWNLOAD_EDIT";
export const TYPE_HISTORY_DOWNLOAD_CREATE = "TYPE_HISTORY_DOWNLOAD_CREATE";
export const TYPE_HISTORY_DOWNLOAD_UPDATE = "TYPE_HISTORY_DOWNLOAD_UPDATE";
export const TYPE_HISTORY_DOWNLOAD_DELETE = "TYPE_HISTORY_DOWNLOAD_DELETE";

// TYPE CAU_HINH================================================
export const TYPE_CAU_HINH_LIST = "TYPE_CAU_HINH_LIST";
export const TYPE_CAU_HINH_EDIT = "TYPE_CAU_HINH_EDIT";
export const TYPE_CAU_HINH_CREATE = "TYPE_CAU_HINH_CREATE";
export const TYPE_CAU_HINH_UPDATE = "TYPE_CAU_HINH_UPDATE";
export const TYPE_CAU_HINH_DELETE = "TYPE_CAU_HINH_DELETE";

export const TYPE_CAU_HINH_LOAD_VBDH = "TYPE_CAU_HINH_LOAD_VBDH";

// TYPE DIA_BAN================================================
export const TYPE_DIA_BAN_LIST = "TYPE_DIA_BAN_LIST";
export const TYPE_DIA_BAN_EDIT = "TYPE_DIA_BAN_EDIT";
export const TYPE_DIA_BAN_CREATE = "TYPE_DIA_BAN_CREATE";
export const TYPE_DIA_BAN_UPDATE = "TYPE_DIA_BAN_UPDATE";
export const TYPE_DIA_BAN_DELETE = "TYPE_DIA_BAN_DELETE";

// TYPE ACOCUNT =================================================
export const TYPE_GET_ACCOUNT_CURRENT = "TYPE_GET_ACCOUNT_CURRENT";
export const TYPE_GET_ACCOUNT_CURRENT_CONFIG = "TYPE_GET_ACCOUNT_CURRENT_CONFIG";
export const TYPE_PHONG_BAN_ALL = "TYPE_PHONG_BAN_ALL";
export const TYPE_ACCOUNT_PROFILE = "TYPE_ACCOUNT_PROFILE";
export const TYPE_ACCOUNT_PROFILES = "TYPE_ACCOUNT_PROFILES";
export const TYPE_ACCOUNT_LIST = "TYPE_ACCOUNT_LIST";
export const TYPE_ACCOUNT_EDIT = "TYPE_ACCOUNT_EDIT";
export const TYPE_ACCOUNT_CREATE = "TYPE_ACCOUNT_CREATE";
export const TYPE_ACCOUNT_UPDATE = "TYPE_ACCOUNT_UPDATE";
export const TYPE_ACCOUNT_DELETE = "TYPE_ACCOUNT_DELETE";

// TYPE ACCOUNT GROUP===========================================
export const TYPE_ACCOUNT_GROUP_LIST = "TYPE_ACCOUNT_GROUP_LIST";
export const TYPE_ACCOUNT_GROUP_EDIT = "TYPE_ACCOUNT_GROUP_EDIT";
export const TYPE_ACCOUNT_GROUP_CREATE = "TYPE_ACCOUNT_GROUP_CREATE";
export const TYPE_ACCOUNT_GROUP_UPDATE = "TYPE_ACCOUNT_GROUP_UPDATE";
export const TYPE_ACCOUNT_GROUP_DELETE = "TYPE_ACCOUNT_GROUP_DELETE";
export const TYPE_ACCOUNT_GROUP_PERMISSIONS = "TYPE_ACCOUNT_GROUP_PERMISSIONS";

// TYPE SERVICE =================================================
export const TYPE_SERVICE_LIST = "TYPE_SERVICE_LIST";
export const TYPE_SERVICE_EDIT = "TYPE_SERVICE_EDIT";
export const TYPE_SERVICE_CREATE = "TYPE_SERVICE_CREATE";
export const TYPE_SERVICE_UPDATE = "TYPE_SERVICE_UPDATE";
export const TYPE_SERVICE_DELETE = "TYPE_SERVICE_DELETE";

//  =========================================================================================================
//  =========================================================================================================

/**
 *  Start đoàn thẩm định
 */
export const TYPE_DOAN_THAM_DINH_LIST = "TYPE_DOAN_THAM_DINH_LIST";
export const TYPE_DOAN_THAM_DINH_EDIT = "TYPE_DOAN_THAM_DINH_EDIT";
export const TYPE_DOAN_THAM_DINH_UPDATE = "TYPE_DOAN_THAM_DINH_UPDATE";
export const TYPE_DOAN_THAM_DINH_DELETE = "TYPE_DOAN_THAM_DINH_DELETE";
export const TYPE_DOAN_THAM_DINH_CREATE = "TYPE_DOAN_THAM_DINH_CREATE";
/**
 *  START_QLCSSXKD
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Danh mục
 *          Lĩnh vực
 */
export const TYPE_LINH_VUC_LIST = "TYPE_LINH_VUC_LIST";
export const TYPE_LINH_VUC_EDIT = "TYPE_LINH_VUC_EDIT";
export const TYPE_LINH_VUC_UPDATE = "TYPE_LINH_VUC_UPDATE";
export const TYPE_LINH_VUC_DELETE = "TYPE_LINH_VUC_DELETE";
export const TYPE_LINH_VUC_CREATE = "TYPE_LINH_VUC_CREATE";

/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Danh mục
 *          Loại hình cơ sở
 */
export const TYPE_GET_LOAI_HINH_CO_SO_CURRENT = "TYPE_GET_LOAI_CO_SO_CURRENT";
export const TYPE_LOAI_HINH_CO_SO_LIST = "TYPE_LOAI_HINH_CO_SO_LIST";
export const TYPE_LOAI_HINH_CO_SO_LIST_TREE = "TYPE_LOAI_HINH_CO_SO_LIST_TREE";
export const TYPE_LOAI_HINH_CO_SO_EDIT = "TYPE_LOAI_HINH_CO_SO_EDIT";
export const TYPE_LOAI_HINH_CO_SO_CREATE = "TYPE_LOAI_HINH_CO_SO_CREATE";
export const TYPE_LOAI_HINH_CO_SO_UPDATE = "TYPE_LOAI_HINH_CO_SO_UPDATE";
export const TYPE_LOAI_HINH_CO_SO_DELETE = "TYPE_LOAI_HINH_CO_SO_DELETE";

/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Cơ sở sản xuất kinh doanh
 */
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_LIST = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_LIST";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_EDIT = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_EDIT";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_UPDATE = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_UPDATE";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_DELETE = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_DELETE";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CREATE = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CREATE";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CAP_NHAT_DS_TINH_THANH = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CAP_NHAT_DS_TINH_THANH";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CAP_NHAT_DS_QUAN_HUYEN = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CAP_NHAT_DS_QUAN_HUYEN";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CAP_NHAT_DS_XA_PHUONG = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_CAP_NHAT_DS_XA_PHUONG";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_LICH_SU_THANH_TRA = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_LICH_SU_THANH_TRA";

export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_QUAN_HUYEN_LIST = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_QUAN_HUYEN_LIST";
/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Hồ sơ tiếp nhận một cửa
 */
export const TYPE_HO_SO_TIEP_NHAN_MOT_CUA_LIST = "TYPE_HO_SO_TIEP_NHAN_MOT_CUA_LIST";
export const TYPE_HO_SO_TIEP_NHAN_MOT_CUA_EDIT = "TYPE_HO_SO_TIEP_NHAN_MOT_CUA_EDIT";
export const TYPE_HO_SO_TIEP_NHAN_MOT_CUA_UPDATE = "TYPE_HO_SO_TIEP_NHAN_MOT_CUA_UPDATE";
export const TYPE_HO_SO_TIEP_NHAN_MOT_CUA_CREATE = "TYPE_HO_SO_TIEP_NHAN_MOT_CUA_CREATE";

/**
 *  Quản lý cơ sở sản xuất kinh doanh
 *      Thống kê báo cáo
 */
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO_LIST_CO_SO = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO_LIST_CO_SO";
export const TYPE_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO_SO_LIEU_TONG_HOP = "TYPE_CO_SO_SAN_XUAT_KINH_DOANH_THONG_KE_BAO_CAO_SO_LIEU_TONG_HOP";

/**
 *  Quản lý Phòng Ban
 *      Phòng Ban
 */

export const TYPE_QUAN_LY_PHONG_BAN_LIST = "TYPE_QUAN_LY_PHONG_BAN_LIST";
export const TYPE_QUAN_LY_PHONG_BAN_EDIT = "TYPE_QUAN_LY_PHONG_BAN_EDIT";
export const TYPE_QUAN_LY_PHONG_BAN_UPDATE = "TYPE_QUAN_LY_PHONG_BAN_UPDATE";
export const TYPE_QUAN_LY_PHONG_BAN_DELETE = "TYPE_QUAN_LY_PHONG_BAN_DELETE";
export const TYPE_QUAN_LY_PHONG_BAN_CREATE = "TYPE_QUAN_LY_PHONG_BAN_CREATE";


/**
 *  Quản lý quốc gia
 *      quốc gia
 */

export const TYPE_QUAN_LY_QUOC_GIA_LIST = "TYPE_QUAN_LY_QUOC_GIA_LIST";
export const TYPE_QUAN_LY_QUOC_GIA_EDIT = "TYPE_QUAN_LY_QUOC_GIA_EDIT";
export const TYPE_QUAN_LY_QUOC_GIA_UPDATE = "TYPE_QUAN_LY_QUOC_GIA_UPDATE";
export const TYPE_QUAN_LY_QUOC_GIA_DELETE = "TYPE_QUAN_LY_QUOC_GIA_DELETE";
export const TYPE_QUAN_LY_QUOC_GIA_CREATE = "TYPE_QUAN_LY_QUOC_GIA_CREATE";

/**
 *  Quản lý Tài Sản
 *      Tài Sản
 */
export const TYPE_QUAN_LY_TAI_SAN_LIST = "TYPE_QUAN_LY_TAI_SAN_LIST";
export const TYPE_QUAN_LY_TAI_SAN_LIST_DETAIL = "TYPE_QUAN_LY_TAI_SAN_LIST_DETAIL";
export const TYPE_QUAN_LY_TAI_SAN_LIST_DETAIL_UPDATE = "TYPE_QUAN_LY_TAI_SAN_LIST_DETAIL_UPDATE";
export const TYPE_QUAN_LY_TAI_SAN_EDIT = "TYPE_QUAN_LY_TAI_SAN_EDIT";
export const TYPE_QUAN_LY_TAI_SAN_UPDATE = "TYPE_QUAN_LY_TAI_SAN_UPDATE";
export const TYPE_QUAN_LY_TAI_SAN_DELETE = "TYPE_QUAN_LY_TAI_SAN_DELETE";
export const TYPE_QUAN_LY_TAI_SAN_CREATE = "TYPE_QUAN_LY_TAI_SAN_CREATE";

/**
 *  Quản lý Tài Sản
 *      Cấp phát tài sản
 */
export const TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_LIST = "TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_LIST";
export const TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_EDIT = "TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_EDIT";
export const TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_UPDATE = "TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_UPDATE";
export const TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_DELETE = "TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_DELETE";
export const TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_CREATE = "TYPE_QUAN_LY_CAP_PHAT_TAI_SAN_CREATE";

/**
 *  Quản lý Tài Sản
 *      Danh muc loai tài sản
 */
export const TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_LIST = "TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_LIST";
export const TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_EDIT = "TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_EDIT";
export const TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_UPDATE = "TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_UPDATE";
export const TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_DELETE = "TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_DELETE";
export const TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_CREATE = "TYPE_QUAN_LY_DANH_MUC_LOAI_TAI_SAN_CREATE";


/**
 *  Quản lý Đối Ngoại
 *      quản lý đoàn vào
 */
export const TYPE_QUAN_LY_DOAN_VAO_LIST = "TYPE_QUAN_LY_DOAN_VAO_LIST";
export const TYPE_QUAN_LY_DOAN_VAO_EDIT = "TYPE_QUAN_LY_DOAN_VAO_EDIT";
export const TYPE_QUAN_LY_DOAN_VAO_UPDATE = "TYPE_QUAN_LY_DOAN_VAO_UPDATE";
export const TYPE_QUAN_LY_DOAN_VAO_DELETE = "TYPE_QUAN_LY_DOAN_VAO_DELETE";
export const TYPE_QUAN_LY_DOAN_VAO_CREATE = "TYPE_QUAN_LY_DOAN_VAO_CREATE";

// Quản lý đoàn ra
export const TYPE_QUAN_LY_DOAN_RA_LIST = "TYPE_QUAN_LY_DOAN_RA_LIST";
export const TYPE_QUAN_LY_DOAN_RA_EDIT = "TYPE_QUAN_LY_DOAN_RA_EDIT";
export const TYPE_QUAN_LY_DOAN_RA_UPDATE = "TYPE_QUAN_LY_DOAN_RA_UPDATE";
export const TYPE_QUAN_LY_DOAN_RA_DELETE = "TYPE_QUAN_LY_DOAN_RA_DELETE";
export const TYPE_QUAN_LY_DOAN_RA_CREATE = "TYPE_QUAN_LY_DOAN_RA_CREATE";

/**
 *  Quản lý Thông tin cá nhân nghỉ phép
 *      Danh muc thông tin cá nhân
 */
export const TYPE_QUAN_LY_THONG_TIN_CA_NHAN_NGHI_PHEP_LIST = "TYPE_QUAN_LY_THONG_TIN_CA_NHAN_LIST";
export const TYPE_QUAN_LY_THONG_TIN_CA_NHAN_NGHI_PHEP_CREATE = "TYPE_QUAN_LY_THONG_TIN_CA_NHAN_CREATE";
export const TYPE_THONG_KE_BAO_CAO_NGHI_PHEP_LIST = "TYPE_THONG_KE_BAO_CAO_NGHI_PHEP_LIST";


// TYPE CAU_HINH_NGHI_PHEP
export const TYPE_CAU_HINH_NGHI_PHEP_LIST = "TYPE_CAU_HINH_NGHI_PHEP_LIST";
export const TYPE_CAU_HINH_NGHI_PHEP_EDIT = "TYPE_CAU_HINH_NGHI_PHEP_EDIT";
export const TYPE_CAU_HINH_NGHI_PHEP_CREATE = "TYPE_CAU_HINH_NGHI_PHEP_CREATE";
export const TYPE_CAU_HINH_NGHI_PHEP_UPDATE = "TYPE_CAU_HINH_NGHI_PHEP_UPDATE";
export const TYPE_CAU_HINH_NGHI_PHEP_DELETE = "TYPE_CAU_HINH_NGHI_PHEP_DELETE";


/**
 *  END_QLCSSXKD
 */


/**
 *  Quản lý Nghỉ Phép
 *      nghỉ phép
 */
export const TYPE_QUAN_LY_NGHI_PHEP_LIST = "TYPE_QUAN_LY_NGHI_PHEP_LIST";
export const TYPE_QUAN_LY_NGHI_PHEP_EDIT = "TYPE_QUAN_LY_NGHI_PHEP_EDIT";
export const TYPE_QUAN_LY_NGHI_PHEP_UPDATE = "TYPE_QUAN_LY_NGHI_PHEP_UPDATE";
export const TYPE_QUAN_LY_NGHI_PHEP_DELETE = "TYPE_QUAN_LY_NGHI_PHEP_DELETE";
export const TYPE_QUAN_LY_NGHI_PHEP_CREATE = "TYPE_QUAN_LY_NGHI_PHEP_CREATE";



/**
 *  Quản lý Nghỉ Phép
 *      công tác
 */
export const TYPE_QUAN_LY_CONG_TAC_LIST = "TYPE_QUAN_LY_CONG_TAC_LIST";
export const TYPE_QUAN_LY_CONG_TAC_EDIT = "TYPE_QUAN_LY_CONG_TAC_EDIT";
export const TYPE_QUAN_LY_CONG_TAC_UPDATE = "TYPE_QUAN_LY_CONG_TAC_UPDATE";
export const TYPE_QUAN_LY_CONG_TAC_DELETE = "TYPE_QUAN_LY_CONG_TAC_DELETE";
export const TYPE_QUAN_LY_CONG_TAC_CREATE = "TYPE_QUAN_LY_CONG_TAC_CREATE";

/**
 *  END_QLCSSXKD
 */



/**
 *  START_QLVBPL
 *  Quản lý văn bản pháp luật
 *      Danh mục
 *          Lĩnh vực
 */
export const TYPE_VBPL_LINH_VUC_LIST_TREE = "TYPE_VBPL_LINH_VUC_LIST_TREE";
export const TYPE_VBPL_LINH_VUC_LIST = "TYPE_VBPL_LINH_VUC_LIST";
export const TYPE_VBPL_LINH_VUC_EDIT = "TYPE_VBPL_LINH_VUC_EDIT";
export const TYPE_VBPL_LINH_VUC_UPDATE = "TYPE_VBPL_LINH_VUC_UPDATE";
export const TYPE_VBPL_LINH_VUC_DELETE = "TYPE_VBPL_LINH_VUC_DELETE";
export const TYPE_VBPL_LINH_VUC_CREATE = "TYPE_VBPL_LINH_VUC_CREATE";

/**
 *  Quản lý văn bản pháp luật
 *      Văn bản pháp luật
 */
export const TYPE_VAN_BAN_PHAP_LUAT_LIST = "TYPE_VAN_BAN_PHAP_LUAT_LIST";
export const TYPE_VAN_BAN_PHAP_LUAT_EDIT = "TYPE_VAN_BAN_PHAP_LUAT_EDIT";
export const TYPE_VAN_BAN_PHAP_LUAT_UPDATE = "TYPE_VAN_BAN_PHAP_LUAT_UPDATE";
export const TYPE_VAN_BAN_PHAP_LUAT_DELETE = "TYPE_VAN_BAN_PHAP_LUAT_DELETE";
export const TYPE_VAN_BAN_PHAP_LUAT_CREATE = "TYPE_VAN_BAN_PHAP_LUAT_CREATE";
/**
 *  END_QLVBPL
 */

/**
 *  START_QLNS
 *  Quản lý nhân sự
 *      Danh mục
 *          Phòng ban
 */
export const TYPE_PHONG_BAN_LIST = "TYPE_PHONG_BAN_LIST";
export const TYPE_PHONG_BAN_EDIT = "TYPE_PHONG_BAN_EDIT";
export const TYPE_PHONG_BAN_UPDATE = "TYPE_PHONG_BAN_UPDATE";
export const TYPE_PHONG_BAN_DELETE = "TYPE_PHONG_BAN_DELETE";
export const TYPE_PHONG_BAN_CREATE = "TYPE_PHONG_BAN_CREATE";

/**
 *  Quản lý nhân sự
 *      Danh mục
 *          Danh hiệu thi đua
 */
export const TYPE_DANHHIEU_THIDUA_LIST = "TYPE_DANHHIEU_THIDUA_LIST";
export const TYPE_DANHHIEU_THIDUA_EDIT = "TYPE_DANHHIEU_THIDUA_EDIT";
export const TYPE_DANHHIEU_THIDUA_UPDATE = "TYPE_DANHHIEU_THIDUA_UPDATE";
export const TYPE_DANHHIEU_THIDUA_DELETE = "TYPE_DANHHIEU_THIDUA_DELETE";
export const TYPE_DANHHIEU_THIDUA_CREATE = "TYPE_DANHHIEU_THIDUA_CREATE";

/**
 *  Quản lý nhân sự
 *      Nhân sự
 */
export const TYPE_NHAN_SU_LIST = "TYPE_NHAN_SU_LIST";
export const TYPE_NHAN_SU_DETAIL = "TYPE_NHAN_SU_DETAIL";
export const TYPE_NHAN_SU_EDIT = "TYPE_NHAN_SU_EDIT";
export const TYPE_NHAN_SU_UPDATE = "TYPE_NHAN_SU_UPDATE";
export const TYPE_NHAN_SU_DELETE = "TYPE_NHAN_SU_DELETE";
export const TYPE_NHAN_SU_CREATE = "TYPE_NHAN_SU_CREATE";
export const TYPE_NHAN_SU_DS_TINH_THANH = "TYPE_NHAN_SU_DS_TINH_THANH";
export const TYPE_NHAN_SU_DS_QUAN_HUYEN = "TYPE_NHAN_SU_DS_QUAN_HUYEN";
export const TYPE_NHAN_SU_DS_XA_PHUONG = "TYPE_NHAN_SU_DS_XA_PHUONG";

/**
 *  Quản lý nhân sự
 *      Thi đua khen thưởng
 */
export const TYPE_THIDUA_KHENTHUONG_LIST = "TYPE_THIDUA_KHENTHUONG_LIST";
export const TYPE_THIDUA_KHENTHUONG_CREATE = "TYPE_THIDUA_KHENTHUONG_CREATE";
export const TYPE_THIDUA_KHENTHUONG_DETAIL = "TYPE_THIDUA_KHENTHUONG_DETAIL";
export const TYPE_THIDUA_KHENTHUONG_EDIT = "TYPE_THIDUA_KHENTHUONG_EDIT";
export const TYPE_THIDUA_KHENTHUONG_UPDATE = "TYPE_THIDUA_KHENTHUONG_UPDATE";
export const TYPE_THIDUA_KHENTHUONG_DANHHIEU_UPDATE = "TYPE_THIDUA_KHENTHUONG_DANHHIEU_UPDATE";
export const TYPE_THIDUA_KHENTHUONG_NHANSU_LIST = "TYPE_THIDUA_KHENTHUONG_NHANSU_LIST";
export const TYPE_THIDUA_KHENTHUONG_PHONGBAN_LIST = "TYPE_THIDUA_KHENTHUONG_PHONGBAN_LIST";
export const TYPE_THIDUA_KHENTHUONG_DELETE = "TYPE_THIDUA_KHENTHUONG_DELETE";

/**
 *  Quản lý nhân sự
 *      Chương trình đào tạo tập huấn
 */
export const TYPE_CHUONGTRINH_DAOTAOTAPHUAN_LIST = "TYPE_CHUONGTRINH_DAOTAOTAPHUAN_LIST";
export const TYPE_CHUONGTRINH_DAOTAOTAPHUAN_EDIT = "TYPE_CHUONGTRINH_DAOTAOTAPHUAN_EDIT";
export const TYPE_CHUONGTRINH_DAOTAOTAPHUAN_UPDATE = "TYPE_CHUONGTRINH_DAOTAOTAPHUAN_UPDATE";
export const TYPE_CHUONGTRINH_DAOTAOTAPHUAN_DELETE = "TYPE_CHUONGTRINH_DAOTAOTAPHUAN_DELETE";
export const TYPE_CHUONGTRINH_DAOTAOTAPHUAN_CREATE = "TYPE_CHUONGTRINH_DAOTAOTAPHUAN_CREATE";

/**
 *  Quản lý nhân sự
 *      Đào tạo tập huấn
 */
export const TYPE_THONGTIN_DAOTAO_TAPHUAN_LIST = "TYPE_THONGTIN_DAOTAO_TAPHUAN_LIST";
export const TYPE_THONGTIN_DAOTAO_TAPHUAN_EDIT = "TYPE_THONGTIN_DAOTAO_TAPHUAN_EDIT";
export const TYPE_THONGTIN_DAOTAO_TAPHUAN_UPDATE = "TYPE_THONGTIN_DAOTAO_TAPHUAN_UPDATE";
export const TYPE_THONGTIN_DAOTAO_TAPHUAN_DELETE = "TYPE_THONGTIN_DAOTAO_TAPHUAN_DELETE";
export const TYPE_THONGTIN_DAOTAO_TAPHUAN_CREATE = "TYPE_THONGTIN_DAOTAO_TAPHUAN_CREATE";
export const TYPE_THONGTIN_DAOTAO_TAPHUAN_NHANSU_LIST = "TYPE_THONGTIN_DAOTAO_TAPHUAN_NHANSU_LIST";
export const TYPE_THONGTIN_DAOTAO_TAPHUAN_DETAIL = "TYPE_THONGTIN_DAOTAO_TAPHUAN_DETAIL";

/**
 *  Quản lý nhân sự
 *      Thông tin nghỉ phép
 */
export const TYPE_THONGTIN_NGHIPHEP_LIST = "TYPE_THONGTIN_NGHIPHEP_LIST";
export const TYPE_THONGTIN_NGHIPHEP_EDIT = "TYPE_THONGTIN_NGHIPHEP_EDIT";
export const TYPE_THONGTIN_NGHIPHEP_UPDATE = "TYPE_THONGTIN_NGHIPHEP_UPDATE";
export const TYPE_THONGTIN_NGHIPHEP_DELETE = "TYPE_THONGTIN_NGHIPHEP_DELETE";
export const TYPE_THONGTIN_NGHIPHEP_CREATE = "TYPE_THONGTIN_NGHIPHEP_CREATE";
export const TYPE_THONGTIN_NGHIPHEP_CONFIRM = "TYPE_THONGTIN_NGHIPHEP_CONFIRM";

/**
 *  Quản lý nhân sự
 *      Thông tin nghỉ phép account_current
 */
export const TYPE_THONGTIN_NGHIPHEP_USER_LIST = "TYPE_THONGTIN_NGHIPHEP_USER_LIST";
export const TYPE_THONGTIN_NGHIPHEP_USER_EDIT = "TYPE_THONGTIN_NGHIPHEP_USER_EDIT";
export const TYPE_THONGTIN_NGHIPHEP_USER_UPDATE = "TYPE_THONGTIN_NGHIPHEP_USER_UPDATE";
export const TYPE_THONGTIN_NGHIPHEP_USER_DELETE = "TYPE_THONGTIN_NGHIPHEP_USER_DELETE";
export const TYPE_THONGTIN_NGHIPHEP_USER_CREATE = "TYPE_THONGTIN_NGHIPHEP_USER_CREATE";

/**
 *  Quản lý nhân sự
 *      Tài sản công
 */
export const TYPE_THONGTIN_TAISANCONG_LIST = "TYPE_THONGTIN_TAISANCONG_LIST";
export const TYPE_THONGTIN_TAISANCONG_EDIT = "TYPE_THONGTIN_TAISANCONG_EDIT";
export const TYPE_THONGTIN_TAISANCONG_UPDATE = "TYPE_THONGTIN_TAISANCONG_UPDATE";
export const TYPE_THONGTIN_TAISANCONG_DELETE = "TYPE_THONGTIN_TAISANCONG_DELETE";
export const TYPE_THONGTIN_TAISANCONG_CREATE = "TYPE_THONGTIN_TAISANCONG_CREATE";
/**
 *  END_QLNS
 */

/**
 *  START_QLQTNVTT
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Kế hoạch thanh tra
 */
export const TYPE_QTNVTT_KE_HOACH_THANH_TRA_LIST = "TYPE_QTNVTT_KE_HOACH_THANH_TRA_LIST";
export const TYPE_QTNVTT_KE_HOACH_THANH_TRA_EDIT = "TYPE_QTNVTT_KE_HOACH_THANH_TRA_EDIT";
export const TYPE_QTNVTT_KE_HOACH_THANH_TRA_UPDATE = "TYPE_QTNVTT_KE_HOACH_THANH_TRA_UPDATE";
export const TYPE_QTNVTT_KE_HOACH_THANH_TRA_DELETE = "TYPE_QTNVTT_KE_HOACH_THANH_TRA_DELETE";
export const TYPE_QTNVTT_KE_HOACH_THANH_TRA_CREATE = "TYPE_QTNVTT_KE_HOACH_THANH_TRA_CREATE";

/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Cuộc thanh tra
 */
export const TYPE_QTNVTT_CUOC_THANH_TRA_LIST = "TYPE_QTNVTT_CUOC_THANH_TRA_LIST";
export const TYPE_QTNVTT_CUOC_THANH_TRA_THANH_TRA = "TYPE_QTNVTT_CUOC_THANH_TRA_THANH_TRA";
export const TYPE_QTNVTT_CUOC_THANH_TRA_EDIT = "TYPE_QTNVTT_CUOC_THANH_TRA_EDIT";
export const TYPE_QTNVTT_CUOC_THANH_TRA_EDIT_UPDATE_LIST = "TYPE_QTNVTT_CUOC_THANH_TRA_EDIT_UPDATE_LIST";
export const TYPE_QTNVTT_CUOC_THANH_TRA_EDIT_REMOVE_LIST = "TYPE_QTNVTT_CUOC_THANH_TRA_EDIT_REMOVE_LIST";
export const TYPE_QTNVTT_CUOC_THANH_TRA_UPDATE = "TYPE_QTNVTT_CUOC_THANH_TRA_UPDATE";
export const TYPE_QTNVTT_CUOC_THANH_TRA_KETLUAN = "TYPE_QTNVTT_CUOC_THANH_TRA_KETLUAN";
export const TYPE_QTNVTT_CUOC_THANH_TRA_DELETE = "TYPE_QTNVTT_CUOC_THANH_TRA_DELETE";
export const TYPE_QTNVTT_CUOC_THANH_TRA_CREATE = "TYPE_QTNVTT_CUOC_THANH_TRA_CREATE";
export const TYPE_QTNVTT_CUOC_THANH_TRA_CHILD_CREATE = "TYPE_QTNVTT_CUOC_THANH_TRA_CHILD_CREATE";
export const TYPE_QTNVTT_CUOC_THANH_TRA_CHILD_UPDATE = "TYPE_QTNVTT_CUOC_THANH_TRA_CHILD_UPDATE";
export const TYPE_QTNVTT_DOT_THANH_TRA_UPDATE_THONG_TIN_BAN_HANH = "TYPE_QTNVTT_DOT_THANH_TRA_UPDATE_THONG_TIN_BAN_HANH";

export const TYPE_QTNVTT_CUOC_THANH_TRA_UPDATE_KEHOACH_BY_ID_CTT = "TYPE_QTNVTT_CUOC_THANH_TRA_UPDATE_KEHOACH_BY_ID_CTT";
export const TYPE_QTNVTT_CUOC_THANH_TRA_UPDATE_KEHOACH_BY_ID = "TYPE_QTNVTT_CUOC_THANH_TRA_UPDATE_KEHOACH_BY_ID";

export const TYPE_QTNVTT_CUOC_THANH_TRA_MAU_UPDATE = "TYPE_QTNVTT_CUOC_THANH_TRA_MAU_UPDATE";

export const TYPE_QTNVTT_CUOC_THANH_TRA_XEP_HANG_CREATE = "TYPE_QTNVTT_CUOC_THANH_TRA_XEP_HANG_CREATE";
export const TYPE_QTNVTT_CUOC_THANH_TRA_XEP_HANG_UPDATE = "TYPE_QTNVTT_CUOC_THANH_TRA_XEP_HANG_UPDATE";
export const TYPE_QTNVTT_CUOC_THANH_TRA_XEP_HANG_DELETE = "TYPE_QTNVTT_CUOC_THANH_TRA_XEP_HANG_DELETE";
/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Đoàn thanh tra
 */
export const TYPE_QTNVTT_DOAN_THANH_TRA_LIST = "TYPE_QTNVTT_DOAN_THANH_TRA_LIST";
export const TYPE_QTNVTT_DOAN_THANH_TRA_EDIT = "TYPE_QTNVTT_DOAN_THANH_TRA_EDIT";
export const TYPE_QTNVTT_DOAN_THANH_TRA_UPDATE = "TYPE_QTNVTT_DOAN_THANH_TRA_UPDATE";
export const TYPE_QTNVTT_DOAN_THANH_TRA_DELETE = "TYPE_QTNVTT_DOAN_THANH_TRA_DELETE";
export const TYPE_QTNVTT_DOAN_THANH_TRA_CREATE = "TYPE_QTNVTT_DOAN_THANH_TRA_CREATE";

/**
 *  Quản lý quy trình nghiệp vụ thanh tra
 *      Biên bản thanh tra
 */
export const TYPE_QTNVTT_BIEN_BAN_LIST = "TYPE_QTNVTT_BIEN_BAN_LIST";
export const TYPE_QTNVTT_BIEN_BAN_EDIT = "TYPE_QTNVTT_BIEN_BAN_EDIT";
export const TYPE_QTNVTT_BIEN_BAN_UPDATE = "TYPE_QTNVTT_BIEN_BAN_UPDATE";
export const TYPE_QTNVTT_BIEN_BAN_DELETE = "TYPE_QTNVTT_BIEN_BAN_DELETE";
export const TYPE_QTNVTT_BIEN_BAN_CREATE = "TYPE_QTNVTT_BIEN_BAN_CREATE";
/**
 *  END_QLQTNVTT
 */

/**
 *  START_QLQTDTXLNDTP
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Hồ sơ ngộ độc thực phẩm
 */
export const TYPE_HO_SO_NGO_DOC_THUC_PHAM_LIST = "TYPE_HO_SO_NGO_DOC_THUC_PHAM_LIST";
export const TYPE_HO_SO_NGO_DOC_THUC_PHAM_EDIT = "TYPE_HO_SO_NGO_DOC_THUC_PHAM_EDIT";
export const TYPE_HO_SO_NGO_DOC_THUC_PHAM_UPDATE = "TYPE_HO_SO_NGO_DOC_THUC_PHAM_UPDATE";
export const TYPE_HO_SO_NGO_DOC_THUC_PHAM_DELETE = "TYPE_HO_SO_NGO_DOC_THUC_PHAM_DELETE";
export const TYPE_HO_SO_NGO_DOC_THUC_PHAM_CREATE = "TYPE_HO_SO_NGO_DOC_THUC_PHAM_CREATE";
export const TYPE_HO_SO_NGO_DOC_THUC_PHAM_DIEU_TRA = "TYPE_HO_SO_NGO_DOC_THUC_PHAM_DIEU_TRA";

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Điều tra ngộ độc thực phẩm
 */
export const TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_LIST = "TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_LIST";
export const TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_EDIT = "TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_EDIT";
export const TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_UPDATE = "TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_UPDATE";
export const TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_DELETE = "TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_DELETE";
export const TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_CREATE = "TYPE_DIEU_TRA_NGO_DOC_THUC_PHAM_CREATE";

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Xử lý ngộ độc thực phẩm
 */
export const TYPE_XU_LY_NGO_DOC_THUC_PHAM_LIST = "TYPE_XU_LY_NGO_DOC_THUC_PHAM_LIST";
export const TYPE_XU_LY_NGO_DOC_THUC_PHAM_EDIT = "TYPE_XU_LY_NGO_DOC_THUC_PHAM_EDIT";
export const TYPE_XU_LY_NGO_DOC_THUC_PHAM_UPDATE = "TYPE_XU_LY_NGO_DOC_THUC_PHAM_UPDATE";
export const TYPE_XU_LY_NGO_DOC_THUC_PHAM_DELETE = "TYPE_XU_LY_NGO_DOC_THUC_PHAM_DELETE";
export const TYPE_XU_LY_NGO_DOC_THUC_PHAM_CREATE = "TYPE_XU_LY_NGO_DOC_THUC_PHAM_CREATE";

/**
 *  Quản lý quy trình điều tra xử lý ngộ độc thực phẩm
 *      Thống kê báo cáo
 */
export const TYPE_QTDTXL_NDTP_THONG_KE_BAO_CAO_LIST = "TYPE_QTDTXL_NDTP_THONG_KE_BAO_CAO_LIST";
export const TYPE_QTDTXL_NDTP_THONG_KE_BAO_CAO_CHI_TIET_LIST = "TYPE_QTDTXL_NDTP_THONG_KE_BAO_CAO_CHI_TIET_LIST";
/**
 *  END_QLQTDTXLNDTP
 */

/**
 *  START_QLTTTCB
 *  Quản lý thủ tục tự công bố
 *      Hồ sơ thủ tục tự công bố
 */
export const TYPE_HO_SO_TU_CONG_BO_LIST = "TYPE_HO_SO_TU_CONG_BO_LIST";
export const TYPE_HO_SO_TU_CONG_BO_EDIT = "TYPE_HO_SO_TU_CONG_BO_EDIT";
export const TYPE_HO_SO_TU_CONG_BO_UPDATE = "TYPE_HO_SO_TU_CONG_BO_UPDATE";
export const TYPE_HO_SO_TU_CONG_BO_DELETE = "TYPE_HO_SO_TU_CONG_BO_DELETE";
export const TYPE_HO_SO_TU_CONG_BO_CREATE = "TYPE_HO_SO_TU_CONG_BO_CREATE";
export const TYPE_HO_SO_TU_CONG_BO_PHE_DUYET = "TYPE_HO_SO_TU_CONG_BO_PHE_DUYET";

export const TYPE_THONG_BAO_HO_SO_TU_CONG_BO_LIST = "TYPE_THONG_BAO_HO_SO_TU_CONG_BO_LIST";
export const TYPE_THONG_BAO_HO_SO_TU_CONG_BO_EDIT = "TYPE_THONG_BAO_HO_SO_TU_CONG_BO_EDIT";
export const TYPE_THONG_BAO_HO_SO_TU_CONG_BO_UPDATE = "TYPE_THONG_BAO_HO_SO_TU_CONG_BO_UPDATE";
export const TYPE_THONG_BAO_HO_SO_TU_CONG_BO_DELETE = "TYPE_THONG_BAO_HO_SO_TU_CONG_BO_DELETE";
export const TYPE_THONG_BAO_HO_SO_TU_CONG_BO_CREATE = "TYPE_THONG_BAO_HO_SO_TU_CONG_BO_CREATE";
export const TYPE_THONG_BAO_HO_SO_TU_CONG_BO_TRINHPHEDUYET = "TYPE_THONG_BAO_HO_SO_TU_CONG_BO_TRINHPHEDUYET";
export const TYPE_THONG_BAO_HO_SO_TU_CONG_BO_YEU_CAU_BO_SUNG_HO_SO = "TYPE_THONG_BAO_HO_SO_TU_CONG_BO_YEU_CAU_BO_SUNG_HO_SO";

export const TYPE_TCBSP_THONG_KE_BAO_CAO_LIST = "TYPE_TCBSP_THONG_KE_BAO_CAO_LIST";

/**
 *  
 *      Danh mục
 *          Nhóm - Phân nhóm
 */
export const TYPE_NHOM_PHAN_NHOM_LIST = "TYPE_NHOM_PHAN_NHOM_LIST";
export const TYPE_NHOM_PHAN_NHOM_EDIT = "TYPE_NHOM_PHAN_NHOM_EDIT";
export const TYPE_NHOM_PHAN_NHOM_UPDATE = "TYPE_NHOM_PHAN_NHOM_UPDATE";
export const TYPE_NHOM_PHAN_NHOM_DELETE = "TYPE_NHOM_PHAN_NHOM_DELETE";
export const TYPE_NHOM_PHAN_NHOM_CREATE = "TYPE_NHOM_PHAN_NHOM_CREATE";
/**
 *  
 *      Danh mục
 *          Nhóm
 */
export const TYPE_NHOM_LIST = "TYPE_NHOM_LIST";
export const TYPE_NHOM_EDIT = "TYPE_NHOM_EDIT";
export const TYPE_NHOM_UPDATE = "TYPE_NHOM_UPDATE";
export const TYPE_NHOM_DELETE = "TYPE_NHOM_DELETE";
export const TYPE_NHOM_CREATE = "TYPE_NHOM_CREATE";

/**
 *  
 *      Danh mục nhóm tài sản
 */
export const TYPE_NHOM_TAI_SAN_LIST = "TYPE_NHOM_TAI_SAN_LIST";
export const TYPE_NHOM_TAI_SAN_EDIT = "TYPE_NHOM_TAI_SAN_EDIT";
export const TYPE_NHOM_TAI_SAN_UPDATE = "TYPE_NHOM_TAI_SAN_UPDATE";
export const TYPE_NHOM_TAI_SAN_DELETE = "TYPE_NHOM_TAI_SAN_DELETE";
export const TYPE_NHOM_TAI_SAN_CREATE = "TYPE_NHOM_TAI_SAN_CREATE";

/**
 *  Quản lý thủ tục tự công bố
 *      Công tác hậu kiểm
 */
export const TYPE_CONG_TAC_HAU_KIEM_LIST = "TYPE_HO_SO_TU_CONG_BO_LIST";
export const TYPE_CONG_TAC_HAU_KIEM_CREATE = "TYPE_CONG_TAC_HAU_KIEM_CREATE";
export const TYPE_CONG_TAC_HAU_KIEM_EDIT = "TYPE_CONG_TAC_HAU_KIEM_EDIT";
export const TYPE_CONG_TAC_HAU_KIEM_UPDATE = "TYPE_CONG_TAC_HAU_KIEM_UPDATE";
export const TYPE_CONG_TAC_HAU_KIEM_DELETE = "TYPE_CONG_TAC_HAU_KIEM_DELETE";
export const TYPE_KE_HOACH_HAU_KIEM_HO_SO_TU_CONG_BO_LIST = "TYPE_KE_HOACH_HAU_KIEM_HO_SO_TU_CONG_BO_LIST";
export const TYPE_SAN_PHAM_OCOP_LIST = "TYPE_SAN_PHAM_OCOP_LIST";
export const TYPE_DANH_SACH_OCOP_DELETE = "TYPE_DANH_SACH_OCOP_DELETE"
/**
 *  END_QLTTTCB
 */

/**
 *  START_QLTNVXLPAKN
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Hồ sơ phản ánh kiến nghị
 */
export const TYPE_PAKN_HO_SO_LIST = "TYPE_PAKN_HO_SO_LIST";
export const TYPE_PAKN_HO_SO_EDIT = "TYPE_PAKN_HO_SO_EDIT";
export const TYPE_PAKN_HO_SO_UPDATE = "TYPE_PAKN_HO_SO_UPDATE";
export const TYPE_PAKN_HO_SO_DELETE = "TYPE_PAKN_HO_SO_DELETE";
export const TYPE_PAKN_HO_SO_CREATE = "TYPE_PAKN_HO_SO_CREATE";
export const TYPE_PAKN_HO_SO_KET_QUA_THANH_TRA = "TYPE_PAKN_HO_SO_KET_QUA_THANH_TRA";

export const TYPE_PAKN_HO_SO_TIEP_NHAN_LIST = "TYPE_PAKN_HO_SO_TIEP_NHAN_LIST";
export const TYPE_PAKN_HO_SO_TIEP_NHAN_EDIT = "TYPE_PAKN_HO_SO_TIEP_NHAN_EDIT";
export const TYPE_PAKN_HO_SO_TIEP_NHAN_UPDATE = "TYPE_PAKN_HO_SO_TIEP_NHAN_UPDATE";
export const TYPE_PAKN_HO_SO_TIEP_NHAN_DELETE = "TYPE_PAKN_HO_SO_TIEP_NHAN_DELETE";
export const TYPE_PAKN_HO_SO_TIEP_NHAN_CREATE = "TYPE_PAKN_HO_SO_TIEP_NHAN_CREATE";
export const TYPE_PAKN_HO_SO_TIEP_NHAN_KET_QUA_THANH_TRA = "TYPE_PAKN_HO_SO_TIEP_NHAN_KET_QUA_THANH_TRA";

export const TYPE_PAKN_HO_SO_DANG_XU_LY_LIST = "TYPE_PAKN_HO_SO_DANG_XU_LY_LIST";
export const TYPE_PAKN_HO_SO_DANG_XU_LY_EDIT = "TYPE_PAKN_HO_SO_DANG_XU_LY_EDIT";
export const TYPE_PAKN_HO_SO_DANG_XU_LY_UPDATE = "TYPE_PAKN_HO_SO_DANG_XU_LY_UPDATE";
export const TYPE_PAKN_HO_SO_DANG_XU_LY_DELETE = "TYPE_PAKN_HO_SO_DANG_XU_LY_DELETE";
export const TYPE_PAKN_HO_SO_DANG_XU_LY_CREATE = "TYPE_PAKN_HO_SO_DANG_XU_LY_CREATE";
export const TYPE_PAKN_HO_SO_DANG_XU_LY_KET_QUA_THANH_TRA = "TYPE_PAKN_HO_SO_DANG_XU_LY_KET_QUA_THANH_TRA";

/**
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Biên bản thanh tra
 */
export const TYPE_PAKN_BIEN_BAN_THANH_TRA_LIST = "TYPE_PAKN_BIEN_BAN_THANH_TRA_LIST";
export const TYPE_PAKN_BIEN_BAN_THANH_TRA_EDIT = "TYPE_PAKN_BIEN_BAN_THANH_TRA_EDIT";
export const TYPE_PAKN_BIEN_BAN_THANH_TRA_UPDATE = "TYPE_PAKN_BIEN_BAN_THANH_TRA_UPDATE";
export const TYPE_PAKN_BIEN_BAN_THANH_TRA_DELETE = "TYPE_PAKN_BIEN_BAN_THANH_TRA_DELETE";
export const TYPE_PAKN_BIEN_BAN_THANH_TRA_CREATE = "TYPE_PAKN_BIEN_BAN_THANH_TRA_CREATE";

/**
 *  Quản lý tiếp nhận và xử lý phản ánh kiến nghị
 *      Biên bản xử phạt
 */
export const TYPE_PAKN_BIEN_BAN_XU_PHAT_LIST = "TYPE_PAKN_BIEN_BAN_XU_PHAT_LIST";
export const TYPE_PAKN_BIEN_BAN_XU_PHAT_EDIT = "TYPE_PAKN_BIEN_BAN_XU_PHAT_EDIT";
export const TYPE_PAKN_BIEN_BAN_XU_PHAT_UPDATE = "TYPE_PAKN_BIEN_BAN_XU_PHAT_UPDATE";
export const TYPE_PAKN_BIEN_BAN_XU_PHAT_DELETE = "TYPE_PAKN_BIEN_BAN_XU_PHAT_DELETE";
export const TYPE_PAKN_BIEN_BAN_XU_PHAT_CREATE = "TYPE_PAKN_BIEN_BAN_XU_PHAT_CREATE";
/**
 *  END_QLTNVXLPAKN
 */

/**
 *  START_QLCTGSON
 *  Quản lý công tác giám sát ô nhiễm
 *      Danh mục
 *          Chỉ tiêu
 */
export const TYPE_QLCTDSON_DM_CHI_TIEU_LIST = "TYPE_QLCTDSON_DM_CHI_TIEU_LIST";
export const TYPE_QLCTDSON_DM_CHI_TIEU_EDIT = "TYPE_QLCTDSON_DM_CHI_TIEU_EDIT";
export const TYPE_QLCTDSON_DM_CHI_TIEU_UPDATE = "TYPE_QLCTDSON_DM_CHI_TIEU_UPDATE";
export const TYPE_QLCTDSON_DM_CHI_TIEU_DELETE = "TYPE_QLCTDSON_DM_CHI_TIEU_DELETE";
export const TYPE_QLCTDSON_DM_CHI_TIEU_CREATE = "TYPE_QLCTDSON_DM_CHI_TIEU_CREATE";

/**
 *  Quản lý công tác giám sát ô nhiễm
 *      Danh mục
 *          Loại thực phẩm
 */
export const TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_LIST = "TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_LIST";
export const TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_EDIT = "TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_EDIT";
export const TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_UPDATE = "TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_UPDATE";
export const TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_DELETE = "TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_DELETE";
export const TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_CREATE = "TYPE_QLCTDSON_DM_LOAI_THUC_PHAM_CREATE";

/**
 *  Quản lý công tác giám sát ô nhiễm
 *      Đợt kiểm tra
 */
export const TYPE_QLCTDSON_DOT_KIEM_TRA_LIST = "TYPE_QLCTDSON_DOT_KIEM_TRA_LIST";
export const TYPE_QLCTDSON_DOT_KIEM_TRA_EDIT = "TYPE_QLCTDSON_DOT_KIEM_TRA_EDIT";
export const TYPE_QLCTDSON_DOT_KIEM_TRA_UPDATE = "TYPE_QLCTDSON_DOT_KIEM_TRA_UPDATE";
export const TYPE_QLCTDSON_DOT_KIEM_TRA_DELETE = "TYPE_QLCTDSON_DOT_KIEM_TRA_DELETE";
export const TYPE_QLCTDSON_DOT_KIEM_TRA_CREATE = "TYPE_QLCTDSON_DOT_KIEM_TRA_CREATE";
export const TYPE_DOT_KIEM_TRA_CO_SO_LIST = "TYPE_DOT_KIEM_TRA_CO_SO_LIST";

/**
 *  Quản lý công tác giám sát ô nhiễm
 *      Thống kê báo cáo
 */
export const TYPE_QLCTDSON_THONG_KE_BAO_CAO_LIST = "TYPE_QLCTDSON_THONG_KE_BAO_CAO_LIST";
/**
 *  END_QLCTGSONTP
 */

/**
 *  START_QLTDCGCNATTP
 *  Quản lý thẩm định cấp giấy chứng nhận an toàn thực phẩm
 *      Hồ sơ cấp giấy chứng nhận
 */
export const TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_LIST = "TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_LIST";
export const TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_EDIT = "TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_EDIT";
export const TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_UPDATE = "TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_UPDATE";
export const TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_DELETE = "TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_DELETE";
export const TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_CREATE = "TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_CREATE";

/**
 *  Quản lý thẩm định cấp giấy chứng nhận an toàn thực phẩm
 *      Thống kê báo cáo
 */
export const TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_REPORT_LIST = "TYPE_HO_SO_CAP_GIAY_CHUNG_NHAN_ATTP_REPORT_LIST";

/**
 *  Quản lý thẩm định cấp giấy chứng nhận an toàn thực phẩm
 *      Kế hoạch thẩm định
 */
export const TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_LIST = "TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_LIST";
export const TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_EDIT = "TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_EDIT";
export const TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_UPDATE = "TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_UPDATE";
export const TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_DELETE = "TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_DELETE";
export const TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_CREATE = "TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_CREATE";
export const TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_HO_SO_LIST = "TYPE_KE_HOACH_THAM_DINH_HO_SO_ATTP_HO_SO_LIST";
/**
 *  END_QLTDCGCNATTP
 */

/**
 * START_QLXNQC
 * Quản lý xác nhận quảng cáo
 *     Xác nhận quảng cáo
 */
export const TYPE_XAC_NHAN_QUANG_CAO_LIST = "TYPE_XAC_NHAN_QUANG_CAO_LIST";
export const TYPE_XAC_NHAN_QUANG_CAO_EDIT = "TYPE_XAC_NHAN_QUANG_CAO_EDIT";
export const TYPE_XAC_NHAN_QUANG_CAO_UPDATE = "TYPE_XAC_NHAN_QUANG_CAO_UPDATE";
export const TYPE_XAC_NHAN_QUANG_CAO_DELETE = "TYPE_XAC_NHAN_QUANG_CAO_DELETE";
export const TYPE_XAC_NHAN_QUANG_CAO_CREATE = "TYPE_XAC_NHAN_QUANG_CAO_CREATE";

/**
  * Quản lý xác nhận quảng cáo
  *     Thống kê báo cáo
  */
export const TYPE_XNQC_BAO_CAO_THONG_KE_LIST = "TYPE_XNQC_BAO_CAO_THONG_KE_LIST";
/**
 *  END_QLXNQC
 */

/**
 *  START_QLCTPAT
 *  Quản lý chuỗi thực phẩm an toàn
 *      Nhóm chuỗi thực phẩm
 */
export const TYPE_NHOM_CHUOI_THUC_PHAM_LIST = "TYPE_NHOM_CHUOI_THUC_PHAM_LIST";
export const TYPE_NHOM_CHUOI_THUC_PHAM_EDIT = "TYPE_NHOM_CHUOI_THUC_PHAM_EDIT";
export const TYPE_NHOM_CHUOI_THUC_PHAM_UPDATE = "TYPE_NHOM_CHUOI_THUC_PHAM_UPDATE";
export const TYPE_NHOM_CHUOI_THUC_PHAM_DELETE = "TYPE_NHOM_CHUOI_THUC_PHAM_DELETE";
export const TYPE_NHOM_CHUOI_THUC_PHAM_CREATE = "TYPE_NHOM_CHUOI_THUC_PHAM_CREATE";

/**
 *  Quản lý chuỗi thực phẩm an toàn
 *      Kế hoạch thẩm định
 */
export const TYPE_KE_HOACH_THAM_DINH_HS_CTP_LIST = "TYPE_KE_HOACH_THAM_DINH_HS_CTP_LIST";
export const TYPE_KE_HOACH_THAM_DINH_HS_CTP_EDIT = "TYPE_KE_HOACH_THAM_DINH_HS_CTP_EDIT";
export const TYPE_KE_HOACH_THAM_DINH_HS_CTP_UPDATE = "TYPE_KE_HOACH_THAM_DINH_HS_CTP_UPDATE";
export const TYPE_KE_HOACH_THAM_DINH_HS_CTP_DELETE = "TYPE_KE_HOACH_THAM_DINH_HS_CTP_DELETE";
export const TYPE_KE_HOACH_THAM_DINH_HS_CTP_CREATE = "TYPE_KE_HOACH_THAM_DINH_HS_CTP_CREATE";
export const TYPE_KE_HOACH_THAM_DINH_HS_CTP_HO_SO_LIST = "TYPE_KE_HOACH_THAM_DINH_HS_CTP_HO_SO_LIST";

/**
 *  Quản lý chuỗi thực phẩm an toàn
 *      Hồ sơ chuỗi thực phẩm
 */
export const TYPE_HO_SO_CHUOI_THUC_PHAM_LIST = "TYPE_HO_SO_CHUOI_THUC_PHAM_LIST";
export const TYPE_HO_SO_CHUOI_THUC_PHAM_EDIT = "TYPE_HO_SO_CHUOI_THUC_PHAM_EDIT";
export const TYPE_HO_SO_CHUOI_THUC_PHAM_UPDATE = "TYPE_HO_SO_CHUOI_THUC_PHAM_UPDATE";
export const TYPE_HO_SO_CHUOI_THUC_PHAM_DELETE = "TYPE_HO_SO_CHUOI_THUC_PHAM_DELETE";
export const TYPE_HO_SO_CHUOI_THUC_PHAM_CREATE = "TYPE_HO_SO_CHUOI_THUC_PHAM_CREATE";

export const TYPE_CHUOI_THUCPHAM_ANTOAN_REPORT_LIST = "TYPE_CHUOI_THUCPHAM_ANTOAN_REPORT_LIST";
/**
 *  END_QLCTPAT
 */

/**
 *  START_QLCTXNKTATTP
 *  Quản lý xác nhận kiến thức attp
 *      Hồ sơ xác nhận kiến thức attp
 */
export const TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_LIST = "TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_LIST";
export const TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_EDIT = "TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_EDIT";
export const TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_UPDATE = "TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_UPDATE";
export const TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_DELETE = "TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_DELETE";
export const TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_CREATE = "TYPE_XNKT_ATTP_HO_SO_XAC_NHAN_CREATE";

/**
 *  Quản lý xác nhận kiến thức attp
 *      Đợt xác nhận kiến thức attp
 */
export const TYPE_XNKT_ATTP_DOT_XAC_NHAN_LIST = "TYPE_XNKT_ATTP_DOT_XAC_NHAN_LIST";
export const TYPE_XNKT_ATTP_DOT_XAC_NHAN_EDIT = "TYPE_XNKT_ATTP_DOT_XAC_NHAN_EDIT";
export const TYPE_XNKT_ATTP_DOT_XAC_NHAN_UPDATE = "TYPE_XNKT_ATTP_DOT_XAC_NHAN_UPDATE";
export const TYPE_XNKT_ATTP_DOT_XAC_NHAN_DELETE = "TYPE_XNKT_ATTP_DOT_XAC_NHAN_DELETE";
export const TYPE_XNKT_ATTP_DOT_XAC_NHAN_CREATE = "TYPE_XNKT_ATTP_DOT_XAC_NHAN_CREATE";
export const TYPE_XNKT_ATTP_THONG_KE_BAO_CAO_LIST = "TYPE_XNKT_ATTP_THONG_KE_BAO_CAO_LIST";
/**
 *  END_QLCTXNKTATTP
 */

/**
 *  START_BCTH
 *  Báo cáo tổng hợp
 */
export const TYPE_BAO_CAO_TONG_HOP_LIST = "TYPE_BAO_CAO_TONG_HOP_LIST";
export const TYPE_BAO_CAO_TONG_HOP_EDIT = "TYPE_BAO_CAO_TONG_HOP_EDIT";
export const TYPE_BAO_CAO_TONG_HOP_UPDATE = "TYPE_BAO_CAO_TONG_HOP_UPDATE";
export const TYPE_BAO_CAO_TONG_HOP_DELETE = "TYPE_BAO_CAO_TONG_HOP_DELETE";
export const TYPE_BAO_CAO_TONG_HOP_CREATE = "TYPE_BAO_CAO_TONG_HOP_CREATE";
/**
 *  END_BCTH
 */

/**
*  Quản lý văn bản pháp luật
*      Văn bản pháp luật
*/
export const TYPE_QUAN_LY_BIEU_MAU_LIST = "TYPE_QUAN_LY_BIEU_MAU_LIST";
export const TYPE_QUAN_LY_BIEU_MAU_EDIT = "TYPE_QUAN_LY_BIEU_MAU_EDIT";
export const TYPE_QUAN_LY_BIEU_MAU_UPDATE = "TYPE_QUAN_LY_BIEU_MAU_UPDATE";
export const TYPE_QUAN_LY_BIEU_MAU_DELETE = "TYPE_QUAN_LY_BIEU_MAU_DELETE";
export const TYPE_QUAN_LY_BIEU_MAU_CREATE = "TYPE_QUAN_LY_BIEU_MAU_CREATE";
/**
 *  END quản lý biểu mẫu
 */

/**
*  Quản lý văn bản pháp luật
*      Văn bản pháp luật
*/
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_LIST = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_LIST";
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_CHUYEN_MON_LIST = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_CHUYEN_MON_LIST";
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_TONG_HOP_LIST = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_TONG_HOP_LIST";
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_EGOV_LIST = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_EGOV_LIST";
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_EDIT = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_EDIT";
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_UPDATE = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_UPDATE";
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_DELETE = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_DELETE";
export const TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_CREATE = "TYPE_QUAN_LY_KE_HOACH_TAI_CHINH_CREATE";
/**
 *  END quản lý biểu mẫu
 */


/**
*  Quản lý chính sách pháp luật
*      đầu tư qlattp địa phương 
*/
export const TYPE_QUAN_LY_ATTP_DIA_PHUONG_LIST = "TYPE_QUAN_LY_ATTP_DIA_PHUONG_LIST";
export const TYPE_QUAN_LY_ATTP_DIA_PHUONG_EDIT = "TYPE_QUAN_LY_ATTP_DIA_PHUONG_EDIT";
export const TYPE_QUAN_LY_ATTP_DIA_PHUONG_UPDATE = "TYPE_QUAN_LY_ATTP_DIA_PHUONG_UPDATE";
export const TYPE_QUAN_LY_ATTP_DIA_PHUONG_DELETE = "TYPE_QUAN_LY_ATTP_DIA_PHUONG_DELETE";
export const TYPE_QUAN_LY_ATTP_DIA_PHUONG_CREATE = "TYPE_QUAN_LY_ATTP_DIA_PHUONG_CREATE";

// kết quả thanh kiểm tra attp
export const TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_LIST = "TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_LIST";
export const TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_EDIT = "TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_EDIT";
export const TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_UPDATE = "TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_UPDATE";
export const TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_DELETE = "TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_DELETE";
export const TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_CREATE = "TYPE_KET_QUA_THANH_KIEM_TRA_ATTP_CREATE";

// kết quả kiem nghiem tp attp
export const TYPE_KET_QUA_KIEM_NGHIEM_TP_LIST = "TYPE_KET_QUA_KIEM_NGHIEM_TP_LIST";
export const TYPE_KET_QUA_KIEM_NGHIEM_TP_EDIT = "TYPE_KET_QUA_KIEM_NGHIEM_TP_EDIT";
export const TYPE_KET_QUA_KIEM_NGHIEM_TP_UPDATE = "TYPE_KET_QUA_KIEM_NGHIEM_TP_UPDATE";
export const TYPE_KET_QUA_KIEM_NGHIEM_TP_DELETE = "TYPE_KET_QUA_KIEM_NGHIEM_TP_DELETE";
export const TYPE_KET_QUA_KIEM_NGHIEM_TP_CREATE = "TYPE_KET_QUA_KIEM_NGHIEM_TP_CREATE";


// gos nhiễm thực phẩm nông nghiệp
export const TYPE_GOS_NHIEM_TPNN_LIST = "TYPE_GOS_NHIEM_TPNN_LIST";
export const TYPE_GOS_NHIEM_TPNN_EDIT = "TYPE_GOS_NHIEM_TPNN_EDIT";
export const TYPE_GOS_NHIEM_TPNN_UPDATE = "TYPE_GOS_NHIEM_TPNN_UPDATE";
export const TYPE_GOS_NHIEM_TPNN_DELETE = "TYPE_GOS_NHIEM_TPNN_DELETE";
export const TYPE_GOS_NHIEM_TPNN_CREATE = "TYPE_GOS_NHIEM_TPNN_CREATE";

// gos nhiễm thực phẩm y tế
export const TYPE_GOS_NHIEM_TPYT_LIST = "TYPE_GOS_NHIEM_TPYT_LIST";
export const TYPE_GOS_NHIEM_TPYT_EDIT = "TYPE_GOS_NHIEM_TPYT_EDIT";
export const TYPE_GOS_NHIEM_TPYT_UPDATE = "TYPE_GOS_NHIEM_TPYT_UPDATE";
export const TYPE_GOS_NHIEM_TPYT_DELETE = "TYPE_GOS_NHIEM_TPYT_DELETE";
export const TYPE_GOS_NHIEM_TPYT_CREATE = "TYPE_GOS_NHIEM_TPYT_CREATE";

// kết quả thực hiện thực hiện  tthc 
export const TYPE_KET_QUA_THUC_HIEN_TTHC_LIST = "TYPE_KET_QUA_THUC_HIEN_TTHC_LIST";
export const TYPE_KET_QUA_THUC_HIEN_TTHC_EDIT = "TYPE_KET_QUA_THUC_HIEN_TTHC_EDIT";
export const TYPE_KET_QUA_THUC_HIEN_TTHC_UPDATE = "TYPE_KET_QUA_THUC_HIEN_TTHC_UPDATE";
export const TYPE_KET_QUA_THUC_HIEN_TTHC_DELETE = "TYPE_KET_QUA_THUC_HIEN_TTHC_DELETE";
export const TYPE_KET_QUA_THUC_HIEN_TTHC_CREATE = "TYPE_KET_QUA_THUC_HIEN_TTHC_CREATE";

// Quản lý chợ siêu thị
export const TYPE_QUAN_LY_CHO_SIEU_THI_LIST = "TYPE_QUAN_LY_CHO_SIEU_THI_LIST";
export const TYPE_QUAN_LY_CHO_SIEU_THI_EDIT = "TYPE_QUAN_LY_CHO_SIEU_THI_EDIT";
export const TYPE_QUAN_LY_CHO_SIEU_THI_UPDATE = "TYPE_QUAN_LY_CHO_SIEU_THI_UPDATE";
export const TYPE_QUAN_LY_CHO_SIEU_THI_DELETE = "TYPE_QUAN_LY_CHO_SIEU_THI_DELETE";
export const TYPE_QUAN_LY_CHO_SIEU_THI_CREATE = "TYPE_QUAN_LY_CHO_SIEU_THI_CREATE";

// Sử dụng kinh phí địa phương
export const TYPE_SU_DUNG_KINH_PHI_DP_LIST = "TYPE_SU_DUNG_KINH_PHI_DP_LIST";
export const TYPE_SU_DUNG_KINH_PHI_DP_EDIT = "TYPE_SU_DUNG_KINH_PHI_DP_EDIT";
export const TYPE_SU_DUNG_KINH_PHI_DP_UPDATE = "TYPE_SU_DUNG_KINH_PHI_DP_UPDATE";
export const TYPE_SU_DUNG_KINH_PHI_DP_DELETE = "TYPE_SU_DUNG_KINH_PHI_DP_DELETE";
export const TYPE_SU_DUNG_KINH_PHI_DP_CREATE = "TYPE_SU_DUNG_KINH_PHI_DP_CREATE";

// Sử dụng kinh phí TW
export const TYPE_SU_DUNG_KINH_PHI_TW_LIST = "TYPE_SU_DUNG_KINH_PHI_TW_LIST";
export const TYPE_SU_DUNG_KINH_PHI_TW_EDIT = "TYPE_SU_DUNG_KINH_PHI_TW_EDIT";
export const TYPE_SU_DUNG_KINH_PHI_TW_UPDATE = "TYPE_SU_DUNG_KINH_PHI_TW_UPDATE";
export const TYPE_SU_DUNG_KINH_PHI_TW_DELETE = "TYPE_SU_DUNG_KINH_PHI_TW_DELETE";
export const TYPE_SU_DUNG_KINH_PHI_TW_CREATE = "TYPE_SU_DUNG_KINH_PHI_TW_CREATE";


// Tổng hợp tình hình vi phạm attp
export const TYPE_TONG_HOP_TINH_HINH_VPATTP_LIST = "TYPE_TONG_HOP_TINH_HINH_VPATTP_LIST";
export const TYPE_TONG_HOP_TINH_HINH_VPATTP_EDIT = "TYPE_TONG_HOP_TINH_HINH_VPATTP_EDIT";
export const TYPE_TONG_HOP_TINH_HINH_VPATTP_UPDATE = "TYPE_TONG_HOP_TINH_HINH_VPATTP_UPDATE";
export const TYPE_TONG_HOP_TINH_HINH_VPATTP_DELETE = "TYPE_TONG_HOP_TINH_HINH_VPATTP_DELETE";
export const TYPE_TONG_HOP_TINH_HINH_VPATTP_CREATE = "TYPE_TONG_HOP_TINH_HINH_VPATTP_CREATE";

// xây dựng cơ sở vật chất attp
export const TYPE_XAY_DUNG_CSVC_ATTP_LIST = "TYPE_XAY_DUNG_CSVC_ATTP_LIST";
export const TYPE_XAY_DUNG_CSVC_ATTP_EDIT = "TYPE_XAY_DUNG_CSVC_ATTP_EDIT";
export const TYPE_XAY_DUNG_CSVC_ATTP_UPDATE = "TYPE_XAY_DUNG_CSVC_ATTP_UPDATE";
export const TYPE_XAY_DUNG_CSVC_ATTP_DELETE = "TYPE_XAY_DUNG_CSVC_ATTP_DELETE";
export const TYPE_XAY_DUNG_CSVC_ATTP_CREATE = "TYPE_XAY_DUNG_CSVC_ATTP_CREATE";

// mẫu kiểm nghiêm
export const TYPE_MAU_KIEM_NGHIEM_LIST = "TYPE_MAU_KIEM_NGHIEM_LIST";
export const TYPE_MAU_KIEM_NGHIEM_EDIT = "TYPE_MAU_KIEM_NGHIEM_EDIT";
export const TYPE_MAU_KIEM_NGHIEM_UPDATE = "TYPE_MAU_KIEM_NGHIEM_UPDATE";
export const TYPE_MAU_KIEM_NGHIEM_DELETE = "TYPE_MAU_KIEM_NGHIEM_DELETE";
export const TYPE_MAU_KIEM_NGHIEM_CREATE = "TYPE_MAU_KIEM_NGHIEM_CREATE";


// MẪU THỰC PHẨM NÔNG NGHIỆP
export const TYPE_MAU_THUC_PHAM_NN_LIST = "TYPE_MAU_THUC_PHAM_NN_LIST";
export const TYPE_MAU_THUC_PHAM_NN_EDIT = "TYPE_MAU_THUC_PHAM_NN_EDIT";
export const TYPE_MAU_THUC_PHAM_NN_UPDATE = "TYPE_MAU_THUC_PHAM_NN_UPDATE";
export const TYPE_MAU_THUC_PHAM_NN_DELETE = "TYPE_MAU_THUC_PHAM_NN_DELETE";
export const TYPE_MAU_THUC_PHAM_NN_CREATE = "TYPE_MAU_THUC_PHAM_NN_CREATE";


// Truyền thông
export const TYPE_TRUYEN_THONG_LIST = "TYPE_TRUYEN_THONG_LIST";
export const TYPE_TRUYEN_THONG_EDIT = "TYPE_TRUYEN_THONG_EDIT";
export const TYPE_TRUYEN_THONG_UPDATE = "TYPE_TRUYEN_THONG_UPDATE";
export const TYPE_TRUYEN_THONG_DELETE = "TYPE_TRUYEN_THONG_DELETE";
export const TYPE_TRUYEN_THONG_CREATE = "TYPE_TRUYEN_THONG_CREATE";

/**
 *  END Sử dụng kinh phí địa phương
 */

/**
*  Quản lý giám sát attp
*    
*/
// sự kiện
export const TYPE_SU_KIEN_LIST = "TYPE_SU_KIEN_LIST";
export const TYPE_SU_KIEN_EDIT = "TYPE_SU_KIEN_EDIT";
export const TYPE_SU_KIEN_UPDATE = "TYPE_SU_KIEN_UPDATE";
export const TYPE_SU_KIEN_DELETE = "TYPE_SU_KIEN_DELETE";
export const TYPE_SU_KIEN_CREATE = "TYPE_SU_KIEN_CREATE";

// giám sát attp
export const TYPE_GIAM_SAT_ATTP_LIST = "TYPE_GIAM_SAT_ATTP_LIST";
export const TYPE_GIAM_SAT_ATTP_EDIT = "TYPE_GIAM_SAT_ATTP_EDIT";
export const TYPE_GIAM_SAT_ATTP_UPDATE = "TYPE_GIAM_SAT_ATTP_UPDATE";
export const TYPE_GIAM_SAT_ATTP_DELETE = "TYPE_GIAM_SAT_ATTP_DELETE";
export const TYPE_GIAM_SAT_ATTP_CREATE = "TYPE_GIAM_SAT_ATTP_CREATE";

// giám sát attp
export const TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_LIST = "TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_LIST";
export const TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_EDIT = "TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_EDIT";
export const TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_UPDATE = "TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_UPDATE";
export const TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_DELETE = "TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_DELETE";
export const TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_CREATE = "TYPE_GIAM_SAT_ATTP_QUYET_DINH_GIAM_SAT_CREATE";

// loại sự kiện
export const TYPE_LOAI_SU_KIEN_LIST = "TYPE_LOAI_SU_KIEN_LIST";
export const TYPE_LOAI_SU_KIEN_EDIT = "TYPE_LOAI_SU_KIEN_EDIT";
export const TYPE_LOAI_SU_KIEN_UPDATE = "TYPE_LOAI_SU_KIEN_UPDATE";
export const TYPE_LOAI_SU_KIEN_DELETE = "TYPE_LOAI_SU_KIEN_DELETE";
export const TYPE_LOAI_SU_KIEN_CREATE = "TYPE_LOAI_SU_KIEN_CREATE";

// kế hoach giám sát
export const TYPE_KE_HOACH_GIAM_SAT_LIST = "TYPE_KE_HOACH_GIAM_SAT_LIST";
export const TYPE_KE_HOACH_GIAM_SAT_EDIT = "TYPE_KE_HOACH_GIAM_SAT_EDIT";
export const TYPE_KE_HOACH_GIAM_SAT_UPDATE = "TYPE_KE_HOACH_GIAM_SAT_UPDATE";
export const TYPE_KE_HOACH_GIAM_SAT_DELETE = "TYPE_KE_HOACH_GIAM_SAT_DELETE";
export const TYPE_KE_HOACH_GIAM_SAT_CREATE = "TYPE_KE_HOACH_GIAM_SAT_CREATE";

// chi tiết sự kiện
export const TYPE_CHI_TIET_SU_KIEN_LIST = "TYPE_CHI_TIET_SU_KIEN_LIST";
export const TYPE_CHI_TIET_SU_KIEN_EDIT = "TYPE_CHI_TIET_SU_KIEN_EDIT";
export const TYPE_CHI_TIET_SU_KIEN_UPDATE = "TYPE_CHI_TIET_SU_KIEN_UPDATE";
export const TYPE_CHI_TIET_SU_KIEN_DELETE = "TYPE_CHI_TIET_SU_KIEN_DELETE";
export const TYPE_CHI_TIET_SU_KIEN_CREATE = "TYPE_CHI_TIET_SU_KIEN_CREATE";
/**
*  END Quản lý giám sát attp
*/


// Quản lý tài sản thanh lý
export const TYPE_QUAN_LY_TAI_SAN_THANH_LY_LIST = "TYPE_QUAN_LY_TAI_SAN_THANH_LY_LIST";
export const TYPE_QUAN_LY_TAI_SAN_THANH_LY_EDIT = "TYPE_QUAN_LY_TAI_SAN_THANH_LY_EDIT";
export const TYPE_QUAN_LY_TAI_SAN_THANH_LY_UPDATE = "TYPE_QUAN_LY_TAI_SAN_THANH_LY_UPDATE";
export const TYPE_QUAN_LY_TAI_SAN_THANH_LY_DELETE = "TYPE_QUAN_LY_TAI_SAN_THANH_LY_DELETE";
export const TYPE_QUAN_LY_TAI_SAN_THANH_LY_CREATE = "TYPE_QUAN_LY_TAI_SAN_THANH_LY_CREATE";

export const TYPE_THONG_KE_BAO_CAO_TAI_SAN_CO_DINH_LIST = "TYPE_THONG_KE_BAO_CAO_TAI_SAN_CO_DINH_LIST";
export const TYPE_THONG_KE_BAO_CAO_CONG_CU_DUNG_CU_LIST = "TYPE_THONG_KE_BAO_CAO_CONG_CU_DUNG_CU_LIST";
/**
*  Quản lý tài sản thanh lý
*/

/**
*  Quản lý giám sát attp
*     
*/
export const TYPE_THONG_KE_BAO_CAO_SU_KIEN_LIST = "TYPE_THONG_KE_BAO_CAO_SU_KIEN_LIST";
export const TYPE_THONG_KE_BAO_CAO_CHI_TIET_SU_KIEN_LIST = "TYPE_THONG_KE_BAO_CAO_CHI_TIET_SU_KIEN_LIST";
export const TYPE_THONG_KE_BAO_CAO_GIAM_SAT_ATTP_LIST = "TYPE_THONG_KE_BAO_CAO_GIAM_SAT_ATTP_LIST";
export const TYPE_THONG_KE_BAO_CAO_KE_HOACH_GIAM_SAT_LIST = "TYPE_THONG_KE_BAO_CAO_KE_HOACH_GIAM_SAT_LIST";

// quản lý tài chính
export const TYPE_TAI_CHINH_LIST = "TYPE_TAI_CHINH_LIST";
export const TYPE_TAI_CHINH_EDIT = "TYPE_TAI_CHINH_EDIT";
export const TYPE_TAI_CHINH_UPDATE = "TYPE_TAI_CHINH_UPDATE";
export const TYPE_TAI_CHINH_DELETE = "TYPE_TAI_CHINH_DELETE";
export const TYPE_TAI_CHINH_CREATE = "TYPE_TAI_CHINH_CREATE";
export const TYPE_TAI_CHINH_LICH_SU_CAP_NHAT_LIST = "TYPE_TAI_CHINH_LICH_SU_CAP_NHAT_LIST";
export const TYPE_TAI_CHINH_DIEU_CHUYEN = "TYPE_TAI_CHINH_DIEU_CHUYEN";

// quản lý tài chính thực hiện
export const TYPE_TAI_CHINH_THUC_HIEN_LIST = "TYPE_TAI_CHINH_THUC_HIEN_LIST";
export const TYPE_TAI_CHINH_THUC_HIEN_EDIT = "TYPE_TAI_CHINH_THUC_HIEN_EDIT";
export const TYPE_TAI_CHINH_THUC_HIEN_UPDATE = "TYPE_TAI_CHINH_THUC_HIEN_UPDATE";
export const TYPE_TAI_CHINH_THUC_HIEN_DELETE = "TYPE_TAI_CHINH_THUC_HIEN_DELETE";
export const TYPE_TAI_CHINH_THUC_HIEN_CREATE = "TYPE_TAI_CHINH_THUC_HIEN_CREATE";

// Loại tài chính
export const TYPE_LOAI_TAI_CHINH_LIST = "TYPE_LOAI_TAI_CHINH_LIST";
export const TYPE_LOAI_TAI_CHINH_EDIT = "TYPE_LOAI_TAI_CHINH_EDIT";
export const TYPE_LOAI_TAI_CHINH_UPDATE = "TYPE_LOAI_TAI_CHINH_UPDATE";
export const TYPE_LOAI_TAI_CHINH_DELETE = "TYPE_LOAI_TAI_CHINH_DELETE";
export const TYPE_LOAI_TAI_CHINH_CREATE = "TYPE_LOAI_TAI_CHINH_CREATE";


// Nguồn kinh phí
export const TYPE_NGUON_KINH_PHI_LIST = "TYPE_NGUON_KINH_PHI_LIST";
export const TYPE_NGUON_KINH_PHI_EDIT = "TYPE_NGUON_KINH_PHI_EDIT";
export const TYPE_NGUON_KINH_PHI_UPDATE = "TYPE_NGUON_KINH_PHI_UPDATE";
export const TYPE_NGUON_KINH_PHI_DELETE = "TYPE_NGUON_KINH_PHI_DELETE";
export const TYPE_NGUON_KINH_PHI_CREATE = "TYPE_NGUON_KINH_PHI_CREATE";


// Danh mục chợ
export const TYPE_DANH_MUC_CHO_LIST = "TYPE_DANH_MUC_CHO_LIST";
export const TYPE_DANH_MUC_CHO_EDIT = "TYPE_DANH_MUC_CHO_EDIT";
export const TYPE_DANH_MUC_CHO_UPDATE = "TYPE_DANH_MUC_CHO_UPDATE";
export const TYPE_DANH_MUC_CHO_DELETE = "TYPE_DANH_MUC_CHO_DELETE";
export const TYPE_DANH_MUC_CHO_CREATE = "TYPE_DANH_MUC_CHO_CREATE";

//Danh mục nhóm ngành hàng
export const TYPE_NHOM_NGANH_HANG_LIST = "TYPE_NHOM_NGANH_HANG_LIST";
export const TYPE_NHOM_NGANH_HANG_EDIT = "TYPE_NHOM_NGANH_HANG_EDIT";
export const TYPE_NHOM_NGANH_HANG_UPDATE = "TYPE_NHOM_NGANH_HANG_UPDATE";
export const TYPE_NHOM_NGANH_HANG_DELETE = "TYPE_NHOM_NGANH_HANG_DELETE";
export const TYPE_NHOM_NGANH_HANG_CREATE = "TYPE_NHOM_NGANH_HANG_CREATE";

//Thông tin hộ tiểu thương
export const TYPE_HO_TIEU_THUONG_LIST = "TYPE_HO_TIEU_THUONG_LIST";
export const TYPE_HO_TIEU_THUONG_EDIT = "TYPE_HO_TIEU_THUONG_EDIT";
export const TYPE_HO_TIEU_THUONG_UPDATE = "TYPE_HO_TIEU_THUONG_UPDATE";
export const TYPE_HO_TIEU_THUONG_DELETE = "TYPE_HO_TIEU_THUONG_DELETE";
export const TYPE_HO_TIEU_THUONG_CREATE = "TYPE_HO_TIEU_THUONG_CREATE";

export const TYPE_LO_KINH_DOANH_LIST = "TYPE_LO_KINH_DOANH_LIST";
export const TYPE_LO_KINH_DOANH_EDIT = "TYPE_LO_KINH_DOANH_EDIT";
export const TYPE_LO_KINH_DOANH_UPDATE = "TYPE_LO_KINH_DOANH_UPDATE";
export const TYPE_LO_KINH_DOANH_DELETE = "TYPE_LO_KINH_DOANH_DELETE";
export const TYPE_LO_KINH_DOANH_CREATE = "TYPE_LO_KINH_DOANH_CREATE";

export const TYPE_BAO_CAO_HO_TIEU_THUONG_LIST = "TYPE_BAO_CAO_HO_TIEU_THUONG_LIST";

/**
*  Quản lý chính sách pháp luât
*     
*/
export const TYPE_THONG_KE_DAU_TU_QUAN_LY_DIA_PHUONG_LIST = "TYPE_THONG_KE_DAU_TU_QUAN_LY_DIA_PHUONG_LIST";
export const TYPE_THONG_KE_MAU_KIEM_NGHIEM_LIST = "TYPE_THONG_KE_MAU_KIEM_NGHIEM_LIST";
export const TYPE_THONG_KE_MAU_THUC_PHAM_NN_LIST = "TYPE_THONG_KE_MAU_THUC_PHAM_NN_LIST";
export const TYPE_THONG_KE_DANH_MUC_TRUYEN_THONG_LIST = "TYPE_THONG_KE_DANH_MUC_TRUYEN_THONG_LIST";
export const TYPE_THONG_KE_KET_QUA_KIEM_NGHIEM_TP_LIST = "TYPE_THONG_KE_KET_QUA_KIEM_NGHIEM_TP_LIST";
export const TYPE_THONG_KE_KET_QUA_THANH_KIEM_TRA_ATTP_LIST = "TYPE_THONG_KE_KET_QUA_THANH_KIEM_TRA_ATTP_LIST";
export const TYPE_THONG_KE_KET_QUA_THUC_HIEN_TTHC_LIST = "TYPE_THONG_KE_KET_QUA_THUC_HIEN_TTHC_LIST";
export const TYPE_THONG_KE_QUAN_LY_CHO_SIEU_THI_LIST = "TYPE_THONG_KE_QUAN_LY_CHO_SIEU_THI_LIST";
export const TYPE_THONG_KE_SU_DUNG_KINH_PHI_DIA_PHUONG_LIST = "TYPE_THONG_KE_SU_DUNG_KINH_PHI_DIA_PHUONG_LIST";
export const TYPE_THONG_KE_SU_DUNG_KINH_PHI_TRUNG_UONG_LIST = "TYPE_THONG_KE_SU_DUNG_KINH_PHI_TRUNG_UONG_LIST";
export const TYPE_THONG_KE_GOS_NHIEM_TPNN_LIST = "TYPE_THONG_KE_GOS_NHIEM_TPNN_LIST";
export const TYPE_THONG_KE_GOS_NHIEM_TPYTE_LIST = "TYPE_THONG_KE_GOS_NHIEM_TPYTE_LIST";
export const TYPE_THONG_KE_TONG_HOP_TINH_HINH_VSATTP_LIST = "TYPE_THONG_KE_TONG_HOP_TINH_HINH_VSATTP_LIST";
export const TYPE_THONG_KE_XAY_DUNG_CSVC_DIA_PHUONG_LIST = "TYPE_THONG_KE_XAY_DUNG_CSVC_DIA_PHUONG_LIST";

export const TYPE_SOCKET_ACCOUNT = "TYPE_SOCKET_ACCOUNT";
export const TYPE_SOCKET_ACCOUNT_GROUP = "TYPE_SOCKET_ACCOUNT_GROUP";
export const TYPE_SOCKET_ACCOUNT_GROUP_PERMISSION = "TYPE_SOCKET_ACCOUNT_GROUP_PERMISSION";
export const TYPE_SOCKET_PERMISSION = "TYPE_SOCKET_PERMISSION";
export const TYPE_SOCKET_CONFIG = "TYPE_SOCKET_CONFIG";
//DANH MUC TIEU CHI
export const DANH_MUC_TIEU_CHI_MENU = "DANH_MUC_TIEU_CHI_MENU";
export const DANH_MUC_TIEU_CHI_LIST = "DANH_MUC_TIEU_CHI_LIST";
export const DANH_MUC_TIEU_CHI_EDIT = "DANH_MUC_TIEU_CHI_EDIT";
export const DANH_MUC_TIEU_CHI_CREATE = "DANH_MUC_TIEU_CHI_CREATE";
export const DANH_MUC_TIEU_CHI_UPDATE = "DANH_MUC_TIEU_CHI_UPDATE";
export const DANH_MUC_TIEU_CHI_UPDATES = "DANH_MUC_TIEU_CHI_UPDATES";
export const DANH_MUC_TIEU_CHI_DELETE = "DANH_MUC_TIEU_CHI_DELETE";
export const DANH_MUC_TIEU_CHI_GET_PRIVILIGED = "DANH_MUC_TIEU_CHI_GET_PRIVILIGED";
//DANH GIA XEP HANG SAO
export const TYPE_DANH_GIA_HANG_SAO_LIST = "TYPE_DANH_GIA_HANG_SAO_LIST";
export const TYPE_DANH_GIA_HANG_SAO_EDIT = "TYPE_DANH_GIA_HANG_SAO_EDIT";
export const TYPE_DANH_GIA_HANG_SAO_UPDATE = "TYPE_DANH_GIA_HANG_SAO_UPDATE";
export const TYPE_DANH_GIA_HANG_SAO_DELETE = "TYPE_DANH_GIA_HANG_SAO_DELETE";
export const TYPE_DANH_GIA_HANG_SAO_CREATE = "TYPE_DANH_GIA_HANG_SAO_CREATE";
//KE HOACH KIEM TRA TRONG O NHIEM THUC PHAM
export const TYPE_QLONATTP_KE_HOACH_THANH_TRA_LIST = "TYPE_QLONATTP_KE_HOACH_THANH_TRA_LIST";
export const TYPE_QLONATTP_KE_HOACH_THANH_TRA_EDIT = "TYPE_QLONATTP_KE_HOACH_THANH_TRA_EDIT";
export const TYPE_QLONATTP_KE_HOACH_THANH_TRA_UPDATE = "TYPE_QLONATTP_KE_HOACH_THANH_TRA_UPDATE";
export const TYPE_QLONATTP_KE_HOACH_THANH_TRA_DELETE = "TYPE_QLONATTP_KE_HOACH_THANH_TRA_DELETE";
export const TYPE_QLONATTP_KE_HOACH_THANH_TRA_CREATE = "TYPE_QLONATTP_KE_HOACH_THANH_TRA_CREATE";
//THANH LAP DOAN KIEM TRA - GIAM SAT
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_LIST = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_LIST";
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_EDIT = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_EDIT";
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_UPDATE = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_UPDATE";
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_CHILD_UPDATE = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_CHILD_UPDATE";
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_DELETE = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_DELETE";
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_CREATE = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_CREATE";
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_CHILD_CREATE = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_CHILD_CREATE";
export const TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_UPDATE_KEHOACH_BY_ID = "TYPE_QLONATTP_THANH_LAP_DOAN_KIEM_TRA_UPDATE_KEHOACH_BY_ID";